"""One-time completed physical statement inspection, not a replayable classifier."""
import workflow as w
c=w.connect()
rows=[
('raw::333',1054,6,'theory','KEEP','VI_electric_field;VII_magnetic_field;VIII_induction;IX_em_oscillations_waves','Coax/ground-plane capacitance and inductance, supplied LC transmission model, reflection continuity, capacitor addition energy and resonant impedance matching','The full A-F task supplies the lumped LC model and the ON/OFF resistor/capacitor behavior of the transistor/dot. Charging energy is electrostatic, not a quantum spectrum to be computed. Source/drain tunnelling permission is prescribed by addition-energy sign, with no tunnelling-rate law requested. Unsupplied energy-lifetime uncertainty appears only in D4(ii), a small peripheral extension with no dependency into the dominant field/circuit/matching work. Whole semantic-majority KEEP; do not rescue or split subparts.',1,True),
('raw::334',1058,6,'theory','REJECT','VII_magnetic_field;II_oscillations_waves;IV_thermodynamics','Relativistic jet density/energy/momentum transformation, ultrarelativistic gas equation of state, gyration/pulse duration, supplied cooling and spectrum laws','A1-A7 require proper-to-lab density and energy/momentum Lorentz transformations which are NOT supplied. B requires unsupplied ultrarelativistic E approximately p*c and C1-C3 require relativistic transverse inertia plus gamma/speed relations. These establish the central jet flow, equation of state and gyration results; D2 also depends on B. Although beaming angle, synchrotron power, spectrum and frozen-flux assumption are supplied, they do not close these structurally central prerequisites. Whole REJECT.',1,True),
('raw::335',1062,4,'theory','KEEP','I_force_motion','Rigid-body force/torque/energy, Euler-angle vector geometry, supplied rotating-frame derivative, frictional dissipation and Jellett invariant','All A1-A10 use Newtonian rigid-body mechanics with specified inertias, kinetic friction and explicit rotating-frame derivative rule. The final invariant is found and verified through torque and vector differentiation using the earlier symmetric-body relation; no canonical Hamiltonian/Poisson-bracket or hidden specialized top theorem must be known. Nonintegrability is context: no numerical evolution is requested. Whole KEEP.',1,False),
('raw::336',1066,8,'experimental','KEEP','I_force_motion;VII_magnetic_field;X_wave_optics','Buoyant balance using supplied magnetic-force kernel, supplied instability/spacing relation, spherical-mirror calibration, log-log fit and empirical hysteresis/energy trends','The magnetic susceptibility, full cylinder field, force density and dipole-force approximation are supplied. The ferrofluid wave dispersion and already-derived surface-tension relation are supplied, not to be reconstructed from continuum hydrodynamics. Optical mirror relation and assumed curvature power law are given; meaningful work is apparatus measurement/calibration, uncertainty, plotting and ordinary qualitative surface/magnetic energy. No unsupplied superparamagnetic or Rosensweig instability theory is needed.',1,True),
('raw::337',1070,8,'experimental','KEEP','II_oscillations_waves;VII_magnetic_field;I_force_motion','Video-based wave speed/uncertainty, supplied depth-speed law, variable-depth pulse geometry and experimental comparison of magnetic versus depth effects','The entire A-D experiment supplies v=kappa*sqrt(depth), the small-amplitude approximation and empirical magnetic attraction context. It asks for measurements, graphical parameter fit, identification of ordinary reflection/refraction/interference and comparison against measured extra depth. It does not request derivation of magnetic-fluid dispersion or microscopic magnetization. Camera frame rate and full operation appendix included. Whole KEEP.',0,False)]
for uid,fid,*rest in rows:
 u=c.execute('select * from units where screening_unit_id=?',(uid,)).fetchone();assert u['decision'] is None and u['source_file_id']==fid
out=[]
for uid,fid,np,fmt,dec,dom,phys,reason,sol,focus in rows:
 out.append(dict(screening_unit_id=uid,decision=dec,confidence='high',primary_spho_domains=dom,required_physics=phys,decision_reason=reason,external_physics_if_any='Unsupplied Lorentz density/energy/momentum transformations and relativistic particle dynamics' if dec=='REJECT' else ('Peripheral D4(ii): unsupplied energy-lifetime uncertainty; not dominant and no later dependency' if uid=='raw::333' else ''),format=fmt,page_start=1,page_end=np,visual_inspection_used=1,solution_used=sol,boundary_status='content_boundary_verified',needs_second_review=focus,evidence=f'APhO2019 original file{fid}: ALL{np} actual statement pages read through SHA cache and ALL rendered physical pages viewed, including diagrams/apparatus. Single parent with every internally lettered/numbered task retained. General instructions1052/1053 all2 pages each read. Key1055 pp2/3 text and p3 image; key1059 pp1-5 text (p2 rerun after slight truncation), pp1/4 images; key1063 p5 text verifies final invariant; key1067 all7 text and pp4/6/7 images verifies measurement/energy method. No experiment performed.'))
p=w.ROOT/'reviews/shutdown_apho_2019_5.json';w.writejson(p,out);w.decisions(p)
for uid,fid,np,fmt,*rest in rows:
 c.execute("update paper_boundary_audit set status='full_paper_boundaries_verified',observed_units=1,evidence=?,checked_at=? where file_id=?",(f'All{np} physical pages inspected. One independently headed {fmt} parent, internal tasks constitute that parent. No omitted top-level task. Experiments actual printed Q1/Q2 are acquisition4/5; same apparatus and cross-reference do not make them equivalent problems. Camera appendix belongs to E2.',w.now(),fid))
for uid in ['raw::333','raw::334','raw::335']:
 c.execute('insert or ignore into unit_files values (?,?,?,?)',(uid,1053,1111,'instructions'))
for uid in ['raw::336','raw::337']:
 c.execute('insert or ignore into unit_files values (?,?,?,?)',(uid,1052,1112,'instructions'))
# E2 explicitly refers to equipment/empirical observations from E1; preserve it too.
c.execute('insert or ignore into unit_files values (?,?,?,?)',('raw::337',1066,1127,'supplementary'))
c.execute('update units set source_quality_notes=? where screening_unit_id=?',('E2 requires new contestant-generated camera videos; no external fixed dataset or software download is specified. Full camera instructions/frame rate are in its own appendix. E1 statement1066 additionally preserved as equipment and explicitly referenced magnetic-fluid context. No original experimental data fabricated.','raw::337'))
c.execute('update units set source_quality_notes=? where screening_unit_id=?',('Official key1059 renderedp4 C1 inserts an extra sin(phi) after already writing v_perp=Omega*r; this changes the physical gyrofrequency. The R decision follows the unsupplied relativistic prerequisites, independently of this key error. Supplied radiation/cooling relations acknowledged.','raw::334'))
c.commit()
reviews=[
dict(screening_unit_id='raw::333',detail='Focused quantum prerequisite/semantic-weight check. Actual full A-F statement and key1055 p3 rendered show charging cost is ordinary capacitor work. D4(ii) does use unsupplied DeltaE*time about h, while D4(i) RC time is explicitly prescribed. This small terminal subtask has no dependency into E/F, whose ON/OFF impedances are separately supplied. The central LC transmission, electrostatics and RF matching work is allowed. Whole KEEP with peripheral external law explicitly disclosed; no rubric shift or subpart rescue.'),
dict(screening_unit_id='raw::334',detail='Theory QC Random(2026100437) selects334 and focused incomplete-supplied-model check. All6 statement images confirm only Lorentz factor named, not density/energy/momentum transformations or relativistic inertia. General instructions1053 contain constants/directions only. Official1059 p1 image explicitly uses length contraction and energy boost; p2 text uses momentum transform; p4 image uses F=gamma*m*a and gamma(speed) for pulses. B2 uses E approximately p*c; D2 depends on B adiabatic equation. These central dependencies outweigh supplied power/spectrum/forward-cone relations. Whole REJECT confirmed, consistent with fixed SR anchor.'),
dict(screening_unit_id='raw::336',detail='Experiment QC Random(2026100438) selects336, focused exotic fluid-model check. All8 actual pages provide force kernel and BOTH instability dispersion/final surface-tension formula. No fluid stability PDE derivation requested. Official1067 all7 text and images4/6/7 confirm log-log slope, empirical hysteresis and ordinary qualitative energy trends; quantitative microscopic hysteresis law not needed. Entire A-D KEEP. E1 and E2 remain independently graded parents despite shared apparatus; both provenance relationships preserved.')]
p=w.ROOT/'reviews/shutdown_apho_2019_focused_seeded_3.json';w.writejson(p,reviews);w.review(p)
print('Saved four KEEP/one REJECT, five physical-boundary audits and three focused/QC reviews.')
