"""One-time source inspection, not a replayable classifier."""
import random
import workflow as w
c=w.connect()
rows=[
('raw::342',1082,8,'theory','I_force_motion;VII_magnetic_field;VI_electric_field','Supplied circulation/magnetic analogy/advection, pressure and gravity balance, kinetic-energy and momentum integration, electric force and image-boundary geometry','The statement supplies quantized circulation, superposition with explicit magnetic-wire equivalence, vortex advection and loop energy/momentum. Free-surface shapes follow ordinary centripetal/hydrostatic balance. Charged-ring velocity follows energy power F*v together with momentum rate F and given U(R),P(R), not an unsupplied canonical Hamiltonian law. Wall boundary is explicitly zero normal flow; image vortices and subsequent energy conservation/ODE geometry use the supplied field model. No microscopic helium theory or unsupplied specialized fluid constitutive law controls the task.'),
('raw::343',1090,6,'theory','I_force_motion','Newtonian gravitational scattering, impact parameter and collision flux, energy loss and orbital shrinkage; supplied gravitational-radiation power and merger cutoff','General information explicitly restricts motion to Newtonian point masses. Weak scattering is ordinary impulse, slingshot speed assumption is given, collision rate follows particle flux. Both gravitational-wave power with quadrupole definition and gravitational radius cutoff are explicitly supplied. The final three-stage evolution is energy balance and integration; no GR field equation, spacetime metric or unsupplied black-hole physics required.'),
('raw::344',1099,6,'theory','I_force_motion;VII_magnetic_field;VIII_induction','Rigid-body angular momentum/energy and precession geometry, residual-fuel dissipation minimum, Faraday induction and magnetic moment/torque, body-frame differentiation and averaged relaxation','Angular-momentum components and angular-velocity vector addition are explicitly given. Free precession follows energy/angular-momentum conservation and vector projection. Residual fuel needs only internal-force energy minimization, not a sloshing model. Shell eddy currents follow Faraday/Ohm integration with self-inductance neglected; geomagnetic dipole field is supplied. Changing field in the rotating frame is trigonometric differentiation, followed by torque and ordinary averaged first-order evolution.'),
('raw::345',1106,19,'experimental','X_wave_optics;IX_em_oscillations_waves','Grating diffraction, supplied Bragg-Snell/porosity/spectral-width models, optical measurements, linearization/fits and supplied layered-reflection table','The entire A-E experiment supplies Bragg-Snell interference, dry/wet effective-index formulas and spectral-width relation. Final structure identification uses explicitly given phase/intensity sum and the complete candidate/table appendix, not unsupplied band-structure/transfer-matrix theory. Main work is apparatus alignment, diffraction angles, intensity measurement, fitting and data/model comparison. X,Y,Z and A-E are internal tasks of ONE20-point experiment, not separate top-level problems.')]
for uid,fid,*rest in rows:
 u=c.execute('select decision,source_file_id from units where screening_unit_id=?',(uid,)).fetchone();assert u['decision'] is None and u['source_file_id']==fid
out=[]
for uid,fid,np,fmt,dom,phys,reason in rows:
 out.append(dict(screening_unit_id=uid,decision='KEEP',confidence='high',primary_spho_domains=dom,required_physics=phys,external_physics_if_any='',decision_reason=reason,format=fmt,page_start=1,page_end=np,visual_inspection_used=1,solution_used=1,boundary_status='content_boundary_verified',needs_second_review=True,evidence=f'APhO2017 original file{fid}: ALL{np} cached statement pages read and ALL physical page renders viewed. Original1106p19 includes candidate structures and intensity table absent from text extraction. Official1084all11 text plus images8/11 checks energy-power and wall method;1092pp3-5 text+p4 image checks GR supplied-law application;1101pp3-12 text plus images7/11/12 checks precession/eddy/rotating-frame method;1115pp1-3 and6-10 text plus images2/10 checks optical/table identification. No laboratory measurements claimed.'))
p=w.ROOT/'reviews/shutdown_apho_2017_4.json';w.writejson(p,out);w.decisions(p)
for uid,fid,np,fmt,*rest in rows:
 c.execute("update paper_boundary_audit set status='full_paper_boundaries_verified',observed_units=1,evidence=?,checked_at=? where file_id=?",(f'All{np} actual physical pages inspected: one top-level {fmt} task, all internal sections retained. No omitted independent problem. Photonic experiment actual Q1 is acquisitionQ4; A-E and three samples are internal tasks, full candidate appendix onp19.',w.now(),fid))
c.execute('update units set source_quality_notes=? where screening_unit_id=?',('Official1115p2 B1 uses650nm while original1106p5 lists659nm and keyp7 uses659nm. This numerical source inconsistency is retained/disclosed, not treated as a scope prerequisite. Actual originalp19 provides indispensable candidate structure diagrams/table; contestants produce measurements, no external fixed dataset specified.','raw::345'))
c.commit()
assert random.Random(2026100441).sample(['raw::342','raw::343','raw::344'],1)==['raw::344']
reviews=[
dict(screening_unit_id='raw::342',detail='Focused advanced-fluid prerequisite check. Actual full statement supplies circulation, magnetic-wire field correspondence, superposition, advection, U(R),P(R) and zero wall-normal-flow condition. Official1084p8 image explicitly derives v=dU/dP using dU/dt=Fv=(dP/dt)v, which is ordinary power/momentum balance, not assumed Hamiltonian dynamics. Pp9-11 text and p11image use image vortices and energy conservation; equivalent trajectory follows supplied velocity ODEs. Free surface is centripetal/gravity equilibrium (keyp2). Complete supplied model closes task; whole KEEP.'),
dict(screening_unit_id='raw::343',detail='Focused supplied-GR check. Original1090p1 expressly states only Newtonian gravity except radiation; p4 explicitly supplies radiation-power formula, quadrupole and rg. Official1092p4 image substitutes Newtonian orbital speed into supplied power and integrates shrinkage; pp3/5text uses impact-parameter flux and ordinary orbital energy. No metric, redshift or relativistic transformation needed. Whole KEEP.'),
dict(screening_unit_id='raw::344',detail='Theory QC Random(2026100441) selects344. Full six-page original statement and key1101pp3-12 text confirm angular-momentum geometry plus Faraday/Ohm shell ring integration. Rendered7/11/12 shows ordinary induction, trigonometric body-frame field derivative and averaged torque ODE. Fuel sloshing rate is never requested: only final conserved-L energy minimum. No unsupplied continuum-liquid or specialized rotational formalism required. KEEP confirmed.'),
dict(screening_unit_id='raw::345',detail='Experiment QC seed2026100442 over singleton345 and focused photonic supplied-model check. Original full19 pages include Bragg-Snell, effective-index dry/wet laws, spectral-width formula, classical phase/intensity sums and p19 candidate table/structures. Key1115p10image matches observed minimum depths/missing orders to that given table; no band-gap calculation demanded. Numerical red-laser discrepancy650/659nm recorded separately. ONE20-point top-level task, all A-E/internal samples retained. Whole KEEP confirmed.')]
p=w.ROOT/'reviews/shutdown_apho_2017_focused_seeded_4.json';w.writejson(p,reviews);w.review(p)
print('Saved four KEEP decisions, four boundary audits and four focused/QC reviews.')
