"""Actual-content decisions for the complete 12-page 2025 paper."""
import workflow as w
c=w.connect();I='I_force_motion';II='II_oscillations_waves';III='III_ideal_gas';IV='IV_thermodynamics';VI='VI_electric_field';VII='VII_magnetic_field';VIII='VIII_induction';IX='IX_em_oscillations_waves';X='X_wave_optics';XII='XII_atomic_nuclear'
rows=[
(1,1,1,'KEEP',[I,X],'Ray reflection under a stipulated inelastic collision model','The fictional reflection law is defined by ordinary restitution; deriving mirror images and periscope geometry requires no unsupplied optical theory.'),
(2,1,1,'KEEP',[I],'Repeated inelastic bead collisions and restitution limits','Newtonian momentum and the given restitution coefficient determine the entire collision sequence; plotting its count is mathematical.'),
(3,1,1,'KEEP',[I],'Corner-cutting geometry, friction and banked circular motion','Ordinary lateral force limits and route geometry determine the travel-time comparison.'),
(4,2,2,'KEEP',[I,III],'Ideal-gas particle shielding, collision momentum flux and orbit drag','The hypothetical gravity mechanism and gas assumptions are stated; kinetic theory, restitution and Newtonian motion supply the physical method.'),
(5,2,2,'KEEP',[I],'Drawer contact forces, Coulomb friction and rigid-body torque','The diagram and contact assumptions specify a Newtonian friction problem; the failure context introduces no external theory.'),
(6,2,2,'KEEP',[I,II],'Hydrostatic equilibrium of a density-graded cylinder and small oscillations','The mass distribution is supplied. Integrating buoyancy and gravitational torque, then linearizing motion, uses ordinary general physics.'),
(7,3,3,'REJECT',[],'Canonical Hamiltonian dynamics for a nonstandard momentum-dependent Hamiltonian','Canonical phase-space evolution is not supplied. It is the central physical machinery for both requested derivations; a Hamiltonian expression alone does not give the Newtonian force/velocity relations.'),
(8,3,3,'KEEP',[IV],'Thermometer expansion in a supplied spatial temperature profile','The source explicitly stipulates local temperatures and negligible column heat transfer; expansion and volume integration suffice.'),
(9,3,3,'REJECT',[II],'Moving-observer relativistic dispersion and Klein-Gordon field relation','The second part centrally requires an unsupplied Klein-Gordon equation and its frame-dependent dispersion; ordinary sound Doppler alone does not cover most meaningful work.'),
(10,4,4,'REJECT',[II],'Continuum elastic wave mode conversion, interface traction and guided-layer dispersion','Lamé constants are named but their continuum constitutive/evolution laws and traction matching are not supplied. These specialized elasticity laws determine both main tasks.'),
(11,4,4,'BORDERLINE',[II,X],'Elastic longitudinal/transverse rays and cylindrical caustics','Geometrical wave-ray caustics are usable, but inclusion of longitudinal/transverse conversion at glued elastic interfaces may require unsupplied continuum-wave machinery. Without a solution the intended dependence is not clear enough for KEEP.'),
(12,4,4,'KEEP',[I,II],'Small vibrations of a chain with an explicitly supplied pair potential','The displayed kinetic term and Morse pair interaction give all forces by differentiation. Newtonian linearization and wave-like normal modes suffice without external solid-state theory.'),
(13,4,4,'KEEP',[IX,X],'Polarized reflection at a dielectric sphere and ray-intensity mapping','Ordinary Maxwell interface reasoning, polarization and geometrical optics determine reflected energy and angles; no specialized optical-material theory is required.'),
(14,5,5,'KEEP',[VI],'Electrostatic equilibrium and induced charge redistribution between spheres','Coulomb fields, conductor equipotential boundaries and induction are expressly in scope; solving the boundary-value geometry is mathematical.'),
(15,5,5,'KEEP',[VI],'Infinite resistor grid with four specified missing edges','The rendered graph requires Ohm/Kirchhoff laws and mathematical lattice analysis; the advanced network mathematics is not external physics.'),
(16,5,5,'KEEP',[VII],'Wire magnetic field, dipole torque and force gradients','Biot-Savart superposition and ordinary magnetic dipole forces control all parts; plotting and asymptotics are mathematical.'),
(17,6,6,'KEEP',[II,VII],'Moving compass in the periodic field of a helical solenoid','The actual coil drawing and pitch define magnetic torque and driven rotational response; unusual motion does not require microscopic magnetism.'),
(18,6,6,'REJECT',[],'Heisenberg-picture spin operator evolution and ladder-operator matrix elements','Spin commutator dynamics and the Heisenberg equation are unsupplied and central throughout. Listed hydrogen/Zeeman topics do not supply this general nonlinear operator problem.'),
(19,7,7,'KEEP',[XII],'Radioactive daughter populations, exponential fits and detector sensitivity','Ordinary decay-chain rate equations and the provided time data determine the detector response; fitting/calibration are eligible experimental-analysis tools.'),
(20,7,7,'BORDERLINE',[],'Ecological equilibrium and stability under a specified added death term','Only the mortality perturbation is specified; the unperturbed population function is not. It is unclear whether generic differential-equation reasoning suffices or an unsupplied ecological interaction model is intended.'),
(21,8,8,'REJECT',[II,VI],'Driven quantum oscillator ground-state survival probabilities','The oscillator potential is supplied, but quantum state evolution and overlap/coherent-state machinery are not. Those laws control every requested probability; familiar classical resonance is insufficient.'),
(22,8,9,'KEEP',[],'Simulation of an explicitly defined finite lattice phase model','The link variables, action, probability weights, boundaries and measured observable are all defined. Sampling and plotting require numerical/mathematical tools, without unsupplied gauge-field physics.'),
(23,10,10,'KEEP',[],'Finite binary-state graph topology with explicitly linked model definitions','The task explicitly discards spin-glass energies. The linked article defines binary spin configurations and the relevant graph; the remaining search is combinatorial geometry, without unsupplied condensed-matter physics.'),
(24,10,10,'KEEP',[],'Matrix entropy optimization under explicitly supplied bipartition definitions','The source defines state arrays, reduced matrices and the entropy to optimize. Tensor linear algebra and numerical search supply the work; no unsupplied quantum dynamics or measurement law is required.'),
(25,11,12,'REJECT',[I],'Relativistic photon rocket, proper-time itinerary and integrated acceleration','The supplied fitness rate does not supply proper-time, photon-rocket or relativistic trajectory laws. Those external laws are essential to the entire travel calculation.')]
out=[]
for n,pstart,pend,decision,domains,physics,reason in rows:
 u=c.execute('select * from units where source_file_id=3116 and problem_number=?',(str(n),)).fetchone();assert u and u['decision'] is None
 out.append(dict(screening_unit_id=u['screening_unit_id'],decision=decision,confidence='medium' if decision=='BORDERLINE' else 'high',primary_spho_domains=';'.join(domains),required_physics=physics,external_physics_if_any=physics if decision=='REJECT' else 'Elastic mode-conversion ambiguity' if n==11 else 'Unspecified population model' if n==20 else '',decision_reason=reason,page_start=pstart,page_end=pend,format='data_analysis' if n in (19,22,23) else 'theory',visual_inspection_used=1,solution_used=0,boundary_status='content_boundary_verified',evidence='Complete source file 3116 physical pp1-12 read in embedded text and actual page renders. Each printed 1-25 problem remains whole; internal lettered parts are not screening units. Q23 source-linked article v2 model and Figure 10 separately inspected and preserved with provenance.'))
c.execute("update paper_boundary_audit set status='full_paper_boundaries_verified',observed_units=25,evidence=?,checked_at=? where file_id=3116",('Complete 12-page paper contains exactly printed problems 1-25, including three multipart modern/model tasks; no extra question after the final story.',w.now()))
c.commit();p=w.ROOT/'reviews/resume_ortvay_2025_25.json';w.writejson(p,out);w.decisions(p)
u=c.execute("select screening_unit_id from units where source_file_id=3116 and problem_number='19'").fetchone()[0]
c.execute('update units set source_quality_notes=? where screening_unit_id=?',('Radon daughter isotope identities/half-lives are not tabulated in the statement. Later use may need a standard decay-chain data table; no extra acquired attachment is claimed.',u))
events=[]
details={11:'Focused second reading of p4: wave speeds and short-wavelength geometry are given, but polarization conversion rules at bonded elastic interfaces are not. Ray geometry is useful; intended inclusion of converted branches remains ambiguous. BORDERLINE confirmed.',20:'Focused second reading of p7: neither functional population interaction laws nor their derivatives are specified. A generic implicit equilibrium can be written, but the requested change and critical mortality need model interpretation. Retain BORDERLINE for statement ambiguity, not merely biological context.',12:'Supplied-model check of p4: the displayed L has identifiable kinetic energy and explicit pair potential. Deriving force by minus potential gradient provides a Newtonian route, so unsupplied canonical Hamiltonian laws from Q7 are not required here. KEEP confirmed.',22:'Focused given-model check of pp8-9: link phases, plaquette multiplication, action, e^-S weight, measured observable and periodic boundaries are supplied. Implementing Metropolis sampling and detecting plotted jumps needs no unsupplied gauge theory. KEEP confirmed.',23:'Focused source/reference check: article v2 setup and Figure 10 p14 plus discussion p15 define binary configurations on an N-dimensional cube. The exam explicitly ignores energy selection. Graph search is mathematics; no spin-glass phase or quantum theory controls this task. KEEP confirmed.',24:'Focused given-model check of p10: density/reduced matrices and von Neumann entropy are defined; all requested properties reduce to normalized complex arrays, partial traces and singular-value/unitarity constraints. No operator time-evolution law is used. KEEP confirmed.'}
for n,detail in details.items():
 u=c.execute('select screening_unit_id from units where source_file_id=3116 and problem_number=?',(str(n),)).fetchone()[0]
 events.append(dict(screening_unit_id=u,detail=detail))
c.commit();p=w.ROOT/'reviews/resume_ortvay_2025_focused_qc_6.json';w.writejson(p,events);w.review(p)
print('Saved 17 KEEP, 2 BORDERLINE, 6 REJECT; suspicious/required cases reviewed.')
