"""Explicit source-grounded continuation judgements; not an automatic classifier."""
import json
import workflow as w
c=w.connect();I='I_force_motion';II='II_oscillations_waves';III='III_ideal_gas';IV='IV_thermodynamics';VI='VI_electric_field';VII='VII_magnetic_field';VIII='VIII_induction';X='X_wave_optics'
rows=[
(1,'KEEP',[I],'theory','Constrained rigid-body initial acceleration after cutting supports','The actual frame/rope geometry and uniform rod masses determine center of mass, inertia, force and torque constraints. Tensegrity terminology supplies context; no specialized structural theory is needed.'),
(2,'KEEP',[],'theory','Coupled rate equations under supplied attrition rates','Per-soldier removal rates and stopping rule define the differential model. Solving and varying the supplied rates is ordinary mathematical modelling, including the tactical interpretations.'),
(3,'BORDERLINE',[IV],'data_analysis','Solar-power fitting with a supplied temperature-efficiency model','Power time series, orientation and panel temperature response are given, but atmospheric absorption model and absolute panel calibration are not. It is unclear how unique absolute atmospheric fractions follow without additional radiative assumptions; no associated solution is available.'),
(4,'KEEP',[],'data_analysis','Gaussian measurement errors, tare bias and sensitivity analysis','Both absolute and relative error models are explicitly supplied. Summing weighing errors and comparing biased/tared totals requires uncertainty and probability, not consumer-law knowledge.'),
(5,'KEEP',[I],'theory','Rolling sphere on an accelerating translating plane','No-slip constraints, sphere inertia and translational Newtonian dynamics determine the graphite trace on the circularly translating racket.'),
(6,'KEEP',[I],'theory','Frictional impulse and transition from slipping to rolling','The given inertia, initial translation/rotation and Coulomb friction give linear/angular impulse and the final rolling constraint. No microscopic contact model is required.'),
(7,'KEEP',[I,II],'theory','Gravity inside a uniform rotating sphere and constrained tunnel motion','Newtonian spherical gravity, centrifugal/Coriolis acceleration and tunnel constraints determine timing and speeds. Rotation and geographic geometry are foundational mechanics.'),
(8,'KEEP',[I,II],'theory','Rolling eccentric hoop on an accelerating belt','Gravity, inertia, no-slip kinematics and energy in the accelerating belt frame determine the crossing threshold and maximal angular speed. Both internal parts remain together.'),
(9,'KEEP',[I],'theory','Comparison of explicitly supplied linear and quadratic drag laws','Newtonian equations for both given drag dependencies yield acceleration histories and terminal speed; equality at the stated time determines V. Turbulence is only a label.'),
(10,'KEEP',[I,VI],'theory','Rotating Coulomb three-body equilibrium and stability','Opposite charges circularly orbit under Coulomb attraction, with radiation expressly neglected. Force balance and linear perturbation stability determine collinear and other equilibria; Lagrange-point terminology adds no prerequisite.'),
(11,'KEEP',[I],'theory','Newtonian orbital integration under a given time-varying gravitational constant','The entire G(t) law is supplied. Integrating inverse-square Newtonian motion and plotting phase space form the dominant task. Slow-change comparison can be developed by orbit averaging; adiabatic-invariant terminology is a peripheral mathematical comparison.'),
(12,'KEEP',[I,VI,VII],'theory','Classical electron circular motion in supplied radial electric/magnetic fields','The monopole field analogy is stated and ordinary Lorentz/Newton forces determine conical circular motion, speed and period. Relativity is explicitly an optional gourmet bonus; completing classical part a earns maximal score, so it does not dominate the whole problem.'),
(13,'KEEP',[I],'numerical','Newtonian gravitational integration over a uniform rectangular planet','Uniform prism gravity, potential energy and constrained frictionless travel determine both numerical times and the orbital time unit. Flat-planet story does not require new gravity.'),
(14,'KEEP',[I],'theory','Contact, friction and collision modelling for a rolling locomotive wheel','The source expressly permits adequate simplifying assumptions. Newtonian contact forces, friction, impulses and rolling distinguish the enumerated behaviours; videos illustrate rather than supply an indispensable law or dataset.'),
(15,'KEEP',[],'theory','Constrained variational optimization under a completely specified cost functional','The cost integrand, endpoint conditions and nonnegativity constraints are all given. Global minimization and free-endpoint calculus are mathematical work; no economic theory is required.'),
(16,'REJECT',[I],'theory','Twist-to-writhe elastic-rod buckling','The critical twist depends centrally on unsupplied bending/torsional elastic energy and stability of a deformable rod. Rigid-body torque and the supplied tension/geometry do not define those constitutive relations.'),
(17,'KEEP',[I],'theory','Efflux energy, projectile geometry and vessel volume','Ordinary hydrostatic/kinetic energy balance gives the horizontal jet speed and emptying rate; shape and sideways retained volume follow by geometry. The actual mug drawing was inspected.'),
(18,'KEEP',[I,III],'theory','Capillary force balance with trapped ideal gas and a tapered tube','Surface-tension vertical force, hydrostatic pressure and the explicitly isothermal ideal-gas model determine all three cases. Jurin law can be derived from ordinary force balance; no continuum flow equation is needed.'),
(19,'REJECT',[II],'theory','Coupled internal and free-surface gravity-wave modes of stratified fluids','Density and layer thickness alone do not supply the dynamical wave model. Deriving two-layer sloshing eigenfrequencies centrally needs unsupplied continuum-fluid velocity/potential equations and interface boundary dynamics throughout the task.'),
(20,'BORDERLINE',[III,IV],'theory','Binary vapour-liquid equilibrium using supplied coexistence slopes','Clausius-Clapeyron slopes and latent heats are given, supporting much thermal work. However ideal liquid solution is named without a vapour-composition/Raoult or chemical-potential relation. That coupling controls coexistence pressure; intended model sufficiency is unclear without a solution.'),
(21,'KEEP',[I,IV],'theory','Mechanical energy balance and the entropy inequality','The definition of internal energy, momentum equation and external-power assumption are explicitly given. Differentiating kinetic energy and using positive T with nondecreasing entropy constrains dissipative power; no advanced nonequilibrium constitutive framework is needed.'),
(22,'KEEP',[X],'theory','Snell refraction in a spherical index gradient and ray reversal','The radial n(r) profile and exclusions are explicit. Thin-layer Snell refraction, turning-point geometry and reversible light paths determine escape and apparent magnification; atmospheric microphysics is unnecessary.'),
(23,'KEEP',[VI],'data_analysis','Reconstruction of an Ohmic network from effective resistance data','The full six-node resistance matrix was checked visually. Kirchhoff/Ohm linearity and matrix inversion determine conductance adjacency; inverse-network mathematics is not additional physics.'),
(24,'KEEP',[I,II,VII],'theory','Magnetic dipole potential and small-displacement stability','Biot-Savart field of the triangular wire and dipole energy give the Hessian, restoring force and oscillation period. The fixed perpendicular moment is explicit.'),
(25,'KEEP',[VII],'theory','Force on a prescribed permanent magnet next to a high-permeability plane','Uniform magnetization and large constant permeability supply the material model. Magnetostatic boundary conditions, equivalent surface currents/poles and field force determine attraction; no hysteresis or microscopic ferromagnetic theory is required.'),
(26,'KEEP',[I,VII,VIII],'theory','Mutual magnetic flux, Faraday braking and gravitational motion','Current drive, resistance and circular geometry define the experiment. Biot-Savart integration, induction and mechanical power yield exact and dipole-limit braking equations; special functions and asymptotics are mathematical difficulty.'),
(27,'KEEP',[VI,VII],'data_analysis','Symmetric resistor currents and Biot-Savart field mapping','The cube diagonal feed and equal edge conductors define the current circuit. Kirchhoff symmetry and field integration produce three spherical component maps; cosmic shielding is context and is not a separate plasma task.'),
(28,'REJECT',[],'theory','Relativistic scalar coupling and rapidity dynamics','Giving the action does not define proper-time kinematics, rapidity or relativistic variational dependencies. These unsupplied specialized concepts control the sole requested equation.'),
(29,'REJECT',[],'theory','Relativistic scalar-field free fall','The linear potential and earlier scalar action are supplied, but proper-time/coordinate-time transformation and scalar mass dynamics are not. Their distinction from Newtonian fall is the central work, not a peripheral extension.'),
(30,'REJECT',[],'theory','Relativistic rocket dynamics with proper-time fuel consumption','The exhaust speed and fuel fraction are given; relativistic momentum balance, rapidity, proper acceleration and elapsed-time conversion are not. They structurally control all travel and apparent-weight tasks.'),
(31,'BORDERLINE',[I,VII,VIII],'theory','Classical magnetic-field jump paired with quantum Landau-state measurement','Part a is ordinary Lorentz motion with Faraday impulse. Part b independently requires unsupplied Landau wavefunctions, overlap probabilities and quantum energy measurement. Both are substantial and neither is clearly peripheral; retain the whole problem as BORDERLINE.'),
(32,'REJECT',[],'theory','Entanglement entropy and SU(2) spin-state interpretation','Bell and triplet vectors are given, but reduced-state density matrices, von Neumann entropy and invariance under local versus global rotations are not. Those quantum-information concepts are the sole central question.'),
(33,'KEEP',[I,II],'theory','Retarded sound rays and caustics for supersonic circular motion','Constant sound propagation and circular kinematics explain multiple apparent sources, directional cusps and response to speed changes. Invisible cars/teleportation are explicitly the mistaken interpretation to explain, not required quantum physics.')]
pages=[1,1,2,2,3,3,3,3,4,4,4,5,5,6,6,6,7,7,7,8,8,8,9,9,9,9,10,10,11,11,12,12,13]
viewed={1,6,7,8,9,12}
units={int(u['problem_number']):u for u in c.execute('select * from units where source_file_id=3120')};assert len(units)==33
out=[]
for n,d,dom,fmt,physics,reason in rows:
    u=units[n];assert u['decision'] is None
    out.append(dict(screening_unit_id=u['screening_unit_id'],decision=d,confidence='medium' if d=='BORDERLINE' else 'high',primary_spho_domains=';'.join(dom),required_physics=physics,decision_reason=reason,external_physics_if_any=physics if d in ('BORDERLINE','REJECT') else ('Optional unsupplied relativity bonus, explicitly unnecessary for maximal score' if n==12 else ''),format=fmt,page_start=pages[n-1],page_end=pages[n-1],boundary_status='content_boundary_verified',visual_inspection_used=int(pages[n-1] in viewed),solution_used=0,evidence=f'Complete actual printed Ortvay 2023 Q{n}, physical p{pages[n-1]}, read from verified SHA-keyed cache; figures/matrices on pp1,6,7,8,9,12 inspected in full-page renders. All thirteen pages checked for Q1-Q33 and additional tasks. No associated solution file exists in this source inventory. Whole numbered problem retained with all internal subparts.'))
p=w.ROOT/'reviews/shutdown_ortvay_2023_33.json';w.writejson(p,out);w.decisions(p)
c.execute("update paper_boundary_audit set status='full_paper_boundaries_verified',observed_units=33,evidence=?,checked_at=? where file_id=3120",('All thirteen pages read: exactly Q1-Q33; bonus and lettered tasks remain internal. Final TeX marker is not a question. Registered numbers match printed inventory.',w.now()))
for n,note in {3:'Absolute atmospheric absorption inference is not uniquely calibrated by the supplied power/temperature data without an atmospheric law and panel scale; scope/model ambiguity retained as BORDERLINE.',12:'Relativity bonus is expressly unnecessary for maximal score. Whole source problem retained, including that optional section.',20:'Ideal solution is named without its mixture vapour-pressure relation; complete source has no attached worked solution.',26:'The idealized circuit omits a numerical self-inductance; future use should state/justify the quasistatic circuit limit or retain inductance symbolically.'}.items():
    c.execute('update units set source_quality_notes=? where screening_unit_id=?',(note,units[n]['screening_unit_id']))
c.commit()
print('Persisted 33 source-inspected Ortvay 2023 decisions and complete boundary audit.')
