import workflow as w
c=w.connect();I='I_force_motion';II='II_oscillations_waves';III='III_ideal_gas';IV='IV_thermodynamics';VI='VI_electric_field';VII='VII_magnetic_field';VIII='VIII_induction';IX='IX_em_oscillations_waves';X='X_wave_optics'
rows=[
(1,'KEEP',[I],'theory','Optimal residence time inside a radius on a parabolic Kepler orbit','The source explicitly excludes propulsion and all forces except solar gravity. Newtonian orbit integrals and one-parameter time optimization determine closest approach and residence time; SETI story adds no physics.'),
(2,'KEEP',[I,II],'theory','Mechanical response of a light bunk bed to occupant motion','A simple rigid/elastic support and coupled inertia model can compare displacement transfer using ordinary force, torque and oscillations. Bed stiffness, forcing and damping are not specified, so no universally unique recommendation is implied.'),
(3,'KEEP',[I,II],'experimental','Frequency comparison of upper and lower leg motion using a simple model','The task asks explanation/model and an observed frequency ratio. Body/limb inertia, elastic restoring and coupled oscillations suffice without an anatomical constitutive law; numerical ratio is model-dependent.'),
(4,'KEEP',[I],'theory','Rolling ball trajectories on an inclined rotating disk','The incline, rotation, no-slip condition and ball geometry were inspected. Newtonian translational/rotational equations and rotating constraints define all trajectories and special orbit cases.'),
(5,'KEEP',[I],'theory','Newtonian orbit and spin of a two-ended space sling','Equal docking masses, light rope, surface-speed and escape-speed targets define orbital/spin kinematics. Newtonian gravity, torque, tension and stability determine parameters and astronaut acceleration; no relativistic effect is asked.'),
(6,'KEEP',[I,II],'theory','Static-friction thresholds for nested cylinders on an eccentric axle','The coaxial hole and outer tangent axle were checked in the render. Rigid-body inertia, gravitational torque and normal/friction forces determine initial slip and no-slip throughout motion.'),
(7,'KEEP',[I,II],'theory','Slack elastic-thread oscillations under slow stiffness change','The unilateral linear spring law, initial extension and slow parameter variation are supplied. Piecewise Newtonian flights/spring motion and averaged work or action conservation derived from them determine period, transition and asymptotic energy.'),
(8,'KEEP',[I],'numerical','Classical meteor scattering by a frozen two-body gravitational field','The source specifies a fast classical particle beam and neglects orbital motion during passage. Newtonian trajectories and impact-parameter Jacobians give cross sections and caustic density; quoted interference means overlapping classical deflections, not an unsupplied quantum law.'),
(9,'KEEP',[I],'theory','Equations for a supplied direction-only classical Lagrangian','The degree-zero velocity dependence and central-coordinate case are explicit. Euler-Lagrange differentiation, Hessian/constraint analysis and conserved quantities are mathematical classical dynamics; no relativistic mass assumption is needed.'),
(10,'KEEP',[II],'theory','Variation and solution of an explicitly supplied nonlocal oscillator functional','Full memory integral, coefficients and exponential kernel are supplied. Direct variation of the prescribed action and solving its linear integral/differential equation are mathematics. Endpoint/future terms must be retained rather than silently replacing the action by a causal friction law.'),
(11,'KEEP',[I,II],'theory','Modes of a finite alternating-spring mass chain','All masses, spring constants and end attachments are specified. Newtonian coupled oscillations and matrix eigenvalues determine bulk and possible edge modes without a solid-state quantum model.'),
(12,'BORDERLINE',[II],'theory','Sound of a struck clamped steel rod with unspecified mode excitation','Rendered dimensions are l=20 cm, width 1 cm, thickness 0.4 cm, unlike corrupted extraction. Axial elastic sound can use ordinary Hooke/compression waves, while dominant transverse tone needs an unsupplied bending-beam model. Impact direction and intended mode are not specified, leaving a real prerequisite ambiguity.'),
(13,'KEEP',[III,IV],'theory','Stirling-cycle efficiency with specified regeneration imperfections','All cycle stages and three regenerator/heating models are supplied. Ideal-gas work/heat and first/second laws determine efficiency and work changes throughout the whole four-part task.'),
(14,'KEEP',[IV],'theory','Why unconstrained differentiation does not locate thermal equilibrium','Thermodynamic entropy variables and the proposed derivative argument are stated. Equilibrium maximization holds under energy/exchange constraints; ordinary entropy and temperature definitions resolve the paradox.'),
(15,'KEEP',[],'theory','First hitting probabilities for a supplied planar street random walk','All step probabilities, absorbing destinations and removed-edge variant are specified and the drawing was checked. Discrete harmonic probability/recurrence are mathematics, with no outside physics.'),
(16,'KEEP',[VI],'theory','Asymptotic force near an infinitely long grounded thin cylinder','Charge, radius, distance and conductor boundary are supplied. Conventional electrostatics and cylindrical boundary Green-function mathematics determine the leading force.'),
(17,'KEEP',[VII,VIII],'theory','Self and mutual inductances of geometrically linked toroidal coils','Both winding directions, perpendicular rings and cross-section notation were inspected in the diagram. Ampere field, flux linkage and magnetic-energy symmetry/positivity determine all inductance conditions.'),
(18,'KEEP',[VI,IX],'numerical','Comparing resistive and electromagnetic radiation loss in a power line','Given current, voltage and frequency define an ordinary circuit/radiation estimate. Maxwell radiation, line geometry and Ohmic resistance establish relevant length/geometry conditions; actual line material/dimensions are additional numerical source data, not a specialized physical theory.'),
(19,'KEEP',[X],'experimental','Mirror/interference identification of circular and linear polarizers','Allowed mirrors, beam splitters, source and sub-wavelength positioning are explicit. Ordinary polarization, reflection handedness and interference measurement determine possible identification and orientation limitations.'),
(20,'REJECT',[],'theory','Refractive-speed model fitted to an unsupplied GR lensing target','Classical ray propagation for c(Phi) is conventional, but the exact GR lensing law and even the weak-field target relation are not supplied. Deriving that comparison centrally needs unsupplied metric/geodesic physics; no unrelated lookup is used to make it contestant-supplied.'),
(21,'REJECT',[],'theory','Energy and momentum of a boosted Schwarzschild star plus gravitational field','Metric, relativistic energy-momentum transformation and definitions of total GR mass/field energy are not supplied. They are the sole substantive physical prerequisites.'),
(22,'REJECT',[],'experimental','Tomography of an unknown spin-one quantum state','The measurement design requires unsupplied quantum state-density, analyzer probabilities and spin-observable rules. Experimental format is eligible in principle, but its actual physics is specialized quantum measurement throughout.'),
(23,'REJECT',[],'theory','Electron spin states and coherent evolution in a rotating magnetic texture','The classical B field is supplied, but spin Hamiltonian/operators, eigenstate probability and unitary dynamics are not. Those central quantum prerequisites control all three parts.'),
(24,'BORDERLINE',[],'theory','Atomic radius ratio for dense GaAs packing without a specified lattice','Hard-sphere packing is geometry, but the GaAs crystal basis/coordination and fixed-structure constraints are not supplied. A freely optimized binary packing problem differs from the intended semiconductor-lattice geometry. Missing structural model leaves the actual prerequisite boundary unresolved.'),
(25,'BORDERLINE',[II],'theory','Band reconstruction from a supplied transfer-matrix trace alone','The intact trace function is given, providing substantial spectral mathematics. But determinant/propagated state definitions and Bloch phase or filling/conduction rules are not. Whether conservative wave-transfer assumptions sufficiently follow from the wording is uncertain; do not silently supply a specialized quantum band model.'),
(26,'REJECT',[],'numerical','Relativistic muon accelerator survival and radiation constraints','Work eE0L and decay context are supplied, but proper-time dilation, relativistic momentum/energy and synchrotron radiation scaling are not. They are central to survival fraction, maximum energy, storage radius and loss comparison.'),
(27,'KEEP',[I,VII],'data_analysis','Classical magnetic collimation and transformed momentum distributions','The explicitly nonrelativistic, slowly varying field regime and isotropic initial emission are supplied. Lorentz motion, flux continuity and gyro-averaged work derive magnetic-moment conservation and map the distributions; no plasma kinetic or quantum-spin theory is required.'),
(28,'KEEP',[IV,VII],'theory','Limits of a supplied classical star-graph spin probability model','The full graph energy, normalized Boltzmann weights, magnetization average and ordered limits are given. For conventional two-valued Ising variables, factoring finite sums and binomial concentration determines the limit; no quantum dynamics or unsupplied transition-temperature theorem is needed.'),
(29,'KEEP',[I,II,III],'numerical','Supersonic fall using an explicitly supplied drag and atmosphere graph','Mass, quadratic drag, coefficient/area, gravity and gas-density relation are supplied, including instruction to disregard the sound barrier. The original linked altitude/temperature/sound-speed chart was recovered and inspected in historical and corrected forms. Newtonian ODE integration and numerical data comparison determine all crossings and model limitations.')]
pages=[1,1,1,1,1,2,2,2,2,2,3,3,3,3,3,4,4,4,4,4,4,4,4,5,5,5,5,6,6]
u={int(r['problem_number']):r for r in c.execute('select * from units where source_file_id=3128')};assert len(u)==29
out=[]
for n,d,dom,fmt,physics,reason in rows:
 assert u[n]['decision'] is None
 out.append(dict(screening_unit_id=u[n]['screening_unit_id'],decision=d,confidence='medium' if d=='BORDERLINE' else 'high',primary_spho_domains=';'.join(dom),required_physics=physics,decision_reason=reason,external_physics_if_any=physics if d in ('BORDERLINE','REJECT') else '',format=fmt,page_start=pages[n-1],page_end=pages[n-1],visual_inspection_used=1,solution_used=0,boundary_status='content_boundary_verified',needs_second_review=n in (7,9,10,20,27,28,29),evidence=f'Complete actual Ortvay 2012 Q{n}, physical p{pages[n-1]}, read from valid SHA cache and all six full-page renders. Broken extraction loses letters/units/layout: rendered source is authoritative, including Q12 cm dimensions and Q25 trace formula. Q29 explicitly linked chart recovered, parsed and visually inspected; both source revisions and attribution preserved. Whole parent clauses kept; no acquired official worked solution.'))
p=w.ROOT/'reviews/shutdown_ortvay_2012_29.json';w.writejson(p,out);w.decisions(p)
c.execute("update paper_boundary_audit set status='full_paper_boundaries_verified',observed_units=29,evidence=?,checked_at=? where file_id=3128",('All six physical pages visually inspected because extraction drops letters and joins headings. Exactly Q1-Q29; all lettered parts belong to parents, no hidden task. Q29 chart is external and now preserved. No additional top-level MCQ/experiment.',w.now()))
notes={2:'Bed stiffness/damping/forcing geometry unspecified; no universal occupancy recommendation is uniquely fixed.',3:'Limb/body effective inertia and elastic-restoring model not numerically specified; simple-model comparison requested rather than exact anatomical frequency.',9:'Velocity dependence is homogeneous degree zero; mass-like Hessian may be singular and must not be treated as ordinary scalar mass without analysis.',10:'Given kinetic coefficient is 1/(2m), not m/2. Nonlocal action variation generally has both time orderings and depends on action endpoint; do not silently impose a causal-only equation.',12:'Rendered dimensions: length 20 cm, width 1 cm, thickness 0.4 cm. Extraction loses letter c. Strike direction and excited axial/transverse/torsional modes unspecified.',18:'No particular Hungarian line geometry, conductor resistance or circuit return layout is given. Existence estimate must declare such data/assumptions.',20:'Classical c(Phi) model supplied only qualitatively; target exact/weak-field GR deflection is not supplied.',24:'No hard-sphere crystal layout or coordination stated; naming GaAs does not define the needed geometry.',25:'Only trace of T given; determinant and Bloch mapping/filling assumptions are not operationally specified.',28:'Conventional Ising variable domain ±1 is named by model but not separately written; all energy/probability/average formulas are supplied. Model has no quantum operators.',29:'Source-linked chart revisions preserved. Commons history records a 2015 correction to temperature-axis labels; pre-2014 graph retained for historical fidelity and corrected current graph explicitly labelled. Fixed drag coefficient above sound is a stated approximation, not silently replaced.'}
for n,note in notes.items():c.execute('update units set source_quality_notes=? where screening_unit_id=?',(note,u[n]['screening_unit_id']))
c.commit();print('Saved 29 complete decisions and six-page boundary audit.')
