import workflow as w
c=w.connect()
rows=[
('raw::305',944,6,'I_force_motion;II_oscillations_waves','Beam and Roberval balance torque, linkage inertia, force identifiability and small oscillations','All geometry/inertia/CM shifts and rigid-link constraints are given. Newton force/torque, energy and linearization cover the entire A-C parent, including circuit-like force indeterminacy questions and floor reaction. A.4 and B.5 are internal response-format items, not independent MCQ parents.',0),
('raw::306',948,4,'X_wave_optics','Far-field diffraction with explicitly supplied phase-jump, Gaussian-charge and growing-layer models','Complex amplitude/intensity, single-electron scale, scattering vector, independent phase-jump law, Fourier identities, Gaussian thickness average and layer-coverage model are all supplied. Ordinary wave interference and probability/integrals do the meaningful work. Literal versus solution model conflicts in B/D are documented separately and require no outside physics.',1),
('raw::307',953,4,'I_force_motion;II_oscillations_waves;VII_magnetic_field','Forced-oscillator phase statistics and fully supplied classical magnetic-moment precession','Both complete oscillator and classical spin-torque differential equations, rotating-variable definitions, static rotation and ensemble initial means are printed. ODE integration, vector rotations and statistical averaging solve the whole problem. No quantum spin representation, density matrix or microscopic relaxation derivation is required.',1)]
out=[]
for uid,fid,np,dom,phy,reason,sol in rows:
 u=c.execute('select * from units where screening_unit_id=?',(uid,)).fetchone();assert u and u['decision'] is None and u['source_file_id']==fid
 out.append(dict(screening_unit_id=uid,decision='KEEP',confidence='high',primary_spho_domains=dom,required_physics=phy,decision_reason=reason,external_physics_if_any='',format='theory',page_start=1,page_end=np,visual_inspection_used=1,solution_used=sol,boundary_status='content_boundary_verified',needs_second_review=True,evidence=f'Full actual APhO 2026 theory problem, source file {fid}, all {np} pages read from SHA cache and rendered pages, including every statement/subpart/diagram/equation. One top-level problem per source; all internal A-C/A-E/A-B parts retained. Q2 official S2 pp3-10 read and pp7-9 rendered; Q3 official S3 all six text pages read and pp4/6 rendered for classical model/sign check.'))
p=w.ROOT/'reviews/shutdown_apho_2026_theory_3.json';w.writejson(p,out);w.decisions(p)
for uid,fid,np,dom,phy,reason,sol in rows:
 number=c.execute('select problem_number from units where screening_unit_id=?',(uid,)).fetchone()[0]
 c.execute("update paper_boundary_audit set status='full_paper_boundaries_verified',observed_units=1,evidence=?,checked_at=? where file_id=?",(f'All {np} physical pages read, official Q{number} source header and complete internal part sequence. One independently numbered theory problem, no omitted top-level task. Internal lettered/question response entries remain one parent.',w.now(),fid))
notes={
'raw::305':'All five balance drawings read. A-C models change CM/pan notation deliberately; linkage force identifiability is within Newton equations, not a missing elastic constitutive law. Seeded QC Random(2026100427) second selection Q1. No scale experiment performed.',
'raw::306':'SOURCE/SOLUTION CONFLICT: B field is written phi(t) globally, while S2 p5 clarifies transported source phase phi(t-si dot r/c), giving total incident+outgoing path delay. D explicitly extends A_N=(1-exp(i*q_z*N*d))/(1-exp(i*q_z*d)) to continuous Gaussian N; literal average diverges at q_z*d=2*pi for sigma=0.4. S2 pp7-9 instead removes integer-layer Bragg phase before continuous averaging and obtains finite ratio1, an additional model convention absent from the written continuous extension. Both originals preserved; conflict report has analytic evidence. KEEP is a scope judgment, not approval of the conflicting answer.',
'raw::307':'Explicitly classical torque/precession model, not quantum nuclear-spin dynamics. Printed positive gamma and S cross B with co-rotating Splus convention give omega0+omega2, not automatically the familiar difference. Official S3 pp3-6 confirms M=(-omega1,0,-omega0-omega2), Omega squared=(omega0+omega2)^2+omega1^2 and omega1*T1=pi/sqrt(2). Seeded QC Random(2026100427) first selection Q3.'}
for uid,note in notes.items():c.execute('update units set source_quality_notes=? where screening_unit_id=?',(note,uid))
c.commit()
w.writejson(w.ROOT/'reviews/shutdown_apho_2026_q2_statement_solution_conflicts.json',{'checked_at':w.now(),'screening_unit_id':'raw::306','statement_file_id':948,'solution_file_id':949,'statement_pages':[2,3,4],'solution_pages':[3,4,5,7,8,9],'inspection':'Full statement and cited solution sections read; statement all pages and solution pp7-9 actually rendered.','B':{'literal':'Ei(r,t)=A*exp(i*(ki dot r-omega*t+phi(t))) has globally simultaneous random phase. Retarded detector contributions sample phi at outgoing-delay-separated scattering times.','solution_clarification':'S2 p5 says phi should mean transported source phase phi(t-si dot r/c); then delay is full scattering path, (q dot r)/(k*c).','status':'Additional phase-transport convention recorded, not silently inserted into original PDF.'},'D':{'literal_mean_amplitude':'[1-exp(i*x*Nbar-sigma^2*x^2/2)]/[1-exp(i*x)], x=q_z*d','at_bragg':'For Nbar=5 and sigma=0.4, numerator at x=2*pi is 1-exp(-2*pi^2*0.16), nonzero; denominator vanishes. Flat sigma=0 reference tends to5, so literal intensity ratio diverges as x approaches2*pi.','solution':'S2 applies the Gaussian characteristic function to residual delta-q after using integer N to discard exp(i*2*pi*N); then ratio at Bragg equals1. That equality is not valid for the exact continuous A_N stipulated in Q2-4.','status':'Genuine continuous-versus-integer model conflict; no raw/solution repair performed.'},'scope':'All interpretations still use ordinary interference and supplied mathematical models. KEEP whole problem; source-quality conflict requires focused review and remains disclosed.'})
reviews=[
dict(screening_unit_id='raw::305',detail='Seeded QC Random(2026100427) second selection: full Q1 six-page A/B/C models and diagrams reread. Torque/stability, linkage energy/force equations, floor reaction and small-oscillation linearization are all ordinary Newton mechanics. Internal answer options do not create independent top-level questions. KEEP confirmed; no supplied-model ambiguity or unprovided central elastic law.'),
dict(screening_unit_id='raw::306',detail='Focused source/solution and supplied-model review: full Q2 and S2 B/D/E passages reread. All microscopic scattering amplitude and stochastic/Gaussian/layer laws are explicitly supplied, so remaining physics is ordinary waves. Analytically the literal continuous-thickness numerator is nonzero at q_z*d=2*pi for sigma=.4, whereas S2 first removes an integer Bragg phase then averages, yielding1. B also clarifies retarded phase transport beyond printed phi(t). Both conflicts documented with pages/formulas and raw sources preserved; no model silently repaired. Whole KEEP confirmed on scope, with explicit source-quality limitations.'),
dict(screening_unit_id='raw::307',detail='Focused supplied classical spin model and seeded QC Random(2026100427) first selection: all Q3 equations/rotations reread and S3 pp3-6 checked, with pp4/6 rendered. Differentiate Splus=e^(+i*omega2*t)*Sigmaplus to obtain M=(-omega1,0,-omega0-omega2); rotate that constant vector and average the linear ODE. Official key agrees with summed frequency and pi/sqrt2 condition. Full oscillator/random phase part also ordinary. KEEP confirmed; no Born, Pauli or microscopic relaxation law required.')]
required={r[0] for r in c.execute("select screening_unit_id from units where screening_unit_id in ('raw::305','raw::306','raw::307') and review_status='pass_1_complete'")};assert required<={r['screening_unit_id'] for r in reviews}
p=w.ROOT/'reviews/shutdown_apho_2026_theory_focused_seeded_3.json';w.writejson(p,reviews);w.review(p)
print('Saved three whole theory decisions, three paper audits, focused/QC records and explicit Q2 conflict evidence.')
