"""One-time content-grounded batch. Never replay after successful commit."""
import workflow as w
c=w.connect()
rows=[
('raw::318',988,7,'theory','I_force_motion;III_ideal_gas;VII_magnetic_field;VIII_induction','Hydrostatic ideal-gas atmosphere, orbital energy and particle momentum flux, explicitly supplied ion collection model, magnetic force and data tables','All A-F work uses ordinary hydrostatics, Newtonian orbits/drag, ideal gas and magnetic force. E explicitly supplies the collecting area, participation assumption and effective length; no plasma sheath, orbital-motion-limited collection or specialized ionosphere theory is required. F table headings/data are recovered from associated official solution p9.',1),
('raw::319',991,4,'theory','I_force_motion;VII_magnetic_field;II_oscillations_waves','Rolling constraint, angular momentum, charged-shell Lorentz torque, supplied planar ODE and conic/oscillator mathematics','Fixed and free turntable parts require Newton force/torque, no-slip kinematics and angular momentum. Charged-shell torque follows an integral of ordinary magnetic force. C3 supplies the complete second-order planar equation. The extra branch used by the C4 key is absent from the statement, causing underdetermination, not an external physics prerequisite.',1),
('raw::320',994,7,'theory','I_force_motion;III_ideal_gas;IV_thermodynamics;II_oscillations_waves','Radial incompressible-fluid energy and continuity, capillary pressure, ideal-gas compression, supplied Henry/Fick and heat-kernel diffusion model','The statement specifies an infinite incompressible inviscid fluid and all diffusion relations, including the transformed heat equation kernel. Radial kinetic energy plus pressure work closes B1 with elementary continuum geometry and Newtonian energy; no unsupplied viscous/stratified fluid constitutive theory is necessary. A-C meaningful work is capillarity, ideal gas, oscillation and supplied diffusion mathematics.',1),
('raw::321',996,10,'experimental','I_force_motion;II_oscillations_waves','Pendulum energy, collision impulse/reduced mass, period and contact-time fitting, explicitly supplied contact deformation and pressure model','The complete A-E experiment supplies the pressure profile, displacement kernel and analytical displacement expression, effective modulus and material constants. Central work measures and fits pendulum/contact timing and compares collisions; E can use the supplied contact model with force/geometry/energy. No independent elastic half-space law must be known. Internal model and key averaging inconsistencies are documented separately.',1),
('raw::322',1001,6,'experimental','X_wave_optics;VI_electric_field;I_force_motion','Laser electrical-power calibration, interference rings/angles, empirical deformation and reversible-power threshold','All A-D tasks are apparatus operation, plotting and empirical power/fringe measurements. Height versus ring count is explicitly supplied as m=2h/lambda. No thermoplastic constitutive law, semiconductor laser emission model or material yield calculation is requested; the yield terminology is an empirical label.',0)]
for uid,fid,*rest in rows:
 u=c.execute('select * from units where screening_unit_id=?',(uid,)).fetchone()
 assert u and u['decision'] is None and u['source_file_id']==fid,(uid,'already committed or unexpected source')
f=c.execute('select * from source_files where id=987').fetchone()
assert w.digest(w.RAW/f['local_path'])==f['sha256']
doc=c.execute('select * from source_documents where id=1045').fetchone()
assert doc['file_id']==987 and str(doc['year'])=='2023'
out=[]
for uid,fid,np,fmt,dom,phy,reason,sol in rows:
 out.append(dict(screening_unit_id=uid,decision='KEEP',confidence='high',primary_spho_domains=dom,required_physics=phy,decision_reason=reason,external_physics_if_any='',format=fmt,page_start=1,page_end=np,visual_inspection_used=1,solution_used=sol,boundary_status='content_boundary_verified',needs_second_review=True,evidence=f'APhO 2023 file {fid}: all {np} pages read in full SHA-cached text and all rendered statement pages actually inspected; one top-level numbered theory/experiment, all internal A-F/A-E/A-D retained. Focused key images: 989 pp7/9; 992 pp12-14; 995 pp1-3/6-8; 997 pp13-15. Shared experiment instructions 987 all eight pages read and rendered. See focused source-quality records.'))
p=w.ROOT/'reviews/shutdown_apho_2023_5.json';w.writejson(p,out);w.decisions(p)
notes={
'raw::318':'Statement ion density is 1e12 m^-3; official solution pp7/9 uses 1e13 and explicitly notes tenfold rescaling for 1e12. Final relative drag ranking therefore depends on the chosen density; do not silently apply the key values to the statement. F refers to answer-sheet tables not linked in the checked acquisition source index; complete table headings/heights are retained in official solution 989 p9. Collection model is explicitly approximate, not an asserted general plasma law.',
'raw::319':'Rendered statement p1 cross-product z component has AxBx where AxBy is required. C4 initial conditions do not uniquely fix both gamma and beta: the key 992 p13 additionally chooses beta-prime=0. Key p12 beta definition omits the Omega factor present in its preceding force equation. C5 explicitly changes moment of inertia to 1/11, while key appears to carry an earlier alpha=1/11 from I=.1; preserve the local statement override and do not silently equate I with alpha.',
'raw::320':'Rendered Q3 p6 B5 prints R0=0.1 m, whereas cached extraction reads 0.1 mm: trust the rendered original and flag discrepancy. A1 key collapse time about .1 s conflicts with supplied 1 mm scale (about 1e-4 s). A2 supplied p_inf=101000, p_v=2340, sigma=.0728, R0=1e-5 gives q0=113220 Pa, not key approx170 kPa. B3 literal initial p=1600 gives q0=13820 Pa, not key approx10 Pa; rebound numerical answer is consequently unreliable. C1 q=170 kPa at 10 micrometres is inconsistent with quasistatic ambient/Laplace equilibrium under the same parameters. Physics scope remains closed by explicit assumptions; no original repaired.',
'raw::321':'Statement equations (1) and (3) have inconsistent contact-kernel normalization. At r=0, integral p(s)/s dA = pi^2*p0*a/2; printed Eq1 coefficient 2*pi/E-prime gives pi^3*p0*a/E-prime, while Eq3 gives pi*p0*a/(2*E-prime), a factor 2*pi^2 difference. Key 997 pp14-15 equates impulse time-average force with the work-average force in K=F_av*delta without an exact justification, and uses approximate peak/average relations. These are source model/approximation problems, not absent contestant physics. No experimental measurements performed.',
'raw::322':'Yield-strength wording denotes an experimentally inferred reversible-power threshold, not a requested stress/strain constitutive calculation. No laboratory data generated by screening; all graphs and sample observations belong to source material.'}
for uid,fid,np,fmt,*rest in rows:
 c.execute("update paper_boundary_audit set status='full_paper_boundaries_verified',observed_units=1,evidence=?,checked_at=? where file_id=?",(f'All {np} pages physically inspected from heading through final task. One independently headed {fmt} parent; every internal letter/number remains its subpart. No omitted top-level task.',w.now(),fid))
 c.execute('update units set source_quality_notes=? where screening_unit_id=?',(notes[uid],uid))
for uid in ['raw::321','raw::322']:
 c.execute('insert or ignore into unit_files(screening_unit_id,file_id,document_id,role) values (?,?,?,?)',(uid,987,1045,'instructions'))
ledger=c.execute('select * from paper_boundary_audit where file_id=987').fetchall()
assert not ledger,'Unexpected instruction ledger entry requires separate audit; do not mark automatically'
c.commit()
w.writejson(w.ROOT/'reviews/shutdown_apho_2023_common_instructions.json',dict(checked_at=w.now(),file_id=987,document_id=1045,sha256=f['sha256'],source_url=doc['direct_url'],associated_units=['raw::321','raw::322'],inspection='All eight pages text and images inspected. Generic safety/setup, laser and oscilloscope calibration/operation only, no independently graded top-level task. Timing instructions specify later pulses to avoid first-impact artifacts. Existing raw source preserved, not reacquired.'))
w.writejson(w.ROOT/'reviews/shutdown_apho_2023_Q1_answer_sheet_availability.json',dict(checked_at=w.now(),source_url='https://olimpicos.net/apho/index.html#2023',resolved_url='https://olimpicos.net/apho/',finding='Checked 2023 source section lists experiment instructions, three theory statements/solutions/mark schemes, two experiments/solutions. No separate blank answer-sheet link in this section. This is an index availability finding, not a claim of worldwide nonexistence.',preserved_table_source_file_id=989,pages=[9],heights_km=[350,375,400,410]))
reviews=[
dict(screening_unit_id='raw::318',detail='Focused supplied collection model/key conflict and theory seeded QC Random(2026100431) selects raw::318. Entire A-F inspected. E specifies area S, all ions/electrons participation and effective length sqrt(S), giving ordinary I=enSv and Ampere force, without sheath law. Official key 989 p9 retains F tables and explicitly documents 1e13 versus 1e12 tenfold density scaling. Ranking/value conflict recorded, not repaired. Whole KEEP confirmed.'),
dict(screening_unit_id='raw::319',detail='Focused official-key conflict review using rendered 992 pp12-14 and statement all four pages. Newton and Lorentz torque close central work. C3 is a supplied constant-coefficient ODE. Complex w=exp(-i*gamma*t/2)*z removes its derivative with beta+gamma^2/4; no advanced mechanics needed. A fixed-angle scalar branch has initial angle rate -1, hence gamma=2, but beta remains free unless the key extra beta-prime=0 is imposed. Official statement does not supply that constraint. Mathematical underdetermination and sign/I/alpha errors recorded separately. Whole KEEP confirmed.'),
dict(screening_unit_id='raw::320',detail='Focused fluid prerequisite/supplied-model review: all seven statement pages and all eight key pages read, key renders1-3/6-8. Continuity v(s)=R^2*Rdot/s^2 gives kinetic energy K=2*pi*rho*R^3*Rdot^2; dK/dt=4*pi*R^2*(p-p_inf-2*sigma/R)*Rdot yields R*Rddot+1.5*Rdot^2=(p-p_inf-2*sigma/R)/rho. Ideal-gas compression closes p. Thus B1 does not require an unsupplied Navier-Stokes law; distinguishes explicitly idealized radial problem from prior unsupplied viscous/stratified-mode cases. Henry and Fick relations and heat kernel are provided for C; transformations/integration are mathematics. Numeric/radius inconsistencies recorded. Whole KEEP confirmed without changing rubric.'),
dict(screening_unit_id='raw::321',detail='Focused Hertz supplied-model/source consistency check: all ten statement pages and eight shared instructions pages inspected; key E pp13-15 rendered. Contact pressure and analytical displacement are explicitly given, effective modulus/material constants defined. Ordinary geometry plus force integration supplies deformation/force dependence; solving collision ODE or energy integral needs no outside elasticity theory. Kernel normalization mismatch and key time-average versus work-average force are documented with actual equations. Central A-D measurement/fitting and collision mechanics remain within scope. Whole KEEP confirmed; no experiment performed.'),
dict(screening_unit_id='raw::322',detail='Experimental-format seeded QC Random(2026100432) selects raw::322. All six pages and shared laser/scope instructions inspected. A-D use power calibration, empirical reversible heating, ring count/diameter/angles and explicit m=2h/lambda. Neither thermal-elastic constitutive theory nor microscopic laser physics is required. Complete experimental parent KEEP; no measured data fabricated.')]
p=w.ROOT/'reviews/shutdown_apho_2023_focused_seeded_5.json';w.writejson(p,reviews);w.review(p)
print('Saved five APhO 2023 parent decisions, five paper audits, shared instruction provenance and five focused/QC reviews.')
