import workflow as w
c=w.connect();I='I_force_motion';II='II_oscillations_waves';III='III_ideal_gas';IV='IV_thermodynamics';VI='VI_electric_field';VII='VII_magnetic_field';VIII='VIII_induction';IX='IX_em_oscillations_waves';X='X_wave_optics'
rows=[
(1,'KEEP',[],'theory','Last-visited position in a prescribed symmetric random walk','Neighbour probabilities, restart and stopping criterion are explicit. Finite-state probability and combinatorics determine seat probabilities without a new physical law.'),
(2,'KEEP',[I],'experimental','Household measurement of mechanical bicycle power','The whole task asks actual reproducible measurements, accounting for gravity, air and mechanical losses. Force, work, speed and power plus calibration/uncertainty suffice; no unsupplied aerodynamic theory is prescribed.'),
(3,'KEEP',[I],'theory','Repeated elastic slope impacts and projectile focal geometry','Moon gravity, elastic reflection and slope geometry define ballistic flights. Newtonian impulses and conic geometry determine directrices and the focal locus.'),
(4,'KEEP',[I,II],'theory','Small rolling oscillations of a joined pair of semicircular disks','The rod geometry and half-disk orientations were checked in the drawing. Rigid-body inertia, gravity, rolling constraints and small-oscillation energy determine the frequency.'),
(5,'KEEP',[I],'theory','Libration viewed from alternative points in a Kepler ellipse','Uniform spin and nonuniform Kepler orbit are explicit. Newtonian orbital timing and angular geometry determine the minimum apparent libration; no relativistic model is needed.'),
(6,'KEEP',[I],'theory','Solstice versus extremal sunrise offsets','Orbital nonuniformity, obliquity and rotating-Earth solar geometry explain equation-of-time offsets and possible planetary cases. Numerical location/time calculation is ordinary mathematics.'),
(7,'BORDERLINE',[I,X],'theory','Dust-tail orbits and brightness with an incompletely specified grain model','Ordinary gravity and radiation force can determine trajectories once optical grain properties and launch conditions are chosen. But time-dependent total brightness and angular absorption centrally need unspecified grain size/distribution, evaporation/injection and optical response. Intended general-physics approximation versus specialized dust/extinction modelling is unresolved.'),
(8,'KEEP',[I,II],'theory','Isochronous motion under an explicitly supplied inverse-cube plus linear force','The exact force and positive coefficients supply the complete dynamics. Potential integration, stability and period integrals explain energy-independent frequency through Newtonian mechanics and mathematics.'),
(9,'KEEP',[I],'theory','Bridge-cable equilibrium and the correct load-constrained variational functional','Horizontally uniform vertical loading and negligible cable mass are explicit. Local force balance, potential-energy accounting and constrained calculus distinguish the two stationary shapes.'),
(10,'REJECT',[],'theory','Mapped airfoil stagnation points under a finite-velocity trailing-edge condition','A conformal map alone does not supply the potential-flow/circulation model, complex velocity field or Kutta condition selecting circulation. These specialized hydrodynamic prerequisites are central to every stagnation-point result.'),
(11,'KEEP',[I],'numerical','Stationary soap-film surfaces and second-variation stability','Surface-of-revolution area and ordinary surface-energy minimization define the physical model. Calculus of variations, numerical eigenvalues and bifurcation landscape are mathematics; no unsupplied material constitutive theory is necessary.'),
(12,'KEEP',[X],'theory','Finite-aperture lens view of a cylindrical cork','All object, eye and lens distances and diameters are supplied. Geometrical imaging and aperture visibility determine the scaled drawing. This lens diameter differs from other years and does not establish an alias.'),
(13,'KEEP',[X],'theory','Wave-optical perfect imaging versus aplanatic sphere rays','The two apparently conflicting claims are described. Optical paths, wavelength in glass, finite aperture and geometrical versus wave imaging explain their distinct limitations through ordinary optics.'),
(14,'KEEP',[I,II,VI,IX],'theory','Dielectric dipole trapping and radiation force in a specified optical field','The small homogeneous dielectric sphere, dielectric constant, wave regime and parabolic intensity profile are supplied. Electrostatic polarizability, Maxwell radiation and force/energy averaging determine equilibrium and transverse oscillations within the explicit electromagnetic-radiation scope.'),
(15,'KEEP',[VI],'theory','Resistance of an infinite finite-width resistor strip','The exact network is specified. Kirchhoff and Ohm laws plus discrete Green functions/transform sums determine arbitrary-contact and N=5 resistances; mathematical complexity adds no outside physics.'),
(16,'KEEP',[VI],'theory','Charged conducting wire between grounded parallel plates','Wire charge, long-wire limit and grounded boundaries are supplied. Conventional electrostatic images and force determine displacement dependence.'),
(17,'KEEP',[VI],'theory','Surface current lines and voltage ratios on a conducting globe','Uniform graphite conductivity and specified current contacts define an Ohmic boundary problem. Surface potential, conservation and geographical coordinate geometry give current lines and the voltage ratio.'),
(18,'KEEP',[VI],'theory','Grounded toroidal cavity electrostatic Green function','The full coloured circle/tori drawing was inspected. The reactor is explicitly inactive: only a static charge and ideal grounded walls are required. Coulomb potential and boundary mathematics determine the solution.'),
(19,'KEEP',[VI],'theory','Anisotropic Ohmic resistance with full-face electrodes','The conductivity/resistivity tensor model and electrode boundaries are explicit. Linear Ohm law, continuity and boundary PDE mathematics yield resistance or limiting approximations.'),
(20,'REJECT',[],'theory','Magnetically loaded clamped copper beam deflection','Ordinary magnetic force can be computed, but the central distributed deflection requires an unsupplied bending moment-curvature/beam equation and its section-dependent stiffness. Permission to look up material constants does not supply that specialized elastic model.'),
(21,'BORDERLINE',[I,VII,VIII],'theory','Magnet fall and stability in an unspecified ferromagnetic pipe','Gravity and eddy induction are ordinary scope. Strong neodymium plus steel may additionally require nonlinear/hysteretic magnetization and a finite-geometry response law, none specified. A simple linear conducting-pipe approximation versus essential ferro-response remains ambiguous.'),
(22,'KEEP',[I,II,VII],'theory','Waves of classical magnetic compass rotors on a supplied lattice','Ideal dipoles, nearest-neighbour interactions, moments, inertias and alignment field are explicitly specified and the lattice drawing was checked. Magnetic torques and Newtonian coupled small rotations give the dispersion matrix; no quantum-spin theory is needed.'),
(23,'KEEP',[I,III,IV],'theory','Dissipative piston oscillations between insulated ideal gases','The full initial gas data and constant kinetic/static friction rule are supplied. Newtonian piston motion, ideal-gas adiabatic work and frictional energy accounting give stopping travel and small-mass limits. Frictional heat allocation needs an explicit ordinary modelling convention, recorded as a source limitation.'),
(24,'REJECT',[],'theory','Rest mass of a mediator in a relativistic velocity exchange','The masses/velocities are constrained but four-momentum and invariant-mass relations are not supplied. Unsupplied special-relativistic kinematics structurally controls the whole result.'),
(25,'REJECT',[],'theory','Exact radial throwing in Schwarzschild coordinates','Neither metric nor geodesic/time normalization equations are supplied. Exact GR dynamics is the central request, beyond the Newtonian comparison substep.'),
(26,'REJECT',[],'theory','Relative local motion of two black-hole infallers','Schwarzschild geodesics, local tetrad/inertial-frame construction and horizon observation rules are not given. They dominate the complete mutual-observer task.'),
(27,'REJECT',[],'theory','Causality and geometry of a cosmological swiss-cheese solution','The named FRW/Einstein model is not operationally supplied through metric, matching or geodesic equations. Those GR prerequisites are central to all three assertions.'),
(28,'REJECT',[],'theory','Quantum singular oscillator spectrum and dimensional generalization','Only the potential is supplied. Schrodinger dynamics, quantum domains, eigenfunction interpretation and spectral rules are unsupplied and control the meaningful work.'),
(29,'KEEP',[],'theory','States of a hyperbolically transformed explicitly defined operator pair','The commutator, adjoint, number operator, eigenbasis and hyperbolic linear transformation are explicitly given. Operator algebra, positive quadratic forms and normalized series solve the requested first states. Formal Lorentz language adds no spacetime dynamics; optional coherent-state extension does not dominate.'),
(30,'KEEP',[],'numerical','Nonzero-entry growth of binary-occupation transition matrices','The binary occupation basis, creation/deletion single-particle form and logarithmic nonzero-count definition are supplied. Counting possible occupied-to-empty moves and generic diagonal terms determines sparsity asymptotics; phase/fermionic sign conventions do not alter generic nonzero counts. No quantum evolution or measurement law is used.'),
(31,'REJECT',[],'theory','Classical and quantum scalar-field diagrammatic perturbation','Lagrangian coefficients alone do not supply covariant field dynamics and, centrally, quantum propagator/diagram/contraction rules needed for the requested quantum-to-classical comparison. That substantial unsupplied QFT machinery prevents keeping the whole task.'),
(32,'BORDERLINE',[],'theory','Quotient configuration topology and partially supplied quantum boundary model','Permutation action, quotient construction, half-plane Hamiltonian and Robin boundary expression support substantial pure mathematics. Physical self-adjointness/probability requirements, free quantum propagation and boson/fermion interpretation are not operationally supplied. The mathematical and unsupplied quantum dependencies are near the whole-problem boundary.'),
(33,'KEEP',[],'theory','Profit optimization under fully specified toy trading rules','Participant valuation distribution, purchase allocation and both banks profit rules are explicit. Integrating and optimizing these prescribed functions is mathematics, with no real-market prerequisite.'),
(35,'KEEP',[II,X],'data_analysis','Galactic velocity inference from official survey coordinates and redshifts','The source specifies DR7, SQL extraction, galactic coordinates, Doppler interpretation, angular averaging and error filtering. Ordinary Doppler motion, line-of-sight geometry, fitting and data validation determine the requested velocity. The official DR7 endpoint was verified and its stated example preserved; no cosmological dynamics is required.')]
pages={**{n:1 for n in range(1,6)},**{n:2 for n in range(6,14)},**{n:3 for n in range(14,19)},**{n:4 for n in range(19,26)},**{n:5 for n in range(26,32)},32:6,33:6,34:7,35:7}
u={int(r['problem_number']):r for r in c.execute('select * from units where source_file_id=3126')};assert len(u)==35 and len(rows)==34
out=[]
for n,d,dom,fmt,physics,reason in rows:
 assert u[n]['decision'] is None
 out.append(dict(screening_unit_id=u[n]['screening_unit_id'],decision=d,confidence='medium' if d=='BORDERLINE' else 'high',primary_spho_domains=';'.join(dom),required_physics=physics,decision_reason=reason,external_physics_if_any=physics if d in ('BORDERLINE','REJECT') else '',format=fmt,page_start=pages[n],page_end=pages[n],visual_inspection_used=1,solution_used=0,boundary_status='content_boundary_verified',needs_second_review=n in (14,20,23,29,30,35),evidence=f'Complete actual Ortvay 2014 Q{n}, physical p{pages[n]}, inspected from valid SHA cache and full render. All seven physical pages inspected for boundaries and diagrams. No worked official solution linked by original year directory; official organizer availability review retained. Q34 essential linked image missing; Q35 original DR7 query/data access verified.'))
p=w.ROOT/'reviews/shutdown_ortvay_2014_34.json';w.writejson(p,out);w.decisions(p)
missing='Q34 physical p7 contains only a link to an essential satellite image, not the image. Original HTTP/HTTPS sandstorm.ps both return 404; original year directory has no abrak folder; exact source archive lookup returned 503. Actual image unavailable; no scope decision guessed. See reviews/shutdown_ortvay_2014_external_availability.json.'
c.execute("update units set review_status='unresolved_source_unavailable',page_start=7,page_end=7,boundary_status='content_boundary_verified',evidence=?,source_quality_notes=? where screening_unit_id=? and decision is null",(missing,missing,u[34]['screening_unit_id']))
c.execute("update paper_boundary_audit set status='full_paper_boundaries_verified',observed_units=35,evidence=?,checked_at=? where file_id=3126",('All seven physical pages and rendered diagrams inspected: exactly Q1-Q35, with each lettered/paragraph continuation under its parent number. Q34 essential linked image absent, explicitly accounted as source unavailable. Q35 full SQL help belongs to the same task. No omitted task.',w.now()))
notes={6:'First paragraph solstice/sunset wording is internally inconsistent with the conventional earliest/latest dates; retain original wording and later explicit winter/latest-sunrise comparison.',7:'Grain radii, optical response, source rate/distribution, launch conditions and viewing geometry are not operationally specified.',12:'Similar cork problems occur in other years, but the stated lens diameter here is 3 cm; no logical equivalence established.',14:'Dielectric sphere regime and intensity are given, but Maxwell dipole-radiation force must be derived. EM radiation is explicitly within the operational scope; not rejected merely as optical tweezers.',20:'Tables supply constants, not the missing beam moment-curvature law.',21:'Strong ferromagnetic pipe response, geometry and material constitutive law are not specified.',23:'Tube/piston are heat insulating; where frictional heat is deposited is unspecified. Adiabatic gas equations with frictional heat stored outside gas are a declared conventional model, not a unique source-prescribed result.',29:'Optional coherent-state request does not define coherent states; compulsory three-state task supplies complete commutator and quadratic operators.',30:'Thermodynamic limit n<N does not specify whether n is fixed or proportional to N; state asymptotics accordingly. Generic coefficients avoid cancellations; vacuum diagonal is zero.',32:'Given Hamiltonian/boundary forms alone do not supply time evolution or the physical self-adjointness/probability-current criterion.',35:'Original portal has aged; official DR7 endpoint verified directly. Saved TOP 100 original example is illustrative and unordered, not full exercise data. A larger chosen DR7 sample and selection/error assessment remain necessary.'}
for n,note in notes.items():c.execute('update units set source_quality_notes=? where screening_unit_id=?',(note,u[n]['screening_unit_id']))
c.commit();print('Saved 34 whole-problem decisions, one explicit missing-image residual, full 35-task boundary audit.')
