"""One-time source-grounded completed inspection; never replay this batch."""
import random
import workflow as w
c=w.connect()
rows=[
('raw::338',1073,6,'theory','VI_electric_field;II_oscillations_waves;IX_em_oscillations_waves;XI_quantum_light','Induced-dipole work, supplied damped-oscillator and Larmor models, photon energy, Gaussian trap depth and harmonic curvature; terminal uncertainty estimates','The dominant optical-dipole/trap work is ordinary electrostatics, driven oscillation, energy balance and calculus with the full damping/radiation and beam models supplied. Final sections9-10 do assume quantitative position-momentum uncertainty, which is named but not given as a relation. They form a subordinate terminal extension and do not control earlier meaningful optical trapping work. No BEC state theory, Born rule or interacting-condensate equation is required. Whole semantic-majority KEEP; all internal sections retained.',1,True),
('raw::339',1079,5,'theory','I_force_motion;VI_electric_field','Newtonian orbital and rotating-frame balance, axial tension/stress differential equation, supplied Morse bond potential and lattice geometry','All four sections use inverse-square gravity, centrifugal balance, ordinary tensile force per area and Taylor expansion of the explicitly given interatomic potential. The linear network/bond geometry is supplied; no tensor constitutive law or specialized continuum elasticity must be known. Mathematical optimization and an unfamiliar space-elevator context do not change the whole-problem eligibility.',0,False),
('raw::340',1077,7,'theory','IV_thermodynamics;VI_electric_field','Supplied Seebeck/Peltier/Fourier laws, reversible Carnot efficiency, Joule heating, energy balance and generator/refrigerator optimization','The statement defines thermoelectric emf and Peltier heat, supplies Fourier conduction and independently states pi=alpha*T after asking for an ideal reversible derivation. That derivation follows ordinary Carnot efficiency; no Onsager transport theory is required. Remaining generator/cooler work is energy conservation, circuits and optimization with material data supplied. Whole KEEP.',1,True),
('raw::341',1081,13,'experimental','VII_magnetic_field;VI_electric_field','Coil field and Earth-field projection, supplied two-resistor GMR model, Wheatstone bridge, measurement/calibration, empirical flux-concentrator fit and electric power','Microscopic spin scattering is explanatory context: the complete series/parallel resistor model is provided. Graded work uses measured resistances/voltages, circuit algebra, plots, field projections and P=UI. Flux enhancement is an explicitly supplied empirical relation to be fitted. No unsupplied quantum or microscopic magnetoresistance theory is needed. All A-D tasks and apparatus appendix form one independently graded 20-point experiment.',1,True)]
for uid,fid,*rest in rows:
 u=c.execute('select * from units where screening_unit_id=?',(uid,)).fetchone()
 assert u['decision'] is None and u['source_file_id']==fid
out=[]
for uid,fid,np,fmt,dom,phys,reason,sol,focus in rows:
 out.append(dict(screening_unit_id=uid,decision='KEEP',confidence='high',primary_spho_domains=dom,required_physics=phys,decision_reason=reason,external_physics_if_any='Final9-10 assume quantitative position-momentum uncertainty rather than supplying it; subordinate terminal extension to dominant classical trap work' if uid=='raw::338' else '',format=fmt,page_start=1,page_end=np,visual_inspection_used=1,solution_used=sol,boundary_status='content_boundary_verified',needs_second_review=focus,evidence=f'Original APhO2018 file{fid}: all{np} actual statement pages read in SHA cache and all rendered pages viewed, including diagrams and experiment appendix. Truncated1073p3 extraction reread in full; interrupted/truncated1081pp9-12 image output reopened successfully before decision. Official1075pp3-4 text/images confirms terminal uncertainty estimates;1078pp2-3 text and p2 image confirms Carnot method;1080pp1-7 text and pp4/6 images confirms resistor inversion and bridge calibration. No experimental data generated or experiment claimed.'))
p=w.ROOT/'reviews/shutdown_apho_2018_4.json';w.writejson(p,out);w.decisions(p)
for uid,fid,np,fmt,*rest in rows:
 c.execute("update paper_boundary_audit set status='full_paper_boundaries_verified',observed_units=1,evidence=?,checked_at=? where file_id=?",(f'All{np} physical pages inspected. One top-level {fmt} parent; internally numbered/lettered tasks retained. No omitted independent task. Experiment printed Q1/A-D totals20points despite acquisition labelQ4, with multimeter/battery/pin appendix included.',w.now(),fid))
c.execute('update units set source_quality_notes=? where screening_unit_id=?',('Rendered original1073p6 specifies z0/rho0 and zL/rhoL; extraction fraction order can be reversed. Original page and key1075p4 used. Quantitative uncertainty relation not silently treated as supplied.','raw::338'))
c.execute('update units set source_quality_notes=? where screening_unit_id=?',('Rendered original1081p7 B10 gamma=r/R and p8 C3 slope=DeltaS/DeltaB supersede reversed extracted fraction order. Official1080p4 confirms r/R; p6 C7 rendered equation uses absolute signal and slope. No fixed external data required: contestant measurements and complete apparatus appendix are integral.','raw::341'))
c.commit()
assert random.Random(2026100439).sample(['raw::338','raw::339','raw::340'],1)==['raw::340']
reviews=[
dict(screening_unit_id='raw::338',detail='Focused supplied-model/whole-problem review. Actual full six-page statement and official1075pp3/4 images confirm quantitative p~hbar/z is assumed, not supplied. This is confined to final9-10 and cannot be called a fully supplied quantum problem. Classical dipole work, explicit driven-oscillator/radiation equations, photon energy and Gaussian potential/harmonic-curvature analysis carry the dominant conceptual work and do not depend on the final quantum relation. Whole KEEP under the unchanged semantic-majority rule, with external terminal prerequisite disclosed; no subpart extraction.'),
dict(screening_unit_id='raw::340',detail='Theory QC seed2026100439 selects340 and focused specialized transport check. All seven actual pages supply Seebeck/Peltier/Fourier laws and subsequent pi=alpha*T. Official1078p2 image derives the ideal relation solely through Carnot efficiency with noninteracting electron gas and negligible electrical resistance; no microscopic electron thermodynamics or Onsager machinery needed. Generator/refrigerator calculations are ordinary conduction/Joule/circuit energy balances. Whole KEEP confirmed.'),
dict(screening_unit_id='raw::341',detail='Experiment QC seed2026100440 over singleton341 and focused microscopic model check. All thirteen actual statement images include equivalent resistor diagram, Wheatstone pins, coil/apparatus figures, flux relation and full appendix. Official1080pp1-7 text with pp4/6 images uses ordinary resistor inversion and bridge signal calibration. The question never asks for a scattering rate, quantum state or microscopic GMR law. Internal A-D and D1-3 applications are parts of ONE20-point experiment, not multiple top-level problems. KEEP confirmed.')]
p=w.ROOT/'reviews/shutdown_apho_2018_focused_seeded_3.json';w.writejson(p,reviews);w.review(p)
print('Saved four KEEP decisions, four physical-boundary audits and three focused/QC reviews.')
