import workflow as w
c=w.connect();I='I_force_motion';II='II_oscillations_waves';III='III_ideal_gas';IV='IV_thermodynamics';VI='VI_electric_field';VII='VII_magnetic_field';X='X_wave_optics'
rows=[
(1,'KEEP',[X],'theory','Distinguishing curved Earth and finite-height Sun by angular observations','Ray geometry on a plane and sphere and angular error estimates distinguish the two stated hypotheses over multiple sites. No astrophysical law is needed.'),
(2,'KEEP',[I],'theory','Rolling square wheel with constant-height centre','The cube/contact drawing and no-slip assumption define geometric surface construction. Rigid-body inertia, energy and rolling kinematics compare slope descent with a round wheel.'),
(3,'KEEP',[I],'theory','Pressure resultant on cylindrical pasta passing a seal','Atmospheric and mouth pressure act on exposed cross sections and contact surfaces. Ordinary pressure stress balance and lip friction resolve the stated paradox; detailed biological swallowing is not requested.'),
(4,'KEEP',[I,II],'theory','Block collision with a massive axial Hooke spring','Total mass, axial spring stiffness, length and elastic impact are supplied. Discretizing an ordinary Hooke spring derives longitudinal waves and the end-mass boundary dynamics, with wave transit important for a light striker. No bending/tensor elasticity is required.'),
(5,'KEEP',[I],'theory','Vertical motion with prescribed exponentially growing mass','The rendered mass law and comoving added-mass clause were checked. Newtonian momentum accounting with the stated intake velocity determines the apex and mass. No relativistic mass-generation law is requested.'),
(6,'KEEP',[I,II],'theory','Amplitude-independent oscillation in an anharmonic potential','Energy quadrature, inverse functions and Taylor coefficients construct isochronous potentials. These are ordinary one-dimensional mechanics and mathematics.'),
(7,'KEEP',[I],'theory','Newtonian potential with a compact Euclidean extra dimension','Flat Euclidean geometry and periodicity are explicit. Generalizing gravitational flux to a sphere in the stated dimension and summing periodic image sources gives the potential and limits; no spacetime curvature or relativistic field theory is required.'),
(8,'KEEP',[I,II],'numerical','Normal modes of a discretized hanging rope','Newton force balance, tension from supported weights, small-angle oscillations and matrix/continuum limits determine the modes and spectral sums. Flexible-string waves are conventional; no bending stiffness is introduced.'),
(9,'KEEP',[I],'numerical','Rope shape and edge wear with explicit bending and abrasion laws','Curvature proportional to torque and wear speed proportional to contact force are both supplied. Local force/torque balance and geometric differentiation determine elastica and moving-boundary wear; no unsupplied constitutive bending law need be known.'),
(10,'KEEP',[I],'numerical','Ballistic deposition on a spherical asteroid','Kepler/Newton trajectories, energy/angular momentum, solid-angle probability and inverse distributions yield fallback fraction and surface thickness. Impact fragmentation is replaced by the supplied emission assumptions.'),
(11,'REJECT',[],'experimental','Slow viscous film draining from a surface and container','Predicting the requested time dependence and retained volume centrally requires an unsupplied viscous-film stress/velocity-profile or lubrication model. The experimental check is eligible in format but does not supply that physics.'),
(12,'BORDERLINE',[I],'theory','Inferring smoke-ring direction from the supplied photograph','The actual embedded torus image is present and inspected. A qualitative parcel-circulation and momentum explanation may use ordinary mechanics, but inferring propagation from smoke texture can require unsupplied vortex-flow induction and is visually ambiguous. Intended depth is unresolved.'),
(13,'BORDERLINE',[I,IV],'theory','Comparing melting times in fresh and salt water','Calorimetry, density-driven convection and melting/freezing arguments are foundational, but a quantitative time ratio also requires a declared mixing/heat-transfer and saline-property model absent from the statement. The qualitative and quantitative work is inseparable here.'),
(14,'KEEP',[I,III],'data_analysis','Pressure from resolved gas-particle collision velocities','Individual momentum jumps, spherical impact geometry and kinetic-gas momentum flux connect measured velocity changes and total time to pressure. The supplied Einstein relation is context; no stochastic master equation is needed.'),
(15,'KEEP',[],'theory','Correlations of a fully specified linear white-noise system','Matrix evolution and the explicit delta-correlated noise covariance give an integral for the covariance. This is supplied stochastic mathematics, not an unsupplied physical fluctuation theory.'),
(17,'KEEP',[X],'theory','When atmospheric refraction makes a celestial disk elliptical','Snell ray bending in a stratified atmosphere and a local angular-map expansion determine anisotropic magnification and ellipse accuracy. Refractive-profile parameters may be retained symbolically; no exact atmosphere is asserted.'),
(18,'KEEP',[X],'theory','Transmission through a slowly varying refractive layer','Maxwell wave propagation, interface continuity and asymptotic integration for the specified index profile determine reflection/transmission. Ordinary EM/wave optics suffices; permeability/absorption and outside-medium conventions must be declared.'),
(19,'KEEP',[VII],'theory','Stability of arbitrary fixed-moment permanent-magnet levitation','Fixed magnetic moments are explicitly distinguished from field-responsive superconductors. In a source-free region each component of external B is harmonic, so the translational potential of any rigid permanent-magnet assembly cannot have a strict local minimum. This is magnetostatics and calculus, not a superconducting prerequisite.'),
(20,'KEEP',[],'theory','Kinematics of a fully specified alternative absolute-time transformation','Absolute time, preservation of the positive light speed and rational transformations are given. Homogeneous frame transformations yield x-prime=(x+V*t)/(1+V/c), its group and velocity composition. Most work is algebra on this supplied toy model; final comparison with Lorentz classification is peripheral.'),
(21,'BORDERLINE',[I,VI],'theory','Dynamics and couplings for the source-defined alternative frame group','The statement explicitly continues Q20, so its toy group is supplied by source relationship. Invariant-action construction and correspondence are mathematical mechanics, but tensor metric choice and gravitational/electromagnetic coupling prescriptions are not operationally specified. Whether constructing a permissible model or knowing an intended outside dynamics is central remains unresolved.'),
(22,'REJECT',[],'theory','Covariant EM field and stress-energy tensor eigenstructure','Neither tensor components nor relativistic transformation, invariants or physical eigenvector interpretation are printed. The broad suggested Landau-Lifshitz book is not an acquired supplied model. Relativistic electrodynamics centrally determines the task.'),
(23,'REJECT',[],'numerical','Lifetime-limited accelerated travel in an expanding Lambda-CDM universe','Proper acceleration, proper-time travel and the expanding-universe metric/parameters are not provided as an operational model. Unsupplied special/general relativity and cosmology control the requested reach.'),
(24,'KEEP',[VI],'numerical','Distributed junction response under a fully supplied Helmholtz model','The full driven 2D PDE, complex wave number, no-radial-flow boundary, electrode shapes and material parameters are printed and visually checked. Solving the PDE and spatially averaging voltage over finite electrodes yields the plots without deriving semiconductor transport.'),
(25,'BORDERLINE',[I],'theory','Classical stability and quantum states of a lens billiard','Elastic ray reflection and local return-map geometry make the classical orbit and surrounding section accessible. The final localized quantum energy states need an unsupplied semiclassical quantization rule. That is a meaningful coupled extension rather than a tiny aside.'),
(26,'REJECT',[],'theory','Quantizing a scale-flow Hamiltonian and imposing a spectral condition','Classical scale motion is accessible, but constructing a Hermitian differential Hamiltonian, its eigenfunctions and the proposed spectral condition requires unprovided quantization/operator/domain machinery. This is the dominant dependency.'),
(27,'REJECT',[],'theory','Gravitational quantum box eigenlevels','Box walls and force do not supply the Schrodinger equation, operator realization, Airy eigenproblem or semiclassical quantization. Those quantum laws are the whole central task.'),
(28,'KEEP',[],'theory','Clifford and spinor identities from explicitly defined division-algebra matrices','The actual matrices, conjugation, gamma action and target anticommutator are supplied. Determinants, bilinear forms, matrix group representations and nonassociative algebra give the requested identities/covariance and octonion caveats. No quantum dynamics or matter-field law is requested.'),
(29,'REJECT',[],'theory','Bose condensation temperature and finite-size correction','Bosonic occupation, chemical-potential limiting criterion and oscillator quantum density of states are not supplied. Specialized quantum statistics controls both the leading temperature and correction.'),
(30,'REJECT',[],'theory','Time evolution of a two-component electronic wave packet','Hamiltonian matrix elements and initial spinor are supplied, but the time-evolution rule and quantum interpretation connecting spectrum to dynamics are not. Diagonalizing alone does not determine the requested spinor packet spreading. Rendered alpha includes a square root missed by extraction.'),
(31,'KEEP',[III,X],'numerical','Engineering a refractive gradient to bend sunlight into an office','Solar geometry, graded-index ray paths, gas density/temperature estimates and feasibility calculations are general optics and gas physics. Devices and limitations can be estimated under stated engineering assumptions without an unsupplied exotic law.')]
pages={n:2 if n<=5 else 3 if n<=10 else 4 if n<=16 else 5 if n<=20 else 6 if n<=24 else 7 if n<=27 else 8 if n<=30 else 9 for n in range(1,32)}
u={int(r['problem_number']):r for r in c.execute('select * from units where source_file_id=3131')};assert len(u)==31 and all(r['decision'] is None for r in u.values())
out=[]
for n,d,dom,fmt,phy,reason in rows:
 out.append(dict(screening_unit_id=u[n]['screening_unit_id'],decision=d,confidence='medium' if d=='BORDERLINE' else 'high',primary_spho_domains=';'.join(dom),required_physics=phy,decision_reason=reason,external_physics_if_any=phy if d in ('BORDERLINE','REJECT') else '',format=fmt,page_start=pages[n],page_end=6 if n==20 else 7 if n==24 else pages[n],visual_inspection_used=1,solution_used=0,boundary_status='content_boundary_verified',needs_second_review=n in (4,7,9,15,18,20,24,28),evidence=f'Complete actual Ortvay 2009 Q{n}, physical p{pages[n]}, inspected from valid SHA cache and all nine full-page renders. Q20 continues on p6 and Q24 on p7. Square wheel/edge/smoke geometry and intact matrix/PDE/noise formulas checked. Whole parent clauses retained. No official worked solution acquired.'))
p=w.ROOT/'reviews/shutdown_ortvay_2009_30.json';w.writejson(p,out);w.decisions(p)
# Linked historical algorithm is essential to Q16 and was not recovered.
assert c.execute('select decision from units where screening_unit_id=?',(u[16]['screening_unit_id'],)).fetchone()[0] is None
c.execute("update units set review_status='unresolved_source_unavailable',format='theory',page_start=4,page_end=4,visual_inspection_used=1,boundary_status='content_boundary_verified',evidence=?,source_quality_notes=? where screening_unit_id=?",('Actual Q16 p4 and linked-source attempts inspected. Exact Hungarian HTTP/HTTPS URLs redirect to the current homepage; corresponding English path redirects to a general security page with no shuffle algorithm. Exact pre-2011 archive query timed out. See reviews/shutdown_ortvay_2009_q16_source_attempts.json. No algorithm or scope decision invented.','Essential historical shuffle algorithm missing. Uniform random-permutation mathematics may be intended, but a current fairness claim does not establish the exact stated algorithm.',u[16]['screening_unit_id']))
c.execute("update paper_boundary_audit set status='full_paper_boundaries_verified',observed_units=31,evidence=?,checked_at=? where file_id=3131",('All nine physical pages inspected: cover p1, Q1-Q31 on pp2-9; Q20 pp5-6 and Q24 pp6-7 each one parent task. Q21 explicitly source-linked to Q20 but independently numbered. Embedded smoke photograph present; Q16 external algorithm separately unavailable. No omitted top-level task.',w.now()))
notes={4:'Uniform axial Hooke-spring idealization; finite transit cannot be replaced by a massless spring when striker is light.',5:'Added mass is stated comoving; assuming stationary accretion would silently change momentum balance.',7:'Higher-dimensional Newtonian flux normalization must be stated. Extra dimension is Euclidean/periodic, not a relativistic spacetime.',12:'Embedded photo is present but detailed circulation/propagation inference is ambiguous.',13:'Initial salt dissolution heat, solution properties, ice placement and convection/heat-transfer assumptions affect the requested time ratio.',15:'Conventional zero-mean white noise independent of the initial state is intended; without initial-noise independence additional cross covariance is needed.',18:'Outside media and any magnetic/absorptive response are unspecified; use declared ordinary nonmagnetic transparent-layer convention.',20:'Only positive-direction light speed is preserved. This is not Lorentz kinematics; do not import the two-way c axiom. Final classification/comparison is peripheral.',21:'Q20 is explicitly referenced as part of this statement, not inferred from a neighbor. The toy group may have a degenerate invariant metric; coupling/action specification remains a model-construction ambiguity.',24:'Rendered Reff=|U|/(J*rL^2*pi), not the reversed expression in extraction. Voltage is spatially averaged over each finite electrode. Square-wave response can use harmonic superposition; displayed complex a is per frequency.',28:'Division-algebra identities are mathematics. Octonionic nonassociativity complicates the final extension but is not an unprovided physical law.',30:'Rendered alpha=sqrt(epsilon/|epsilon|); cached extraction drops the root. The missing evolution law, rather than mathematical difficulty, is the prerequisite issue.',31:'Atmospheric refractivity-density and device feasibility require declared numerical assumptions; proposed construction is not claimed practically realizable.'}
for n,note in notes.items():c.execute('update units set source_quality_notes=? where screening_unit_id=?',(note,u[n]['screening_unit_id']))
c.commit();print('Saved 30 decisions, one explicit missing-source item and complete 31-task boundary audit.')
