"""Explicit decisions, not an automatic topic classifier."""
import workflow as w
c=w.connect();I='I_force_motion';II='II_oscillations_waves';III='III_ideal_gas';IV='IV_thermodynamics';VI='VI_electric_field';IX='IX_em_oscillations_waves';X='X_wave_optics';XII='XII_nuclear_physics'
rows=[
(1,'KEEP',[I],'theory','Tractor wheel size, steering and traction','Both tractor photos and rear-drive condition were inspected. Contact pressure, rolling obstacles, torque/traction and steering geometry give qualitative advantages; no specialized tyre constitutive model is requested.'),
(2,'KEEP',[I,II],'theory','Three-mass pulley slingshot with changing rope geometry','The complete force/rope drawing and all four parts were inspected. Newtonian tension, kinetic energy, equilibrium curvature and detachment determine launch speed/time and small oscillations.'),
(3,'KEEP',[I],'theory','Frictionless collapse of a loaded hinged ladder','Rigid rods, hinge and sliding feet specify a constrained Newtonian motion. Gravitational energy and rod inertia determine impact speed and time quadrature.'),
(4,'KEEP',[I],'theory','Sequential elastic ball collisions and escape-energy efficiency','The full four-part task uses ordinary momentum/energy collision laws, ballistic timing and Newtonian escape energy. No unsupplied relativistic rocket law is requested.'),
(5,'KEEP',[I,II],'theory','Rotating magnetic-dipole pair with fixed or hinged tube','The full apparatus was inspected. Ordinary dipole interaction, gravity and centrifugal balance give equilibria and coupled small oscillations under each supplied constraint.'),
(6,'KEEP',[I],'theory','Elastic/inelastic impacts on a quarter-circle wall','The incoming offset and arc geometry were checked in the figure. Contact normal impulse, tangential velocity and repeated geometry determine collision count and exit, including the grazing limit.'),
(7,'KEEP',[I],'theory','What biased die outcomes imply about rigid-body parameters','Given probabilities do not uniquely specify launch dynamics, shape or mass distribution. Ordinary rigid-body motion and inverse-problem nonuniqueness permit a reasoned answer; no specialized stochastic collision law is required.'),
(8,'KEEP',[I,III],'data_analysis','Model fitting to supplied high-altitude free-fall observations','The source-linked height and velocity files were recovered and validated. Newtonian gravity, atmospheric gas density, effective drag and orientation-dependent area permit a simplest fitted model. Empirical parameters and limb motion can be inferred/approximated without requiring an exact unsupplied CFD theory.'),
(9,'KEEP',[I,II],'numerical','Retarded sound frequency and direction of an off-axis moving siren','Sound speed and uniform trajectory are given. Emission/reception geometry and Doppler timing determine subsonic/supersonic branches; visual propagation is explicitly instantaneous.'),
(10,'KEEP',[IV],'theory','Time-varying power of an ideal refrigerator in an insulated room','Carnot efficiency, finite thermal reservoirs and first-law heating determine power trends under explicit load/control assumptions. Those missing numerical parameters are ordinary apparatus choices, not outside physics.'),
(11,'KEEP',[I,III],'theory','Momentum source for buoyancy-driven chimney flow','Hydrostatic pressure differences, gravitational force and control-volume momentum balance explain rising heated air. Only a conceptual momentum accounting is asked, not a specialized convection-rate calculation.'),
(12,'KEEP',[VI],'numerical','Equivalent resistance of a periodic finite-range resistor chain','The exact network links were inspected. Kirchhoff/Ohm laws reduce arbitrary-node resistance to a linear system or Fourier integral; algorithm analysis is mathematics.'),
(13,'KEEP',[VI],'theory','Inferring lattice slab thickness from surface resistance','All lattice directions, thickness and nearest-neighbour resistors are specified. Ordinary circuit conservation and discrete Green functions determine measured resistance and limiting cases.'),
(14,'KEEP',[VI],'theory','Four-contact potential on a finite conducting disc','The A/B internal contacts and C/D boundary positions were inspected. Local Ohm law, current continuity and insulating outer boundary define potential; image/conformal methods are mathematical tools.'),
(15,'KEEP',[VI],'theory','Equipotential shape around a line in a supplied anisotropic dielectric','The permittivity tensor model is explicitly stated. Electrostatic potential and coordinate scaling give elliptic equipotential cylinders; no microscopic dielectric theory is required.'),
(16,'KEEP',[I,VI],'theory','Equilibrium electric deformation of a conducting liquid drop','Weak-field and surface-tension parameters are supplied. Ordinary conductor surface pressure and capillary force balance, or electrostatic/surface-energy variation, give small deformation. No fluid transient law is needed.'),
(17,'KEEP',[VI],'theory','Nonzero Coulomb fields and cancellation of charge multipoles','The precise charge arrangements and algebraic claims are supplied. Coulomb superposition, field zeros and multipole expansion are ordinary electrostatics plus mathematics.'),
(18,'KEEP',[I,VI],'numerical','Classical Coulomb-chain ground configuration in a parabolic trap','The nanotube is expressly replaced by classical charges with an effective mass, permittivity and parabolic confinement. Minimizing ordinary Coulomb-plus-spring energy determines positions and energy; semiconductor terminology introduces no additional prerequisite.'),
(19,'KEEP',[III,IX,X],'numerical','Classical clear-sky scattering and calibrated RGB rendering','The requested dawn geometry and example photo were inspected. Maxwell-driven molecular dipole scattering, solar spectral illumination and spectral colour calibration supply a classical optical route. Atmospheric composition/polarizability and monitor response are unsupplied numerical inputs, not a central new quantum scattering model.'),
(20,'KEEP',[X],'theory','Gaussian-beam diffraction and return from a corner cube','The reflector photo, distance, wavelength and beam sizes were inspected. Ordinary aperture/Gaussian wave optics and reflection give relative intensity distribution; laser pulse generation is not requested.'),
(21,'KEEP',[II],'theory','Retarded solution of an explicitly supplied moving-source wave equation','The full inhomogeneous wave PDE is printed. Green functions, emission-time roots and dimensional generalizations are mathematics applied to ordinary sound; no unsupplied exotic spacetime physics is needed.'),
(22,'REJECT',[],'theory','Relativistic moving-mask photodetection in two frames','Mask speed 12c/13 makes Lorentz contraction, simultaneity and frame-dependent light timing central. These relations are not supplied; ordinary photocurrent alone cannot solve the task.'),
(23,'REJECT',[],'theory','Inverse relativistic scalar field from prescribed elliptic orbits','Scalar-generated rest mass does not supply relativistic action/momentum dynamics. These unsupplied relations determine every requested radial field reconstruction.'),
(24,'REJECT',[],'theory','Gravitational-wave circularization of an eccentric binary','No gravitational-radiation energy/angular-momentum or orbital-rate law is supplied. This specialized relation centrally determines the sole timescale and element evolution; unlike 2017 Q38 the model is absent.'),
(25,'KEEP',[],'theory','Invalid squared differential-operator expectation on a hard interval','The wavefunction, differential Hamiltonian and both computed integrals are explicit. Normalization, integral evaluation and checking the operator domain/boundary terms diagnose the misleading variance. No missing quantum evolution or measurement rule is needed.'),
(26,'REJECT',[],'theory','Quantum two-electron nanotube spectrum and exchange coupling','The classical confinement/Coulomb model is given, but Schrodinger two-particle dynamics, spin antisymmetry and singlet/triplet state construction are not. They dominate every wavefunction, excitation and exchange task.'),
(27,'BORDERLINE',[],'theory','Quantum pump cycle under a supplied scattering-charge formula','The pumping trace formula and projection matrices are given; the explicitly linked four-page reference supplies optimality and integer-winding criteria. Substantial cycle analysis is self-contained matrix mathematics, but constructing the required physical energy-independent one-dimensional scatterer may need unsupplied quantum boundary/scattering dynamics.'),
(28,'REJECT',[],'theory','Tight-binding transmission and quantum envelope-function dynamics','Hopping/onsite parameters and diagram are supplied, but their wave-amplitude evolution, scattering current and envelope-function Hamiltonian rules are not. These specialized quantum transport dependencies centrally determine both mandatory parts.'),
(29,'KEEP',[XII],'data_analysis','Confidence that all independent radioactive nuclei have decayed','Half-life, number and independence fully specify exponential survival and the last-decay order statistic. Ordinary nuclear decay and probability suffice.'),
(30,'KEEP',[],'theory','Normal-ordering conversion under an explicitly supplied scalar operator model','Field expansion, oscillator commutator, mass-frequency relation and creation-before-annihilation ordering are all printed. Reordering polynomial/exponential series with those supplied rules and changing oscillator basis is algebra/integration; no scattering, field dynamics or missing renormalization prescription is requested.'),
(31,'REJECT',[],'theory','Effective thermal state of one hidden-partner quantum oscillator','A coupled Hamiltonian alone does not define quantum ground states, reduced density operator or thermal-state inference. These unsupplied quantum entanglement/statistics rules control the sole temperature task.'),
(32,'REJECT',[],'theory','Scalar-particle decay lifetime from self-energy imaginary part','The interaction Lagrangian and target relation are given, but propagators, self-energy/resonance pole and quantum decay-amplitude rules are not. These are the central field-theory prerequisites.'),
(33,'KEEP',[IV],'numerical','Entropy maximum and stability of a fully specified classical vector model','Energy, evolution, invariants, density, entropy and order parameter are explicitly defined. Constrained entropy variation, ordinary inverse-temperature derivative and Hessian/stability analysis give equilibrium and plots. Negative-temperature context adds no unsupplied quantum spin theory.'),
(34,'REJECT',[],'theory','Gauge invariance and a quantum-field Ward identity','The identity is printed but proper vertices, time-ordered correlations, 1PI projection and gauge quantum-field rules are not. They centrally determine the conceptual answer.'),
(35,'KEEP',[II],'theory','Linearized waves of an explicitly supplied nonlinear complex PDE','The complete Gross-Pitaevskii equation, density normalization, c and xi are supplied. Linearization about a homogeneous solution and elimination of real/imaginary perturbations give a real dispersive wave equation. Comparing long-wavelength wave symmetry with higher derivatives is mathematical model analysis, not derivation of an unsupplied condensate theory.'),
(36,'KEEP',[I],'theory','Vertical launch, orbital timing and a rotating Earth target','The complete narrative spans pp10-11. Newtonian central-force orbits, angular momentum and Earth rotation explain the simulated versus actual return and geographic separation. No exotic law is needed.')]
pages=[1,1,2,2,2,3,3,3,3,3,4,4,4,4,4,5,5,5,5,6,6,6,6,6,7,7,7,8,8,8,9,9,9,10,10,10]
units={int(r['problem_number']):r for r in c.execute('select * from units where source_file_id=3124')};assert len(units)==36
out=[]
for n,d,dom,fmt,physics,reason in rows:
 u=units[n];assert u['decision'] is None
 out.append(dict(screening_unit_id=u['screening_unit_id'],decision=d,confidence='medium' if d=='BORDERLINE' else 'high',primary_spho_domains=';'.join(dom),required_physics=physics,decision_reason=reason,external_physics_if_any=physics if d in ('BORDERLINE','REJECT') else '',format=fmt,page_start=pages[n-1],page_end=11 if n==36 else pages[n-1],visual_inspection_used=1,solution_used=0,boundary_status='content_boundary_verified',needs_second_review=n in (8,16,18,19,25,30,33,35),evidence=f'Whole printed Ortvay 2016 Q{n}, physical p{pages[n-1]}'+('-11' if n==36 else '')+' read from verified SHA cache. Full renders of all eleven physical pages inspected for apparatus, photos, source links and operator/PDE formulas. Q8 essential original datasets preserved; Q27 explicitly linked reference model checked. No worked solution accompanies the acquired paper or is linked in organizer archive. Internal parts remain one top-level problem.'))
p=w.ROOT/'reviews/shutdown_ortvay_2016_36.json';w.writejson(p,out);w.decisions(p)
c.execute("update paper_boundary_audit set status='full_paper_boundaries_verified',observed_units=36,evidence=?,checked_at=? where file_id=3124",('All eleven physical pages read and rendered: exactly Q1-Q36, with Q36 continuing on p11. Photos, apparatus drawings and reference links are part of existing numbers. No unindexed top-level task found.',w.now()))
notes={8:'Original h_vs_t and v_vs_t files are headerless. Numeric units inferred by cross-check (height plausibly metres; velocity plausibly km/h); source bytes retained. Video URL could not be read by web tool, but both numerical files are available and preserved.',9:'Last paragraph mistakenly labels the supersonic branch V<c; preceding statement explicitly defines V>c.',10:'Cooling setpoint/control, fridge heat capacity and room heat capacity not specified; power time course needs explicit ordinary apparatus assumptions.',15:'Permittivity tensor entries/orientation and line charge remain symbolic inputs.',18:'Classical effective mass and Coulomb screening are explicitly supplied; quantum counterpart is separate Q26 and not an alias.',19:'Exact RGB values require optical polarizability/air-density spectral data, absorption assumptions and monitor calibration, not numerically specified.',20:'Absolute source power and precise corner-cube phase/aperture convention not supplied; relative intensity/distribution remains calculable under explicit optical assumptions.',21:'Source calls wave amplitude u sound intensity; physical intensity convention and source normalization need clarification.',25:'Hard-interval boundary domain matters when applying the differential Hamiltonian twice; source integral expressions must not be trusted as valid squared moments without it.',27:'Four-page problem-linked Optimal Quantum Pumps reference preserved with hash/provenance. It supplies cycle criterion but does not supply a simplest energy-independent 1D physical scatterer construction.',30:'All noncommuting reordering uses the actually supplied oscillator commutator and field expansion; no unrelated QFT source was used to supply missing contestant physics.',33:'Vector energy, dynamics, entropy and constraints are supplied; classical continuum mean-field limit is the printed model.',35:'Model is explicitly supplied nonlinear complex PDE; analysis need not assume microscopic Bose condensate physics.',36:'Complete source task includes physical pp10-11; narrative clauses remain within Q36.'}
for n,note in notes.items():c.execute('update units set source_quality_notes=? where screening_unit_id=?',(note,units[n]['screening_unit_id']))
c.commit();print('Saved 36 explicit decisions and full eleven-page paper boundary audit.')
