"""Explicit whole-paper boundaries and physics readings, not an automatic classifier."""
import workflow as w
c=w.connect();bs=[]
maps={4094:([2,2,3,3,3,4,4,4,5,5,6,8,9,10],[2,2,3,3,3,4,4,4,5,5,7,8,9,10]),4060:([3]*7+[4]*5+[5]*3+[6]*3+[7]*2+[8]*2+[9]*2+[10]*4+[11]*6+[12]*3+[13]*5+[14]*3+[15]*3+[16]*2,None),4035:([2,2,3,3,3,4,4,4,5,6],[2,2,3,3,3,4,4,5,5,6]),4036:([2,2,2,3,3,3,4,4,5,5],None),4037:([2,2,2,3,3,3,3,3,4,4],None),4038:([2,2,3,3,4,5,5,5,6,6],None),4039:([2,2,2,2,2,3,3,3,4,4],None)}
for pid,(starts,ends) in maps.items():
 r=c.execute('select * from containers where source_problem_id=?',(pid,)).fetchone();assert r['status']=='pending_boundary_review'
 ends=ends or starts
 assert len(starts)==(50 if pid==4060 else 14 if pid==4094 else 10)
 us=[]
 for i,(start,end) in enumerate(zip(starts,ends),1):
  fmt='multiple_choice' if pid==4060 or (pid==4094 and i<=10) else 'experimental' if pid==4094 and i==14 else 'theory'
  us.append(dict(number=str(i),page_start=start,page_end=end,format=fmt,location={'source_label_present':True,'boundary_note':'Printed top-level numbering visually verified across all statement pages; internal parts retained.'}))
 bs.append(dict(source_problem_id=pid,boundary_evidence='All statement page renders visually inspected. Source cover count reconciles with printed top-level question headings; constants/blank pages excluded.',units=us))
p=w.ROOT/'reviews/resume_english_scan_boundaries.json';w.writejson(p,bs);w.derive(p)
I='I_force_motion';II='II_oscillations_waves';III='III_ideal_gas';IV='IV_thermodynamics';V='V_real_gas';VI='VI_electric_field';VII='VII_magnetic_field';VIII='VIII_induction';IX='IX_em_oscillations_waves';X='X_wave_optics';XI='XI_quantum_light';XII='XII_atomic_nuclear'
au=[([I],'Phone dropped onto head: gravitational and contact forces'),([I],'Newton third law in truck-whale collision'),([I],'Steady chair motion and kinetic friction'),([I],'Increased applied force and acceleration under kinetic friction'),([IV],'Refrigerator waste heat and energy balance'),([], 'Measurement uncertainty in height differences'),([], 'Repeated measurements and uncertainty interpretation'),([I],'Inelastic collision momentum'),([I],'Projectile speed and acceleration at apex'),([I],'Planet mass and summation of separated component weights'),([I,II],'Bungee cord potential energy, motion and graph slopes'),([I],'Helicopter momentum flux, air column geometry and power scaling'),([IV],'Explicit microscopic conduction model and dimensional form of heat-flow law'),([II],'Experimental design for acoustic transit speed in air and steel; timing and uncertainty')]
sj=[
([I],'SI units of weight'),([I],'Piecewise travel displacement with shared stem'),([I],'Average velocity with shared travel stem'),([I],'Vertical projectile travel time'),([I],'Building height from projectile flight'),([I],'Tractor and trailer forces on inclined road'),([I],'Towbar tension on inclined road'),([I],'Ball rebound impulse and speed'),([I],'Accelerated car displacement ratio'),([I],'Stopping train distance from decreasing speed'),([I],'Constant torque and rotational energy ratio'),([I],'Momentum change in head-on collision'),([I],'Displacement-time graphs and relative motion'),([I],'Circular satellite speed on a different planet'),([I],'Instantaneous power of applied force'),([I],'Perpendicular force and momentum magnitude'),([I],'Floating-volume fractions and density'),([I],'Energy of elliptical satellite orbit at perigee'),([I,II],'Circular motion and stretched elastic string'),([I],'Ladder equilibrium with friction at wall and floor'),([I],'Uniform angular deceleration and rotational kinetic energy'),([II],'Vertical elastic-string oscillation with displacement convention'),([I,II],'Velocity-position graph from linear restoring acceleration'),([X],'Lens focal length from object/image graph'),([X],'Lensmaker dependencies'),([II],'Simple-harmonic displacement after specified fraction of period'),([II],'Beat frequencies and tuning fork identification'),([X],'Wavelength change upon refraction'),([X],'Prism minimum-deviation geometry'),([X],'Compound microscope lens changes'),([II],'Two-speaker interference along an axis'),([X],'Diffraction grating and coincident orders'),([VI],'Potential of an isolated charged metal sphere'),([VI],'Coulomb force in a dielectric'),([I,VI],'Electric support of charged oil drop'),([I,VI],'Parallel-plate capacitor energy and separation'),([VI],'Parallel capacitor combination'),([VI],'RC discharge exponential time'),([VI],'Drude current and mean carrier drift speed'),([VI],'Ohmic rod current scaling with diameter, length and voltage'),([VI],'Loop resistance between adjacent square corners'),([VI],'Power dissipation ratio in cylindrical resistors'),([VI,VII],'Trajectory in mutually perpendicular electric and magnetic fields'),([VI],'Potentiometer balance and cell EMF ratio'),([VI],'Voltmeter loading and variable-resistor circuit'),([III],'Ideal-gas container calorimetry and mass determination'),([III,IV],'Isothermal gas compression, heat and work'),([III],'Absolute temperature from constant-volume pressure extrapolation'),([IV],'Conduction through a slab with specified conductivity'),([III],'Mean molecular kinetic energy from pressure versus inverse volume graph')]
sp={
4035:[([I],'Yo-yo torque, rolling and friction direction'),([I],'Yo-yo centre-of-mass acceleration independent of string pull angle'),([VI],'Coaxial cylindrical capacitor and dielectric insertion'),([I,II],'Distributed spring mass and oscillator effective inertia'),([I],'Water-wave propagation scaling and sand damping of an oscillating board'),([I,VI],'Charged capacitor plates, attraction and jumping motion energy'),([IV],'Supplied two-level heat-capacity model and impurity relaxation time'),([IV,I],'Dimensional heat-loss model for meteorite; peripheral meson momentum-transfer extension'),([VII],'Magnetic field of two straight current-carrying segments using Biot-Savart'),([XII],'Rb-Sr decay dating and isochron slope')],
4036:[([I],'Dimensional blast-radius scaling and supplied density/energy data'),([I,II],'Adiabatic pendulum length change and work/oscillation amplitude'),([I],'Projectile fragments and time-of-flight momentum conservation'),([VI,II],'Supplied Thomson uniform-charge atomic model and electron oscillation'),([], 'Photon-rocket exhaust with relativistic energy and momentum conservation'),([VIII],'Small conducting ring motion in spatially varying magnetic field'),([X],'Three linear polarizers and Malus law'),([VI,VIII],'Two sliding rods, motional EMF and parallel rail current'),([VI,VIII],'RL switching, current-time graph and decay'),([X],'Refraction through mirrored transparent cylinder')],
4037:[([I],'Scale calibration under acceleration and height-dependent gravity'),([I],'Forces in a chain of sliding blocks'),([I,II],'Physical pendulum ring with a mass on a diameter'),([I,II],'Pendulum period difference at pole and equator'),([VI],'Resistor lattice wrapped into cylinder'),([], 'Relativistic electromagnetic field and charge/current transformations between observers'),([III,IV],'Adiabatically expanding monatomic helium balloon'),([I,VI,VII],'Classical two-charge orbital solutions in a magnetic field and Coulomb attraction/repulsion'),([I],'Vertical steel cylinder flotation including capillarity'),([X,II],'Double-slit phase changing with supplied time-dependent refractive indices')],
4038:[([II],'Supplied exponential pendulum damping law and measurement-error propagation'),([I,II,XI],'Optical momentum, optical tweezers and elementary kinetic/Brownian estimates'),([I,II],'Elastic bead collisions, driven chain and propagation speed'),([X],'Two-lens variable-magnification zoom system'),([I],'Rod torque balance against one or many circles'),([IV],'Heat conduction and helium boil-off energy balance'),([X],'Soap-film interference and wavelength-dependent refractive index'),([VII],'Thick-solenoid field, winding geometry and power parameterization'),([I,II],'Stacked blocks in spring oscillation and falling-string tension'),([], 'Neutrino signal in moving frames and relativistic rod length/orientation')],
4039:[([I],'Elastic rebound from tilted plane'),([I,II],'Rolling solid sphere oscillation inside cylindrical trough'),([X],'Lens and convex mirror images'),([II,X],'Radio path interference at a lake surface'),([XI],'Photoelectric threshold energy and electron emission rate'),([I],'Vertical launch, escape speed and maximum height'),([VI],'Multi-cell DC network currents'),([IV],'Steam heating, condensation and calorimetry'),([VI,VII,XI],'Crossed-field photomultiplier electron trajectory with stated emission and field model'),([], 'Relativistic rod length and orientation in its proper frame')]
}
out=[]
for pid,items in [(4094,au),(4060,sj),*sp.items()]:
 for n,(domains,phys) in enumerate(items,1):
  u=c.execute('select * from units where source_problem_id=? and problem_number=?',(pid,str(n))).fetchone();assert u and u['decision'] is None
  reject=(pid,n) in {(4036,5),(4037,6),(4038,10),(4039,10)}
  reason=('Unsupplied special-relativistic '+('energy and momentum laws' if (pid,n)==(4036,5) else 'frame transformations')+' are structurally central to the entire question.' if reject else 'The meaningful work uses '+phys[0].lower()+phys[1:]+'; this is syllabus physics, ordinary prerequisite reasoning or a supplied model.')
  if (pid,n)==(4035,8):reason='Most work is dimensional thermal modeling. The shorter meson momentum-transfer extension may require unsupplied relativistic dynamics but does not control the main task.'
  out.append(dict(screening_unit_id=u['screening_unit_id'],decision='REJECT' if reject else 'KEEP',confidence='high',primary_spho_domains=';'.join(domains),required_physics=phys,external_physics_if_any='Special relativity' if reject or (pid,n)==(4035,8) else '',decision_reason=reason,visual_inspection_used=1,solution_used=0,page_start=u['page_start'],page_end=u['page_end'],boundary_status='content_boundary_verified',evidence='Read the complete top-level statement and options/figures in rendered source pages. Full-size page 3 additionally inspected for Singapore 2012 Q6/Q8, and full-size page 5 for Singapore 2014 Q8.'))
assert len(out)==114,len(out)
p=w.ROOT/'reviews/resume_english_scans_content_114.json';w.writejson(p,out);w.decisions(p)
print('Saved',len(out),'content decisions')
