import workflow as w
c=w.connect()
rows=[
('raw::314',979,3,'theory','I_force_motion','Projectile kinematics, trajectory envelopes and geometric coverage Jacobian','Water elements are explicitly particle projectiles with equal launch speed. All A-B work is Newtonian kinematics, differentiating a trajectory family and matching hemisphere/ground annulus areas; no nozzle-flow constitutive theory is requested.',0,True),
('raw::315',981,4,'theory','X_wave_optics','Snell refraction, critical angles, meridional ray guiding and curved-fibre geometry','Snell law and refractive indices are given. Hemisphere dispersion, rod return conditions, environmental changes and fibre numerical aperture/bend correction require ordinary ray optics and geometry, not waveguide eigenmodes or material dispersion theory.',0,False),
('raw::316',984,8,'mixed','I_force_motion;X_wave_optics;XI_quantum_light;XII_atomic_nuclear;VII_magnetic_field','Angular motion, diffraction and spectral/flux data, supplied redshift/expansion/accretion models, annihilation energy and magnetic energy minimization','The actual A-F parent supplies gravitational redshift, Hubble constant and z~v/c, spectral flux/inverse-square conversion, Schwarzschild radius and both jet energy-density powers. Remaining work is graph/ratio analysis, algebra/calculus, Newton potential energy, mass-energy/photon relations and ordinary magnetic-field energy. No GR derivation, synchrotron emission law or black-hole accretion theory must be known.',1,True),
('raw::317',986,22,'experimental','I_force_motion;II_oscillations_waves','Gyroscope torque and angular momentum, inertia integration, experimental calibration/uncertainty, supplied Euler ODE and prototype design','The complete A-G experiment includes setup/leveling, speed-arm-mass-torque measurements, error analysis and prototype design. Precession law and motor calibration are explicitly supplied, and the full three Euler equations and principal-axis variables are printed for the small nutation part. Ordinary mechanics, measurement and ODE analysis cover the meaningful work.',0,True)]
out=[]
for uid,fid,np,fmt,dom,phy,reason,sol,focus in rows:
 u=c.execute('select * from units where screening_unit_id=?',(uid,)).fetchone();assert u and u['decision'] is None and u['source_file_id']==fid
 out.append(dict(screening_unit_id=uid,decision='KEEP',confidence='high',primary_spho_domains=dom,required_physics=phy,decision_reason=reason,external_physics_if_any='',format=fmt,page_start=1,page_end=np,visual_inspection_used=1,solution_used=sol,boundary_status='content_boundary_verified',needs_second_review=focus,evidence=f'APhO 2024 file {fid}: all {np} physical statement pages read in full SHA-cached text and all rendered pages actually inspected, including every internal part, equation, graph and apparatus image. One complete top-level parent per source. Quasar solution 983 all nine pages read; pp3/6/7/9 rendered for method/units/source-quality checks.'))
p=w.ROOT/'reviews/shutdown_apho_2024_4.json';w.writejson(p,out);w.decisions(p)
for uid,fid,np,fmt,*rest in rows:
 c.execute("update paper_boundary_audit set status='full_paper_boundaries_verified',observed_units=1,evidence=?,checked_at=? where file_id=?",(f'All {np} physical pages inspected, beginning through final part. One independently headed {fmt} task; internal A/B/etc and answer-option items remain subparts, no omitted top-level question.',w.now(),fid))
c.execute('update units set source_quality_notes=? where screening_unit_id=?',('Source/marking issues preserved, not silently repaired: B.1 key attributes occultation oscillations to telescope diffraction without an explanation; the supplied options omit an explicit lunar-edge diffraction option. A.1 key last line labels .55 per second as degrees rather than arcseconds. D.1 spectral luminosity retains an erroneous m^-2 unit. E.1 rendered key actually prints 8*10^14 J for .5 MeV and .000002 nm: direct unit conversion gives about 8*10^-14 J and .0025 nm (frequency about 1.2*10^20 Hz), so these are genuine source numerical errors, not broken extraction. F.2 wording mixes power with energy over one second; key uses the latter. All scope models remain supplied.','raw::316'))
c.execute('update units set source_quality_notes=? where screening_unit_id=?',('Complete 22-page apparatus/assembly instructions and A-G retained. Installation text says 26 mm while equipment/task descriptions say 26 cm. Printed Euler equations use the opposite cross-term signs from the usual right-handed body-axis convention; the given algebra still yields harmonic frequency magnitude when I1=I2 and torque is set to zero. Torque-free F.2 model is a stated idealization, not evidence that physical gravitational torque can be removed by choosing a frame. No measurements or prototype construction were performed by this screening.','raw::317'))
c.commit()
reviews=[
dict(screening_unit_id='raw::314',detail='Theory-format seeded QC Random(2026100429) selects raw::314. Full three-page A/B and sprayer diagram reread. Envelope follows derivative with respect to launch angle; coverage follows 2*pi*R*dR and hemisphere annulus area with the stated monotonic branch. Supplied particle-stream assumption excludes nozzle/fluid continuum prerequisites. Whole KEEP confirmed.'),
dict(screening_unit_id='raw::316',detail='Focused supplied-model/source-quality review: full eight-page A-F and nine-page official key checked. GR redshift and Schwarzschild radius explicitly given; Hubble relation/approximation and jet powers supplied; E2 key uses ordinary -GMm/r, not an unsupplied relativistic accretion law. E1 mass-energy and photon relation within atomic/nuclear and quantum-light domains. MCQ B1/B2 are internal subparts. Rendered key confirms numerical/unit errors in E1 and D1, recorded separately; no raw changes. Qualitative diffraction identification does not require a specialist occultation inverse model. Whole KEEP confirmed with source-quality qualifications.'),
dict(screening_unit_id='raw::317',detail='Experimental-format QC Random(2026100430) selects the only 2024 experiment. All 22 pages including installation photos, motor table, A-G tasks and missing-in-text equations reviewed. B6 has omega_p=m*g*r/(I*omega_s); F2 supplies all three Euler equations, and I1=I2 with tau=0 reduces the transverse components to coupled constant-coefficient harmonic ODEs. Central A-E/G work is torque/angular momentum, inertia and experimental design/data analysis. Idealized torque-free and cross-sign conventions are disclosed rather than repaired; no unsupplied advanced physics controls the whole parent. KEEP confirmed; no fabricated experimental data.')]
p=w.ROOT/'reviews/shutdown_apho_2024_focused_seeded_3.json';w.writejson(p,reviews);w.review(p)
print('Saved four whole 2024 tasks and four paper audits, with three focused/format QC records.')
