import workflow as w
c=w.connect();I='I_force_motion';II='II_oscillations_waves';IV='IV_thermodynamics';VI='VI_electric_field';VII='VII_magnetic_field';X='X_wave_optics';XI='XI_quantum_light'
rows=[
(1,'KEEP',[X],'theory','Maximum-volume building whose ground shadow stays on its site','Straight solar rays and the supplied elevation cutoff constrain roof height for each direction. Solar path geometry and intersecting geometric envelopes determine optimal volume; land ownership story adds no physics.'),
(2,'KEEP',[I],'theory','Geostationary visibility and centrifugal deviation of a plumb line','Spherical horizon geometry infers orbit radius from uncovered fraction. Newtonian orbit period and rotating-frame gravity determine plumb deviation; no relativity is asked.'),
(3,'KEEP',[I],'theory','Motion with friction exactly at the slope-balance threshold','Newtonian gravity and velocity-opposing Coulomb friction define the trajectory. Parametrization and asymptotic ODE integration are mathematics.'),
(4,'KEEP',[I],'theory','Sand-impact boundary under an explicitly supplied random tangent rule','The impact law is expressly given: speed retained, direction randomized in the tangent plane. Constraint force/detachment, energy and ballistic landing envelopes determine the whole covered region without an unsupplied granular collision model.'),
(5,'KEEP',[I,II],'theory','Torque-free near-orthogonal rigid dumbbell dynamics','The inertia geometry was checked in the render. Newtonian angular momentum/energy and small deviations from principal-axis rotation determine stability and motion for both mass ratios.'),
(6,'KEEP',[I],'theory','Second variation of an explicitly defined action functional','Stationarity, functional integral, fixed endpoint variations and kinetic-potential examples are supplied. Taylor expansion, integration by parts and quadratic-form spectra determine extrema; deriving an outside physical variational principle is not requested.'),
(7,'KEEP',[II],'theory','General solution of a fully supplied damped wave PDE','All PDE coefficients are given. An exponential time substitution reduces it to the ordinary wave equation; solution characterization is mathematical wave analysis.'),
(8,'KEEP',[IV],'theory','Efficiency bounds for elliptical thermodynamic cycles','The T-S, H-S and p-V planes and ideal-gas conditions are explicit. First-law work/heat, entropy and standard enthalpy relations bound the three cycle efficiencies.'),
(9,'KEEP',[I,IV],'theory','Consistency and heat capacity of a supplied thermoelastic spring','The energy and force equations, temperature coefficients and Carnot constraint are explicit across pp2-3. Thermodynamic differential consistency, mechanical equilibrium and heat capacity determine every linked part.'),
(10,'KEEP',[IV,X,XI],'theory','Second-law limit on passive concentration of sunlight','Both second-law formulations and exact equilibrium/radiation caveats are supplied. Heat-engine/refrigerator reasoning and optical reciprocity establish the limit; no unsupplied advanced radiation statistics is structurally necessary.'),
(11,'KEEP',[VI],'theory','Force on an axial charge near a grounded conducting torus','Equipotential conductor conditions and Coulomb potential define induced charge and force. Toroidal boundary mathematics may be difficult but requires no new electrostatic law.'),
(12,'KEEP',[VI],'experimental','Four-contact potential measurement on a rectangular conducting plate','The corner current and voltage geometry was inspected. Ohm law, current conservation and insulating edge conditions define the measured voltage; numerical Green-function evaluation is mathematics.'),
(13,'KEEP',[VI],'theory','Current through a checkerboard composite conductor','All eight cubes, two conductivities, contacts and voltage are supplied in the source and figure. Ordinary local Ohm law and interface continuity determine effective conductance without an unsupplied composite-material law.'),
(14,'KEEP',[VII],'theory','Magnetic field of a chord current with spherical-shell return','A straight internal current and the thin spherical conducting return define conventional magnetostatic sources. Surface Ohm/continuity and Biot-Savart determine interior/exterior fields under a uniform-shell idealization.'),
(15,'KEEP',[VII],'theory','Magnetic field from a rotating explicitly defined charge sheet','The exact density and angular speed were checked in the intact formula render. Current density and Biot-Savart superposition determine the field and limiting properties; special-function integration is mathematics.'),
(16,'BORDERLINE',[],'theory','Anisotropic-light relativity from partially specified kinematic postulates','Unequal invariant light speeds and the relativity principle are stated, supporting linear-map/group and wave-equation mathematics. Ruler/clock normalization, simultaneity and transformation conventions are not operationally supplied; self-contained derivation versus assumed Lorentz theory remains uncertain.'),
(17,'REJECT',[],'theory','Physical eigenstructure of a relativistic electromagnetic tensor','One tensor derivative formula is given, but Lorentz metric/index conventions and the physical meaning of tensor eigendirections are not. They are central to interpreting the spectrum and singular cases, beyond a purely specified finite matrix exercise.'),
(18,'REJECT',[],'theory','Relativistic scalar-gravity fall with rapidity and proper time','A four-force equation is supplied, but four-velocity normalization, proper/coordinate-time relations, rapidity and relativistic momentum definitions are not. These control every trajectory and impact comparison.'),
(19,'BORDERLINE',[I,IV],'theory','Local thermometer/force-gauge test of gravity versus acceleration','The equivalence statement is supplied, but the intended thermal or finite-laboratory effect is not. A quantum acceleration-temperature interpretation requires an unsupplied specialized law; a classical environmental/tidal interpretation differs materially. No worked solution resolves the intended mechanism.'),
(20,'REJECT',[],'theory','Relating static-metric geodesics to a classical-looking Lagrangian','Metric conditions alone do not supply geodesic connection, coordinate/proper-time transformation or covariant action dynamics. These GR prerequisites centrally determine the requested Hessian/potential and external-field extension.'),
(21,'REJECT',[],'theory','Charged-shell rescue inside a Schwarzschild/Reissner-Nordstrom horizon','The line element is supplied, supporting a horizon-root substep, but shell/free-fall geodesics, clock normalization and causal escape dynamics are not. Those unsupplied GR rules dominate the complete three-part task.'),
(22,'REJECT',[],'theory','Kerr black-hole traversal and outgoing particle images','Kerr metric, conserved-quantity geodesic equations and frame/image rules are not supplied. They are the entire central spacetime model despite the prose description of an extended geometry.'),
(23,'REJECT',[],'theory','Cohesive energy scaling with atomic coordination','No electronic bonding/tight-binding model or second-moment relation is supplied. A square-root coordination law is not a general consequence of ordinary pair-bond energy and centrally requires a specialized solid-state model.'),
(24,'BORDERLINE',[XI],'theory','Uncertainty saturation for two noncommuting Hermitian matrices','The finite matrices and normalized-vector task support ordinary linear algebra, but the relevant variance/commutator inequality is only named. Model sufficiency depends on whether that unsupplied quantum uncertainty rule is assumed; no dynamics is requested.'),
(25,'KEEP',[],'theory','Scattering and completeness for an explicitly supplied delta-potential PDE','The complete time-dependent equation is supplied, as is the wavefunction norm probability interpretation for loss. Stationary separation, distributional matching, spectral completeness and continuity/flux derive reflection/transmission and complex-coupling behaviour through mathematics, without importing an unsupplied quantum evolution law.'),
(26,'REJECT',[],'theory','Five-site quantum tunnelling dynamics and relocation probability','The Hamiltonian action fully supplies a finite eigenproblem, but the central later wavefunction evolution and time to reliably change site need unsupplied Schrodinger/unitary evolution and measurement rules. Whole-problem REJECT; the mathematical opening is not separately rescued.'),
(27,'REJECT',[],'theory','Entangled-spin versus classical-mixture analyzer correlations','State notation and outcome labels do not supply rotated-spin projection/Born probability or reduction rules. These central quantum measurement prerequisites determine every requested minimum and setting; no numerical correlation law is provided.'),
(28,'KEEP',[],'theory','Probability evolution from explicitly supplied Gaussian stochastic updates','Full Q28 spans pp7-8 and defines drift, Gaussian noise measure, Ito and midpoint update rules and the target PDE. Finite Gaussian integration and a continuum Taylor expansion establish the probability equation; specialized physical Brownian assumptions are not needed.'),
(29,'REJECT',[],'numerical','Large-N quantum-field self-energy and renormalization diagrams','The scalar Lagrangian is given but diagram/propagator rules, Wick rotation, counterterm scheme and quantum loop expansion are not. These central QFT prerequisites dominate every requested graph, plot and conclusion.'),
(30,'KEEP',[],'numerical','Optimization of a fully specified toy adaptive investment map','Complete Q30 spans pp8-9 and gives stochastic returns, wealth map, bounded adaptive update and ranking score. Probability/simulation/optimization are mathematics; no real financial-market theory is necessary. Hidden rival and unspecified probability-path ensemble affect unique optimum, not physics scope.'),
(31,'KEEP',[IV,XI],'theory','Apparent infrared sky temperature from a supplied absorption-column model','The spectral band, homogeneous vapour column and fixed attenuation length are supplied. Ordinary thermal radiation, absorption/emission balance and spherical path geometry determine angle-dependent brightness temperature and curvature error under explicit atmospheric-temperature assumptions.')]
pages=[1,1,1,1,1,2,2,2,2,3,3,3,4,4,4,4,4,5,5,5,5,6,6,6,6,6,7,7,8,8,9]
endpages={9:3,26:7,28:8,30:9};units={int(r['problem_number']):r for r in c.execute('select * from units where source_file_id=3125')};assert len(units)==31
out=[]
for n,d,dom,fmt,physics,reason in rows:
 u=units[n];assert u['decision'] is None
 out.append(dict(screening_unit_id=u['screening_unit_id'],decision=d,confidence='medium' if d=='BORDERLINE' else 'high',primary_spho_domains=';'.join(dom),required_physics=physics,decision_reason=reason,external_physics_if_any=physics if d in ('BORDERLINE','REJECT') else '',format=fmt,page_start=pages[n-1],page_end=endpages.get(n,pages[n-1]),visual_inspection_used=1,solution_used=0,boundary_status='content_boundary_verified',needs_second_review=n in (6,25,26,28,31),evidence=f'Complete actual Ortvay 2015 Q{n}, physical pp{pages[n-1]}-{endpages.get(n,pages[n-1])}, read from verified SHA cache and full renders. All nine physical pages inspected; Q9,Q26,Q28,Q30 continuations preserved within parent tasks. Diagrams and intact operator/metric/PDE formulas checked. No acquired worked solution or organizer-archive solution link found.'))
p=w.ROOT/'reviews/shutdown_ortvay_2015_31.json';w.writejson(p,out);w.decisions(p)
c.execute("update paper_boundary_audit set status='full_paper_boundaries_verified',observed_units=31,evidence=?,checked_at=? where file_id=3125",('All nine physical pages read and visually inspected: exactly Q1-Q31; Q9,Q26,Q28,Q30 span page boundaries without adding tasks. No omitted experimental/MCQ/short-answer task. Figures and all lettered clauses remain under printed parent numbers.',w.now()))
notes={1:'Shadow-free interpretation is no projected shadow outside the owned site; sunlight directions and solar-elevation cutoff are explicit constraints.',14:'Uniform shell conductivity/contact idealization is not stated numerically; quantitative return-current distribution needs it.',15:'Rigid infinite rotating sheet has unbounded rim speed and may be physically unrealizable; the specified steady mathematical current density still defines ordinary magnetostatics.',16:'Light-cone asymmetry and relativity principle given, but coordinate synchronization/normalization conventions not fully operationally defined.',19:'Thermal mechanism is not specified; equivalence principle alone does not supply an acceleration-temperature or horizon-radiation relation.',24:'Heisenberg inequality is named without its expectation/variance/commutator expression.',25:'Probability interpretation and time evolution PDE are actually supplied; complex gain/loss spectral completeness requires mathematical care and is not silently treated as Hermitian.',26:'Finite Hamiltonian action is supplied but time evolution law is not; Q25 elsewhere in the paper is not assumed to provide a model for this independently numbered question.',30:'Hidden active competitor and probability-path law prevent a uniquely specified expected-score optimizer. Retain complete toy model and this source limitation; do not supply real investment advice.',31:'Printed optical depth has units of length (5000 m), suggesting attenuation length. Temperature profile, band response and exact camera calibration are not specified; brightness temperature depends on them.'}
for n,note in notes.items():c.execute('update units set source_quality_notes=? where screening_unit_id=?',(note,units[n]['screening_unit_id']))
c.commit();print('Saved 31 explicit decisions and nine-page boundary audit.')
