"""Explicit source judgements after complete nine-page inspection."""
import workflow as w
c=w.connect();I='I_force_motion';II='II_oscillations_waves';III='III_ideal_gas';IV='IV_thermodynamics';VI='VI_electric_field';IX='IX_em_oscillations_waves';X='X_wave_optics';XI='XI_quantum_light'
rows=[
(1,'KEEP',[I],'experimental','Rolling inertia as a measurement of a supplied mass-scaling exponent','The statement operationally defines m(r)=k*r^D and gives rolling speed/height measurements. Rotational energy and radial mass integration infer D under the stated averaged spherical model. Fractal terminology introduces no external physical law.'),
(2,'KEEP',[I],'data_analysis','Optimal acceleration-limited roundabout travel and measured map radii','The circular ramp geometry, speed and acceleration limits are explicit. Tangential/normal acceleration, integration and optimization determine delay; map radii are ordinary measurements.'),
(3,'KEEP',[I],'theory','Frictional motion under a moving taut-rope constraint','Newtonian tension, sliding friction and the fixed rope length determine the driven motion; speed dependence requires mathematical differential equations.'),
(4,'BORDERLINE',[I],'theory','Returning boomerang through gyroscopic and aerodynamic torques','Gyroscopic turning is ordinary rigid-body mechanics, but the simplified trajectory alone does not specify blade lift or its dependence on rotation/throw parameters. Aerodynamic model sufficiency is uncertain; neither a lift law nor a worked solution is supplied.'),
(5,'KEEP',[I],'theory','Geometric-mass collision chain with supplied restitution convention','The pendulum/holder drawing and center-of-mass velocity restitution definition were inspected. Momentum and elastic/inelastic collision energy determine the amplification and optimal number.'),
(6,'REJECT',[I,II],'theory','Release and bending dynamics of a locally displaced elastic rod','Linear elasticity and rapidly decaying transverse waves are mentioned, but bending stiffness, moment-curvature relation and beam/contact dynamics are not supplied. These deformable-rod prerequisites centrally determine the release impulse and fall direction.'),
(7,'BORDERLINE',[I,II],'theory','Satellite-droplet ring produced by impact on a table','The actual photo shows the central drop and separate satellite ring. Momentum and surface energy support scaling, but crown breakup, droplet launch and impact/wetting assumptions are not supplied. The intended mechanism and necessary model remain genuinely ambiguous.'),
(8,'KEEP',[I,III],'theory','Stationary capillary bubble in centrifugal hydrostatic pressure','Slow spin-up and stationary final shape avoid an unsupplied fluid transient. Rotating-frame hydrostatics, gas pressure-volume balance and surface-tension force balance determine the interface and size. Nonlinear curvature geometry is mathematics.'),
(9,'KEEP',[I],'theory','Skipping-stone dynamics with an explicitly supplied hydrodynamic force','The rendered immersed-area, normal and tangent geometry and full lift/friction force are supplied. Newtonian impulse, energy and repeated-flight dynamics suffice without importing a specialized water-impact law.'),
(10,'KEEP',[I],'theory','Rain-induced car power losses from momentum and energy transfer','Additional rain interception, acceleration of collected water and water displacement losses can be estimated using mass flux, momentum and mechanical work. Empirical numerical parameters are inputs, not new required physics.'),
(11,'KEEP',[III,IV],'numerical','Air-well condensation estimates from heat and water-vapour budgets','The task asks realistic estimates rather than an exact transport solution. Vapour saturation, latent heat, airflow/diffusive supply and cooling energy set yields and interaction scales. Ordinary gas kinetic/thermal reasoning permits explicit approximation choices; climate/geometry inputs are not specified.'),
(12,'KEEP',[IV],'theory','Different mechanical behaviour of glacier and frozen sea ice','Salt rejection and trapped brine/porosity during ordinary freezing explain the qualitative contrast. No quantitative fracture or specialized crystal constitutive law is requested.'),
(13,'KEEP',[III,IV],'theory','Condensation versus deposition when cooling argon and carbon dioxide','Ordinary phase-path reasoning explains flowing condensed argon collecting before freezing, versus carbon-dioxide deposition along the cold tube. The different melting/phase properties are material data, not a new specialized theory.'),
(14,'KEEP',[IV],'theory','Maximum heating of one of three isolated finite heat reservoirs','First-law energy conservation and entropy/Carnot constraints for constant heat capacities decide the attainable temperature. Engines and refrigerators introduce ordinary thermodynamics only.'),
(15,'REJECT',[IV],'theory','Constructing mixture free energy from a closed miscibility gap','The rendered concentration-temperature ellipse is supplied, but chemical-potential equality and the common-tangent phase-separation construction are not. These specialized binary-mixture thermodynamic rules are central to the sole free-energy reconstruction task.'),
(16,'REJECT',[],'theory','Defect-free semiconductor epitaxial-film critical thickness','Crystal lattice mismatch, strain/dislocation energy and the critical-thickness model are unsupplied. They determine the entire silicon-on-GaAs thickness bound; ordinary energy conservation cannot specify their constitutive relations.'),
(17,'KEEP',[X],'theory','Finite-aperture lens image of an extended nearby cylinder','Lens power, aperture, eye distance and cork dimensions fully specify paraxial ray construction and visibility. The requested scaled drawing is conventional geometric optics.'),
(18,'KEEP',[X],'numerical','Ray envelopes of sunlight reflected from a sinusoidal water surface','The stationary sinusoidal reflecting geometry and illumination direction are supplied. Reflection and envelope differentiation locate caustics, singularities and parameter dependence without a fluid-wave model.'),
(19,'KEEP',[VI,X],'theory','Electrostatic wedge capacitor with supplied anisotropic dielectric axes','The render defines the wedge and principal axes. A linear permittivity tensor is specified; electrostatic potential, D divergence and dielectric energy define the field problem. Coordinate rescaling and field-line integration are mathematics.'),
(20,'KEEP',[I,VI],'theory','Charged and neutral metal-sphere elastic collision','Conducting-sphere induction, charge redistribution at contact, energy and momentum determine the separated velocities under the printed ideal elastic assumption. No advanced microscopic metal model is required.'),
(21,'KEEP',[VI],'theory','Optimizing a surface dipole field under a fixed-area constraint','The dipole direction at every surface point is explicitly defined. Ordinary electrostatic dipole superposition and geometric optimization determine the field, including possible lack of a finite optimum without a distance constraint.'),
(22,'REJECT',[],'theory','Retarded image of a relativistic transverse light beam','Lorentz aberration and relativistic emission-frame transformations are not supplied. They centrally determine the visible dust-scattered beam and apparent image.'),
(23,'REJECT',[],'theory','Relativistic photon absorption and electron-positron production threshold','Unit conventions alone do not supply relativistic energy-momentum dispersion, frame transformations or invariant reaction constraints. Those prerequisites control all four linked parts.'),
(24,'REJECT',[],'theory','Proper-time fuel consumption and relativistic rocket spacetime reach','Exhaust speed and fuel rate are specified, but relativistic rocket momentum balance, proper-time transformation and worldlines are not. All requested spacetime/fuel results rely on them.'),
(25,'REJECT',[],'theory','Electromagnetic modes inside a relativistically moving dielectric','Rest dielectric constants are given, but Lorentz transformations of fields and moving-medium constitutive relations are not. These outside-scope dependencies centrally determine the requested E,D,B,H modes.'),
(26,'KEEP',[],'theory','Domain error in a supplied differential-operator square','The wavefunction, differential Hamiltonian and two conflicting expectation expressions are explicit. Normalization and operator boundary-domain analysis resolve the apparent contradiction: the first derivative application leaves the hard-wall operator domain. No unsupplied quantum dynamical or measurement law is needed.'),
(27,'BORDERLINE',[XI],'theory','Angle-angular-momentum uncertainty on a periodic quantum domain','Angular-momentum quantization is within the stated light/atomic scope, but the periodic angle operator and modified uncertainty/domain rule are not supplied. Whether elementary quantization plus periodic probability suffices for the intended explanation is unresolved.'),
(28,'REJECT',[],'theory','Exact oscillator-two-level quantum time evolution beyond rotating-wave approximation','The Hamiltonian is supplied, but ladder-operator action, quantum oscillator/coherent states and unitary time-evolution rules are not. These central prerequisites cannot be replaced by ordinary finite-matrix algebra.'),
(29,'BORDERLINE',[X,IX],'theory','Pulse group velocity in a pumped two-line gas','The two-transition diagram, linewidth limit and classical-oscillator permission support ordinary dispersion. However pumping-to-population/oscillator-strength and gain parameters are not operationally specified, leaving ambiguity over the central two-line susceptibility model and numerical group velocity.'),
(30,'BORDERLINE',[],'theory','Short-time purity constraint under a supplied quantum master equation','The full evolution equation, variance, purity bounds and thermal length are supplied. Much work is trace algebra, but the canonical position-momentum commutator needed for the friction contribution is not stated. Supplied-model sufficiency remains uncertain rather than treating the quantum label alone as rejection.'),
(31,'REJECT',[],'theory','Covariant weight of a charged orbiting particle in Schwarzschild gravity','Some background field tensors are supplied, but the metric, covariant particle equation/geodesic connection and gravitational force interpretation are not. These central GR prerequisites are necessary for support and covariant weight.'),
(32,'REJECT',[],'theory','Ideal-gas balloon deformation at a black-hole horizon','Ordinary gas laws are insufficient: the metric/tidal field, falling-frame dynamics and horizon deformation model are unsupplied. They determine the pressure/temperature distribution requested.'),
(33,'KEEP',[I,II],'theory','Gravity-tunnel periods for fully specified alternative Earth shapes','The five geometries and uniform-density assumptions were checked in the full-page drawing. Newtonian laws are explicitly retained; gravity integration, energy and travel-time quadrature give each return time. Fictional context adds no specialized physics.')]
pages=[1,1,1,2,2,2,2,3,3,3,4,4,4,4,4,5,5,5,5,6,6,6,6,6,7,7,7,7,7,8,8,9,9]
units={int(r['problem_number']):r for r in c.execute('select * from units where source_file_id=3122')};assert len(units)==33
out=[]
for n,d,dom,fmt,physics,reason in rows:
 u=units[n];assert u['decision'] is None
 out.append(dict(screening_unit_id=u['screening_unit_id'],decision=d,confidence='medium' if d=='BORDERLINE' else 'high',primary_spho_domains=';'.join(dom),required_physics=physics,decision_reason=reason,external_physics_if_any=physics if d in ('BORDERLINE','REJECT') else '',format=fmt,page_start=pages[n-1],page_end=pages[n-1],visual_inspection_used=int(pages[n-1] in {2,3,4,5,7,8,9}),solution_used=0,boundary_status='content_boundary_verified',needs_second_review=n in (8,11,19,26),evidence=f'Whole printed Ortvay 2018 Q{n}, physical p{pages[n-1]}, read from verified SHA cache. Full renders pp2-5,7-9 inspected for photos, force vectors, phase diagram, capacitor, operator formulas and Earth shapes. All nine physical pages audited for Q1-Q33; internal letters retained. Only statement file is acquired; organizer archive https://ortvay.elte.hu/main.html lists no 2018 worked solutions.'))
p=w.ROOT/'reviews/shutdown_ortvay_2018_33.json';w.writejson(p,out);w.decisions(p)
c.execute("update paper_boundary_audit set status='full_paper_boundaries_verified',observed_units=33,evidence=?,checked_at=? where file_id=3122",('Complete nine-page statement inspected: exactly Q1-Q33. Page9 contains complete Q32 and Q33; no omitted experiment, MCQ or independently numbered supplemental task. Photo/diagrams are within parent questions.',w.now()))
notes={1:'Inferring D from whole-ball inertia assumes the stated statistically averaged radial mass-scaling model adequately represents the ball; this is an approximation, not a fractal constitutive law.',2:'Google Maps radius sampling is an open measurement extension, not a fixed missing problem dataset.',11:'Geometry, weather, humidity and cooling mechanism are unspecified. Numerical country estimates require explicit realistic assumptions; no unique data set is supplied.',13:'Phase-transition material constants are not numerically supplied; only a qualitative explanation is requested.',19:'Permittivity tensor axes are supplied symbolically; no numerical principal values are given. Optical indices need not uniquely determine static permittivity, so retain a symbolic electrostatic answer.',20:'Charge equilibration at ideal elastic metal contact may dissipate electrical energy; the intended collision idealization needs to be stated rather than silently assuming total energy conservation through dissipative contact.',21:'No minimum distance from x or restriction on surface topology is supplied; field may be unbounded under concentration near x.',26:'Rendered Hamiltonian coefficient appears to use hbar rather than hbar squared. Overall positive coefficient does not alter the domain contradiction; source typo retained.',29:'Line strengths, steady pumped populations and pumping strength are not specified. Classical oscillator permission alone does not fix the susceptibility amplitude.',30:'Printed master-equation normalization also lacks conventional mass/hbar factors in the Hamiltonian term. Purity commutator contribution is insensitive to that term, but canonical [x,p] rule is unsupplied.'}
for n,note in notes.items():c.execute('update units set source_quality_notes=? where screening_unit_id=?',(note,units[n]['screening_unit_id']))
c.commit();print('Saved 33 explicit decisions and complete nine-page boundary audit; focused checks queued.')
