"""Explicit 2019 reviews, committed as two small durable batches."""
import sys
import workflow as w
c=w.connect();I='I_force_motion';II='II_oscillations_waves';III='III_ideal_gas';IV='IV_thermodynamics';VI='VI_electric_field';VII='VII_magnetic_field';VIII='VIII_induction';IX='IX_em_oscillations_waves';X='X_wave_optics';XI='XI_quantum_light'
rows=[
(1,'KEEP',[I,II],'theory','Gravity-gradient torque and torsional pendulum period','The exact asymmetric-height balance drawing, wire torsion constant and small-size assumptions are supplied. Newtonian torque and rotational inertia give the period.'),
(2,'KEEP',[I],'experimental','Optimizing gravitational torque in a Cavendish-type balance','The physical instrument drawing and ball separations/heights determine all force lever arms. Newtonian gravity and numerical angle optimization suffice.'),
(3,'BORDERLINE',[I,II,III],'theory','Molecular-size estimate inferred from capillary-wave scaling','Wave scaling and one speed/wavelength pair are given, but the molecular surface-energy relation needed to infer a molecular length is not. Eotvos law is mentioned without a usable formula. A heuristic thermal estimate may be intended; model/prerequisite sufficiency is genuinely uncertain.'),
(4,'KEEP',[I,II],'theory','Pendulum timing under spheroidal gravity and centrifugal acceleration','All three geometric/rotational effects are described. Ordinary gravity integration and pendulum frequency quantify their contributions, with numerical Earth parameters treated as measurement inputs.'),
(5,'KEEP',[I],'theory','Newtonian elliptic projectile orbit and trajectory envelope','Inverse-square gravity, energy and angular momentum determine orbit parameters, travel time and highest point. Envelope differentiation and launch optimization are mathematics; all five parts remain one task.'),
(6,'KEEP',[I],'theory','Aircraft landing, suspension and slipping-wheel spin-up','Given masses, spring compression, friction and touch-down motion define Newtonian suspension forces and wheel angular impulse. Wear energy is frictional work, without an unsupplied tyre model.'),
(7,'KEEP',[I],'theory','Two-mass motion with a string bent around a fixed nail','String-length constraints, conservation laws and Newtonian tensions determine trajectories. The point-nail limit adds no specialized physical theory.'),
(8,'KEEP',[I],'theory','Rigid spoke-wheel rotation and contact impulses on a slope','Uniform rod inertia, gravitational torque, no-slip reactions and successive impacts determine the friction threshold. Rimless construction is an ordinary rigid-body model.'),
(9,'KEEP',[I],'theory','Alternating constrained ski motion and center-of-mass dynamics','The actual ski/track photographs and longitudinal/transverse friction assumptions were inspected. Newtonian balance, step timing and geometry determine slope limits and speed.'),
(10,'KEEP',[I],'theory','Angular-momentum redistribution when ocean circulation stops','Conserving Earth-plus-ocean angular momentum relates circulation to rotation period. A numerical estimate requires flow masses and velocities, but the required physical law is ordinary rotational mechanics, not oceanographic dynamics.'),
(11,'KEEP',[I],'theory','Torque-free rigid-body motion in four Euclidean dimensions','The task changes the mathematical dimension, not the Newtonian laws. Rotation matrices, kinetic energy and conserved angular momentum generalize the rigid-body equation; SO(4) algebra and visualization are mathematical difficulty. No relativistic or quantum theory is requested.'),
(12,'KEEP',[II],'theory','Impedance matching at the end of a taut massive rope','Transverse string wave speed follows from tension and mass density. The end force proportional to velocity cancels reflection at matched wave impedance; no unsupplied material constitutive law is needed.'),
(13,'REJECT',[II],'theory','Damped flexural modes of an elastic cantilever','Viscous stress proportional to strain rate is stated, but the elastic bending moment law, beam dynamical equation and clamped/free stress conditions are not. Unsupplied deformable-beam mechanics centrally determines every mode/frequency/quality factor.'),
(14,'KEEP',[II,III],'theory','Refraction and a sound shadow in an atmospheric temperature gradient','Ordinary sound propagation and temperature-dependent ideal-gas sound speed explain sudden audibility. The elevation estimate needs atmospheric-profile assumptions, which are measurement/model parameters rather than a new physical theory.'),
(15,'KEEP',[X],'theory','Apparent depth and astigmatic ray geometry in a supplied index profile','The fixed known n(z), two viewing-ray arrangements and depth are supplied. Snell refraction and local ray convergence determine the differing apparent depths; salt chemistry is irrelevant.'),
(16,'KEEP',[X],'theory','Total internal refraction geometry at a sinusoidal water surface','Sinusoidal wave slopes, illumination and the stated angular measurements define ordinary Snell/critical-angle geometry. Time-varying surface normals explain the dark angular region without fluid-wave dynamics.'),
(17,'KEEP',[X],'theory','Inverse reflecting-surface design for a specified caustic','The statement defines caustic as the ray envelope. Reflection geometry and differential envelope equations determine mirror shapes, including semicircle/heart examples; no specialized optical law is missing.'),
(18,'KEEP',[I,IV,XI],'numerical','Radiative heating from a supplied random stellar population','Spatial/mass distributions and mass-luminosity law are explicit, and gas/lensing are excluded. Inverse-square light flux, blackbody energy balance and sampling determine the thermal/probability estimates; no stellar-evolution or GR model is required.'),
(19,'KEEP',[III,IX,XI],'theory','Single-scattering sky brightness from driven small dipoles','The small-particle and single-scattering limits are explicit. Ordinary Maxwell dipole radiation, blackbody spectral illumination and ideal-gas hydrostatics supply the physical route to angular and wavelength dependence. Molecular polarizability/pressure inputs needed for an absolute numerical scale are source-quality omissions, not an assumed unsupplied quantum scattering law.'),
(20,'KEEP',[IV,XI],'numerical','Rotating-solid heat conduction with blackbody boundary radiation','Density, heat capacity, conductivity, rotation and beam intensity supply a conventional thermal model. Local energy balance with Fourier conduction and Stefan-Boltzmann boundary power defines the PDE; its spherical numerical solution is mathematical work.'),
(21,'KEEP',[IV],'numerical','Steady Fourier heat conduction under a specified laser source','Gaussian radial heating, exponential penetration, conductivity and linear boundary heat transfer are all explicitly given. Energy balance defines the temperature boundary problem; solving it adds mathematics rather than new laser/material physics.'),
(22,'KEEP',[III,IV],'theory','Quasistatic gas compression through alternating piston/thermal constraints','The apparatus render confirms alternating fixed conducting and freely moving insulating walls. Ideal-gas pressure balance, heat exchange and first law determine every section and piston displacement.'),
(23,'BORDERLINE',[III,IV,VI],'theory','Thermal extension of charged elastic hairs near a dipole skin','The skin dipole density and hair idealization are supplied, but surface geometry and a nonzero force-producing departure from an ideal homogeneous dipole layer are not. That missing field model changes the claimed repulsion. No solution clarifies whether a discrete/local model is intended.'),
(24,'KEEP',[III],'theory','Long-time ideal-gas pressure measurement in a rarefied sphere','The sensor collision rule and long averaging time are explicit. Molecular kinetic momentum transfer and equilibrium sampling determine pressure; finite mean free path does not require a specialized detector theory.'),
(25,'BORDERLINE',[II,IV],'theory','Thermal rotor coupled to an unspecified harmonic bath','The pendulum and oscillator-environment hint support classical dynamics, but coupling, bath spectrum and thermal noise/low-temperature prescription are not supplied. Classical statistical and quantum open-system interpretations differ materially; the intended model is unresolved.'),
(26,'KEEP',[VI],'theory','Point-dipole electrostatic field-line integration','Ordinary dipole field components and the tangent-to-field condition yield the curve; choosing coordinates is a mathematical simplification.'),
(27,'KEEP',[VI],'theory','Electrostatic equilibrium on a Cornu-shaped conductor','Equipotential boundary conditions and Coulomb field/charge relationships define the charge-distribution problem. Cornu-spiral coordinates and singular-boundary analysis are mathematics, not specialized new electrostatics.'),
(28,'KEEP',[I,III,VI],'theory','Capacitance and screening of a conducting shell containing rotating gas','For an enclosing spherical conductor in electrostatic equilibrium, its exterior potential/total charge determine capacitance independently of neutral gas inside. Polarizability and centrifugal gas density do not introduce an outside prerequisite; the solid/filled wording is flagged.'),
(29,'KEEP',[VI],'theory','Ohmic surface-current potential on a cylindrical shell','The actual A/B injection and C/D voltage geometry were checked. Unfolding/periodic coordinates, local Ohm law and current continuity define the surface potential; no specialized material model is needed.'),
(30,'KEEP',[VI,IX],'theory','Multipole radiation of rotating Platonic charge distributions','Nonrelativistic motion and exact charge/axis geometry are supplied. Symmetry of ordinary electromagnetic sources and a long-wavelength Maxwell expansion determine the first nonzero moment and frequency power; multipole algebra is mathematical difficulty.'),
(31,'KEEP',[VII],'theory','Biot-Savart interaction of skew infinite current wires','Wire geometry and currents are fully specified. Magnetic force integration yields the skew result and parallel limit; singular infinite-length limits are mathematical, not new physics.'),
(32,'KEEP',[VI,VII],'experimental','Inferring an elliptical wire from resistance and magnetic measurements','Uniform resistance per length, known applied voltage and available meters define the measurement task. Ohm/Biot-Savart laws and geometric calibration determine the ellipse; experimental design is eligible.'),
(33,'KEEP',[IX],'theory','Maxwell integral constraints in a supplied periodic three-dimensional space','The glued-face cube operationally defines the torus. Integrating Ampere-Maxwell over a periodic cross section forces displacement-field growth for net winding current; additional manifolds are mathematical generalizations. de Rham theory is a suggested mathematical aid, not indispensable outside physics.'),
(34,'REJECT',[],'theory','Relativistic wheel photograph with retardation','Lorentz transformation and simultaneous/retarded rotating-point kinematics are unsupplied and central to the whole image. Classical limit does not dominate the requested relativistic result.'),
(35,'REJECT',[],'theory','Relativistic proper-acceleration rocket and mass consumption','Exhaust speed and acceleration are specified, but proper-time worldlines, relativistic momentum balance and photon-rocket limit laws are not. These control every travel and fuel result.'),
(36,'REJECT',[],'theory','Relativistic absorption and pair-production kinematics','Dark-photon rest mass alone is insufficient: unsupplied relativistic energy-momentum relations and reaction constraints control the entire maximum-velocity task. No given nuclear mass-energy relation replaces those dependencies.'),
(37,'REJECT',[],'theory','Relativistic hydrodynamic shear tensor','Relativistic stress projection, four-velocity derivatives and constitutive shear definitions are unsupplied. They are the sole physical method requested in both dimensional cases.'),
(38,'REJECT',[],'theory','Lorentz-tensor eigenstructure of electromagnetic stress energy','Energy-momentum and field-strength tensor definitions/physical Lorentz interpretation are not supplied. Understanding their degenerate eigenvectors centrally requires specialized relativistic field formalism.'),
(39,'REJECT',[],'theory','Nonlinear Lorentz-invariant electrodynamics from a field Lagrangian','The Lagrangian is supplied, but deriving material equations via tensor field variation and wave characteristics is not. Those specialized dependencies control the new theory; ordinary Maxwell equations cannot be substituted.'),
(40,'REJECT',[],'theory','Iterative tensor-gravity action and Einstein-Hilbert self-coupling','The starting schematic equation/action is given, but covariant stress tensor, gravitational self-coupling and Einstein-Hilbert metric theory are not. These are the central physical machinery.'),
(41,'REJECT',[],'theory','Friedmann cosmological dynamics and stability','The actual cosmological evolution equations are named rather than supplied. Unsupplied Friedmann/GR relations control all phase-space curves; coordinate definitions alone do not give an evolution model.'),
(42,'REJECT',[],'theory','Gravitational-wave orbital radiation and inspiral','No gravitational-radiation quadrupole/power law is supplied. This specialized GR relation is central to every emitted-energy and inspiral estimate.'),
(43,'REJECT',[],'theory','Quantum coordinate-momentum Hamiltonian and evolution operator','The operator matrix is given, but x/p commutators, oscillator representation and quantum time evolution are not. Numeric matrix diagonalization alone cannot solve an operator-valued Hamiltonian or the evolution task.'),
(44,'BORDERLINE',[],'theory','Finite branched hopping-graph spectrum with an implicit quantum model','The star graph and uniform onsite/hopping data suggest a finite matrix spectrum solvable by linear algebra. However the hopping-to-Hamiltonian amplitude rule is not explicitly defined; it is unclear whether a self-contained matrix model or unsupplied tight-binding interpretation is assumed. No solution is present.'),
(45,'REJECT',[],'theory','Scale symmetry followed by canonical quantization and singular quantum states','Classical scaling is a mathematical opening, but the dominant later work requires unsupplied Noether/canonical operator machinery, Schrodinger states and quantum probability current near a singular potential. Whole-problem REJECT.'),
(46,'REJECT',[],'theory','Quantum phonon thermodynamics and fractal magnetic order','A scalar spring equation and spin pair energy are given, but low-temperature phonon occupation/Debye quantization and critical spectral-dimension physics are not. These central prerequisites dominate over the classical mode-building step.'),
(47,'REJECT',[],'theory','Many-electron coupling to a quantized electromagnetic mode','Hamiltonian and vector-potential mode expression are given, but photon creation-operator algebra, oscillator-state construction and quantum minimal-coupling diagonalization are not. They are structurally required for eigenstates.'),
(48,'REJECT',[],'theory','Acceleration-dependent quantum-field entanglement near a horizon','Vacuum decomposition is supplied, but excited-mode transformation, tracing inaccessible Rindler regions and the entanglement measure are not. Those quantum-field/information concepts control the sole requested result.'),
(49,'REJECT',[],'theory','Two-particle-irreducible quantum-field effective potential','Functional and auxiliary Lagrangians are supplied, but Feynman diagram rules, propagator expansion and large-N order counting are not. They centrally determine all requested diagrams and elimination.'),
(50,'KEEP',[I],'theory','Forced geostationary motion, escaping exhaust and rising altitude','The complete narrative spans pp16-17. Newtonian gravity, rotating-frame force balance, rocket momentum and escape-energy conditions determine the limiting altitude/time. Geosynchronous/escape formulas follow from ordinary mechanics; no relativity is asked.')]
pages=[1,2,2,3,3,4,4,4,4,5,5,5,5,5,5,6,6,6,7,7,7,8,8,8,8,8,9,9,9,9,10,10,10,10,11,11,11,11,12,12,12,13,13,13,13,14,14,15,15,16]
start,end=map(int,sys.argv[1:3]);assert (start,end) in ((1,25),(26,50))
units={int(r['problem_number']):r for r in c.execute('select * from units where source_file_id=3121')};assert len(units)==50
visual_pages={1,2,3,4,8,9,10,14,15};out=[]
for n,d,dom,fmt,physics,reason in rows:
 if not start<=n<=end:continue
 u=units[n];assert u['decision'] is None
 out.append(dict(screening_unit_id=u['screening_unit_id'],decision=d,confidence='medium' if d=='BORDERLINE' else 'high',primary_spho_domains=';'.join(dom),required_physics=physics,decision_reason=reason,external_physics_if_any=physics if d in ('BORDERLINE','REJECT') else '',format=fmt,page_start=pages[n-1],page_end=17 if n==50 else pages[n-1],visual_inspection_used=int(pages[n-1] in visual_pages),solution_used=0,boundary_status='content_boundary_verified',needs_second_review=n in (11,19,28,30,33),evidence=f'Complete actual Ortvay 2019 Q{n}, physical p{pages[n-1]}'+('-17' if n==50 else '')+' read from verified SHA-based text cache. Full-page renders pp1-4,8-10,14-15 inspected for diagrams, axes and damaged formula extraction. All seventeen physical pages audited for Q1-Q50 and omitted tasks. No acquired worked solutions accompany this paper. Internal letters remain inside each printed top-level question.'))
p=w.ROOT/f'reviews/shutdown_ortvay_2019_{start}_{end}.json';w.writejson(p,out);w.decisions(p)
c.execute("update paper_boundary_audit set status='full_paper_boundaries_verified',observed_units=50,evidence=?,checked_at=? where file_id=3121",('All seventeen physical pages read: exactly Q1-Q50, including Q50 continuation on p17. Anniversary preface and portrait do not add tasks. All figures and within-problem letters kept with their parent numbers; no unindexed problem found.',w.now()))
notes={10:'Numerical ocean angular momentum requires measured circulation masses/velocities, not supplied in the source.',14:'Numerical sound-shadow angle requires an atmospheric temperature profile; no unique profile is supplied.',18:'Visibility estimate requires a naked-eye flux threshold and mean-temperature approximation; stellar sampling law is supplied.',19:'Absolute Rayleigh brightness requires atmospheric density normalization and molecular optical polarizability, not numerically specified. Classical dipole-radiation route is recorded; no quantum scattering relation inserted into source.',23:'Ideal homogeneous dipole-layer interpretation has no exterior force; finite/discrete field geometry is unspecified. Model ambiguity retained as BORDERLINE.',27:'Cornu-shaped conducting body needs a chosen finite extent/thickness convention for quantitative normalization; source is geometrically idealized.',28:'Source says solid conductive sphere filled with gas; enclosing-shell electrostatic interpretation yields exterior screening independent of interior gas. Wording retained rather than silently corrected.',50:'Complete source problem is pp16-17; all dictator conditions belong to one Q50.'}
for n,note in notes.items():
 if start<=n<=end:c.execute('update units set source_quality_notes=? where screening_unit_id=?',(note,units[n]['screening_unit_id']))
c.commit();print(f'Saved explicit source judgements Q{start}-Q{end}; focused checks remain queued.')
