"""Source-inspected 2020 continuation, withdrawal and essential dataset."""
import json,math
import workflow as w
c=w.connect();I='I_force_motion';II='II_oscillations_waves';III='III_ideal_gas';IV='IV_thermodynamics';VI='VI_electric_field';VII='VII_magnetic_field';IX='IX_em_oscillations_waves';X='X_wave_optics';XII='XII_atomic_nuclear'
rows=[
(1,'KEEP',[],'theory','Integration of a fully supplied epidemic rate model','Both SIS differential equations, conserved population and interpretation of rates are supplied. Changing the prescribed rate numerically is mathematical modelling, with no epidemiological prerequisite.'),
(2,'KEEP',[II],'theory','Damped driven oscillator with linearly varying forcing amplitude','Ordinary oscillator equations, a sinusoidal driver and a stated linear amplitude change determine transient and long-time motion. Climate is an analogy, not an unsupplied climate model.'),
(3,'KEEP',[I,II],'experimental','Newtonian gravitational calibration through torsional oscillations','The actual lead-block/torsion-balance geometry and measured period relation are supplied. Gravitational integration, torque gradients and inertia determine calibration and its arm-length dependence.'),
(4,'KEEP',[I],'numerical','Quadratic-drag flights and energy-transfer recursion','The drag dependence and exact mass/energy transfer sequence are supplied. Newtonian ascent/descent energy and repeated recurrence determine the 101st speed.'),
(5,'KEEP',[II,IV],'data_analysis','Thermal energy balance, measured heating/cooling fits and thermostat response','The essential linked organizer measurements were retrieved and validated: 11 heating and 31 cooling time-temperature pairs. Ordinary heat capacity, thermal leakage and fitting determine neighbouring temperature, costs and daily phase response; no specialized building model is required.'),
(6,'KEEP',[I],'theory','Torque equilibrium of a tilted bucket and a liquid center of mass','The bucket photograph, cuboid dimensions, suspension/center-of-mass diagram and small-angle permission were inspected. Hydrostatic liquid geometry and gravitational torque determine the tilt.'),
(7,'KEEP',[I],'theory','Green kernel of the explicitly supplied Newton equation','The governing equation and convolution form are given. Two integrations with an appropriate causal/initial-condition choice produce the kernel; distribution/Green-function language adds mathematics.'),
(8,'KEEP',[I,IV],'theory','Energy dissipation during Newtonian spin-orbit tidal locking','Isolated angular momentum and circular orbital assumptions are explicit. Initial/final rotational and orbital energy give the dissipated fraction without needing a microscopic tidal constitutive law.'),
(9,'KEEP',[I],'theory','Tidal torque with an explicitly supplied delayed-deformation model','Constant response delay and deformation amplitude proportional to R^-3 replace unknown elasticity. Newtonian gravity-gradient torque and spin/orbit angular-momentum exchange determine all coupled equations.'),
(11,'KEEP',[II],'theory','Travel-time spread and sound propagation from an extended lightning channel','Ordinary sound speed, differing source distances and sound attenuation explain the initial clap and trailing murmur. No plasma or lightning-generation theory is required.'),
(12,'BORDERLINE',[I,II],'theory','Small displacement of a dense spherical core in surrounding fluid','Newtonian gravitational restoring and buoyancy forces are in scope, but the surrounding fluid inertia/boundaries and dynamical response are not specified. A rigid-body-only approximation versus an added-mass fluid model materially changes the equation; intended prerequisite/model balance is unresolved.'),
(13,'KEEP',[I,VII],'theory','Magnetic dipole interaction and collision time','The point-dipole approximation and fixed moment orientations are supplied. Magnetic potential energy and Newtonian radial travel determine the time in both orientations.'),
(14,'KEEP',[VI,IX],'theory','Ohmic charge relaxation in the stipulated merged conducting sphere','The unusual material/contact rule is explicitly supplied. Gauss law, charge continuity and Ohm current give a relaxation timescale; initial/final charge partition determines duration in terms of material parameters. No unsupplied semiconductor/contact microphysics is required.'),
(15,'KEEP',[IV],'theory','Entropy rise from mixing equal masses at different temperatures','Constant specific heat is stated. Energy balance determines equilibrium temperature and integrating dQ/T gives entropy relative to total heat capacity.'),
(16,'KEEP',[X],'theory','Diffraction amplitudes with supplied Gaussian slit randomness','Single-slit amplitude and phase sums across the grating, averaged with the stated Gaussian widths/spacings, determine the pattern. Statistical averaging is mathematics within ordinary diffraction.'),
(17,'KEEP',[X],'theory','Oblique-incidence diffraction orders and wavelength limits','Ordinary grating optical-path differences under rotation determine allowed directions and the two-order transmission window. Printed missing part b is a label gap, not an inferred task.'),
(18,'REJECT',[],'theory','Relativistic scalar-field orbit with changing invariant mass','The four-force equation is supplied, but four-velocity normalization, proper-time transformations and scalar rest-mass coupling are not. These specialized dependencies control every orbital-speed and time result.'),
(19,'REJECT',[],'theory','Quantum linear-potential eigenstates and semiclassical quantization','The potential and walls are stated; Schrodinger equation, quantum boundary interpretation and WKB quantization/wavefunctions are not supplied. They control all eigenenergy and wavefunction tasks.'),
(20,'REJECT',[],'theory','Squeezed oscillator-state dynamics after a frequency quench','Creation-operator algebra, coherent states, quantum evolution and overlap probabilities are unsupplied and central. Specifying a frequency multiplier alone does not provide those rules.'),
(21,'REJECT',[],'theory','Fermionic electron heat capacity using Sommerfeld expansion','Fermi occupation, density of states and Sommerfeld expansion are unsupplied. They are the sole method requested; ordinary ideal-gas heat capacity is insufficient.'),
(22,'KEEP',[IV,VII,XII],'theory','Adiabatic cooling of independent quantized magnetic dipoles','The independent-dipole model is explicit. Magnetic energy, quantized moment projections, Boltzmann populations and constant entropy imply temperature scaling with B. These are ordinary magnetization/statistical and atomic prerequisites, without an interacting quantum-spin formalism.'),
(23,'REJECT',[],'theory','Quantum lattice hopping and magnetic translation algebra','The hopping expressions and phase integrals are supplied, but creation/annihilation commutation rules and representation of magnetic quantum translations are not. They structurally control the requested commuting/group conditions.'),
(24,'REJECT',[],'theory','Free-particle peculiar velocity in an expanding cosmological metric','Only the scale factor is named. The spacetime metric, geodesic/redshifting momentum law and relativistic velocity relation are unsupplied; these are the central cosmological physics.'),
(25,'REJECT',[],'theory','Yukawa quantum-field renormalization and counterterm diagrams','Schematic diagram terms are supplied, but propagators, regularization, Feynman rules and spontaneous-symmetry-breaking renormalization are not. Those unsupplied QFT concepts control the sole substantive correction task.'),
(26,'KEEP',[I],'data_analysis','Depth-distribution statistics and density-weighted center of mass','The depth and density functions define area/volume/weight integrals. Probability densities, median definitions and center of mass are standard analysis; both bowl/bell cases remain inside this whole problem.'),
(27,'KEEP',[I,II],'theory','Inference of prism gravity from pendulum and orbital periods','The homogeneous density and comparative periods define Newtonian gravitational derivatives and local acceleration. Geometric integration and numerical shape inference require no new gravity model.'),
(28,'KEEP',[],'theory','Rank and probability under specified sign errors in linear equations','Gaussian elimination and rank perturbations analyze the supplied integer-matrix copying model. No physics prerequisite is inferred from the story; the probability ensemble needs explicit interpretation for a unique number.')]
pages={1:1,2:1,3:2,4:2,5:3,6:3,7:4,8:4,9:4,11:5,12:5,13:5,14:5,15:6,16:6,17:6,18:6,19:7,20:7,21:7,22:7,23:8,24:8,25:9,26:9,27:10,28:11}
units={int(r['problem_number']):r for r in c.execute('select * from units where source_file_id=3119')};assert len(units)==28 and len(rows)==27
# Validate downloaded original bytes before publishing the file/association.
dest=w.ROOT/'references/ortvay_2020_p05_data_EN.txt';part=dest.with_suffix('.txt.part')
payload=(dest if dest.exists() else part).read_text(encoding='utf-8');blocks={};current=None
for line in payload.splitlines():
 if not line.strip():continue
 if line.startswith(('heating:','cooling:')):current=line.split(':')[0];blocks[current]=[];continue
 pair=list(map(float,line.split()));assert len(pair)==2 and all(math.isfinite(x) for x in pair);blocks[current].append(pair)
assert len(blocks['heating'])==11 and len(blocks['cooling'])==31
assert all(all(a[0]<b[0] for a,b in zip(data,data[1:])) for data in blocks.values())
if not dest.exists():part.replace(dest)
reference=dict(reference_id='ortvay_2020_p05_data_EN',screening_unit_id=units[5]['screening_unit_id'],url='https://ortvay.elte.hu/2020/p05/p05_data_EN.txt',local_path=dest.relative_to(w.ROOT).as_posix(),sha256=w.digest(dest),byte_size=dest.stat().st_size,page_count=None,purpose='Essential original time-temperature data linked from physical statement p3 via https://ortvay.elte.hu/2020/p05/; verified 11 heating and 31 cooling pairs, finite values and increasing time axes.',acquired_at=w.now())
c.execute('insert into screening_references values (?,?,?,?,?,?,?,?,?)',tuple(reference.values()));c.commit();w.writejson(dest.with_suffix('.txt.provenance.json'),{**reference,'validation_status':'validated original data; numerical pair counts/time axes checked','statement_file_id':3119,'statement_sha256':units[5]['source_sha256']})
out=[]
for n,d,dom,fmt,physics,reason in rows:
 u=units[n];assert u['decision'] is None
 out.append(dict(screening_unit_id=u['screening_unit_id'],decision=d,confidence='medium' if d=='BORDERLINE' else 'high',primary_spho_domains=';'.join(dom),required_physics=physics,decision_reason=reason,external_physics_if_any=physics if d in ('BORDERLINE','REJECT') else '',format=fmt,page_start=pages[n],page_end=pages[n],visual_inspection_used=int(pages[n] in {1,2,3,4,5,8,9,11}),solution_used=0,boundary_status='content_boundary_verified',needs_second_review=n in (9,14,22),evidence=f'Complete printed Ortvay 2020 Q{n}, physical p{pages[n]}, read from verified SHA-based cache. Full-page renders pp1-5,8,9,11 inspected for diagrams, formula loss and withdrawal. All eleven physical pages audited; no acquired official solutions accompany this file. Q5 essential organizer-linked dataset additionally inspected and preserved. Whole numbered problems retained.'))
p=w.ROOT/'reviews/shutdown_ortvay_2020_27.json';w.writejson(p,out);w.decisions(p)
notice='Physical source p5 explicitly states Problem 10 withdrawn (26 October 19:52 CET). No statement remains; preserve acquisition row with NULL decision.'
c.execute("update units set review_status='unresolved_source_unavailable',page_start=5,page_end=5,boundary_status='content_boundary_verified',evidence=?,source_quality_notes=?,location_json=? where screening_unit_id=? and decision is null",(notice,notice,json.dumps({'top_level_label':'10','withdrawn':True}),units[10]['screening_unit_id']))
c.execute("update paper_boundary_audit set status='full_paper_boundaries_verified',observed_units=28,evidence=?,checked_at=? where file_id=3119",('All eleven pages read: Q1-Q28 labels, consisting of 27 surviving complete tasks plus explicit Q10 withdrawal notice. No additional printed tasks. Numbered internal seven analysis requests in Q5 remain one problem; final TeX marker is not a task.',w.now()))
for n,note in {5:'Essential external measurement table preserved under screening_references with original source URL/hash; no raw files changed.',7:'A causal Green kernel fixes homogeneous/initial-condition freedom; statement does not explicitly choose a Green-function convention.',12:'Fluid boundary conditions and added mass are unspecified; scope/model ambiguity retained as BORDERLINE.',17:'Printed labels jump a to c to d; no hidden part b inferred from that typographical gap.',28:'No probability measure on the original integer matrices is specified explicitly. Mathematical scope is eligible, but a unique numerical probability requires an ensemble convention.'}.items():
 c.execute('update units set source_quality_notes=? where screening_unit_id=?',(note,units[n]['screening_unit_id']))
c.commit();print('Saved 27 decisions, one explicit withdrawal, full boundary audit and verified essential data.')
