"""32 complete actual statements, including figures/models; no title inference."""
import json
import workflow as w
c=w.connect();I='I_force_motion';II='II_oscillations_waves';IV='IV_thermodynamics';VI='VI_electric_field';VII='VII_magnetic_field';VIII='VIII_induction';IX='IX_em_oscillations_waves';X='X_wave_optics'
rows=[
(1,'KEEP',[], 'data_analysis','Geometric horizon fitting with measurement uncertainties','Earth curvature, measured mountain positions and image geometry determine the estimates. Standard calibration/error propagation suffice; geographic data acquisition is explicitly permitted.'),
(2,'KEEP',[I,II],'theory','Newtonian gravity inside a sphere and constrained motion','Spherical gravity, tangential force and conserved energy determine the circular-track motion and periods; elliptic integrals are mathematical difficulty.'),
(3,'KEEP',[I,II],'theory','Periodically driven coupled pendulum motion','Building and numerically evolving the point-mechanical swing model uses Newtonian torque and oscillations. The final qualitative chaos question is peripheral to the dominant useful modelling task.'),
(4,'KEEP',[I],'data_analysis','Satellite trajectory fitting and calibration uncertainty','The source assumes a circular orbit and spherical Earth. Image geometry, Newtonian orbital speed and uncertainty fitting determine altitude; satellite context adds no external theory.'),
(5,'KEEP',[I],'theory','Static massive-cord tension and Coulomb friction','The actual slopes and hanging cord require segment force balance and optimization; catenary integrals do not constitute an external physical theory.'),
(6,'KEEP',[I,II],'theory','Coupled rolling-body small oscillations','The actual no-slip contacts, moments of inertia and gravitational energy determine the half-tube/cylinder motion.'),
(7,'KEEP',[],'data_analysis','Solar-shadow spherical geometry and timing','The measured shadow angles, city positions and rotating-Earth geometry determine times. The requirement is geometric interpretation, not unsupplied celestial dynamics.'),
(8,'KEEP',[I],'theory','Work lifting a massive rope with friction','Newtonian segment equilibrium and gravitational/friction work determine the lifting energy.'),
(9,'KEEP',[I,II],'theory','Rotating spring-mass normal modes and stability','Hooke forces in the stipulated rotating apparatus determine stationary positions, modes and stability; diagonalizing coupled equations is mathematics.'),
(10,'KEEP',[I],'theory','Inverse central-force orbit from its given shape','Angular momentum and Newtonian radial acceleration determine the potential from the specified circular locus; the source explicitly excludes relativity.'),
(11,'KEEP',[I],'data_analysis','Gravity-gradient free fall with a supplied linear drag model','Newtonian inverse-square gravity, the explicitly given drag dependence and measurement precision determine the method; no atmospheric microphysics is required.'),
(12,'KEEP',[I],'theory','Least-time motion under two specified potentials','Energy supplies speed along the path in both explicitly given potentials. First/second variations and free-endpoint optimization are mathematical requirements, not external physics.'),
(13,'KEEP',[I],'theory','Tidal torque on an irregular rigid body','Expanding ordinary external gravitational forces across a small rigid body and summing torques determines orientations; tensor/eigenvalue algebra is mathematical.'),
(14,'KEEP',[I],'theory','Classical capture under an explicitly supplied inverse-fourth potential','The interaction model is given. Energy, angular momentum and centrifugal-barrier geometry determine reaction cross section without chemistry or quantum scattering.'),
(15,'KEEP',[I],'theory','Work and sliding threshold of a defined fractal carpet','The carpet construction and area-proportional friction are supplied. Area bookkeeping, gravitational work and force balance control both whole-problem parts.'),
(16,'BORDERLINE',[I,II],'theory','Harmonic bath reduction to a Langevin friction model','Microscopic spring motion is in scope, but the requested coarse-grained Langevin description is not given and chain coupling/initial-state assumptions are underspecified. The prerequisite boundary is not clear enough for main selection.'),
(17,'KEEP',[X],'theory','Snell ray refraction and geometric caustic envelopes','The refracting ellipse and its parameterization are provided; ordinary geometrical optics and differentiating intersecting rays determine the envelope. Unfamiliar caustic terminology adds geometry rather than an external optical theory.'),
(18,'KEEP',[IV,IX],'data_analysis','Solar-panel energy calibration using supplied thermal/attenuation laws','Panel temperature, efficiency slope and exponential atmospheric attenuation are explicitly modelled. Solar geometry, regression and energy accounting suffice without semiconductor or atmospheric transport theory.'),
(19,'REJECT',[],'theory','Anisotropic electrostriction and adiabatic electrocaloric response','Cubic-crystal versus isotropic strain and temperature response centrally requires unsupplied material constitutive and susceptibility-strain/temperature relations; ordinary electrostatics alone does not determine the answer.'),
(20,'REJECT',[],'theory','Relativistic proper acceleration and elapsed proper time','The entire round trip requires unsupplied special-relativistic acceleration transformation and time dilation, especially at the light-year scale.'),
(21,'REJECT',[],'theory','Rindler coordinate geometry and scalar-field mode transformations','Proper-time simultaneity, the Riemann metric, covariant wave equation and field-mode transformation are structural unsupplied prerequisites throughout.'),
(22,'KEEP',[VI],'theory','Induced charge partition between grounded spheres','Electrostatic equilibrium, field flux and grounded boundary conditions determine the equal-charge locus. Difficult image/series methods are mathematical rather than new physical laws.'),
(23,'BORDERLINE',[VII,IX],'theory','Residual magnetization and magnetostatic vector potential','Magnetization is listed, and its residual response is supplied, but the analytic vector-potential target needs a potential/gauge formulation not supplied by this statement. Its status as an implicit Maxwell prerequisite is ambiguous.'),
(24,'KEEP',[VII,VIII],'theory','Faraday emf of a rotating arbitrary wire loop','Magnetic flux through the actual winding, induction and RMS averaging determine all parts; spherical-helix integration is mathematical.'),
(25,'KEEP',[I,II,VII],'theory','Classical angular-momentum dynamics under a supplied exchange energy','The source expressly uses continuous classical spins and gives the pair energy. Torque as orientation derivative, angular-momentum evolution and small-mode linearization suffice; quantum spin-operator machinery is not needed.'),
(26,'REJECT',[],'theory','Quantum spin-chain states and transition probabilities','Ground-state spin projections and propagation probabilities require unsupplied spin-operator algebra, state evolution and quantum measurement rules. The stated Hamiltonian alone does not supply that machinery.'),
(27,'KEEP',[],'theory','Finite Hermitian-matrix algebra and spectra under fully supplied identities','All algebraic relations and finite dimensionality are explicitly given. Constructing matrices and finding eigenvalues uses linear algebra; no quantum state or dynamical law is needed despite the Hamiltonian terminology.'),
(28,'KEEP',[],'data_analysis','Statistical detection of permuted anticorrelated binary data','The original perfect anticorrelation and permutation mechanism are provided. Testing aggregate correlations and sample size is data-analysis mathematics; no Bell theorem or unsupplied EPR physics is used.'),
(29,'REJECT',[],'theory','Spin-dependent Landau quantization','Landau levels require unsupplied magnetic minimal coupling, momentum-operator commutators and arbitrary-spin quantum representations; these control the entire task.'),
(30,'REJECT',[],'theory','Heisenberg-picture quasispin operator evolution','The requested time-dependent momentum needs unsupplied canonical quantum commutators and Heisenberg/unitary evolution; giving a Hamiltonian and hints is insufficient.'),
(31,'REJECT',[],'theory','Quantum admissibility of a phase-space Wigner function','Distinguishing a positive Gaussian from a valid Wigner function requires unsupplied quantum phase-space admissibility/uncertainty criteria, which are the central insight.'),
(32,'BORDERLINE',[],'theory','Canonical diagonalization of a supplied quadratic operator model','Completing the square is self-contained, but most of the task asks for canonical transformations without defining that restriction. The given commutators may permit a mathematical preservation route, yet assuming its meaning is not clear enough for KEEP.')]
units={int(r['problem_number']):r for r in c.execute('select * from units where source_file_id=3117')};assert len(units)==len(rows)==32
pages=[1,1,2,2,3,3,3,4,4,4,5,5,5,6,6,6,7,7,8,8,8,8,9,9,10,10,11,11,12,12,12,13]
out=[]
for n,d,domains,fmt,physics,reason in rows:
 u=units[n];assert u['decision'] is None
 external={16:'Unsupplied Langevin/coarse-graining framework; coupling topology and initial-state assumptions',23:'Unsupplied vector-potential and gauge construction',25:'Classical Heisenberg-type exchange energy explicitly given',27:'Hermitian operator algebra explicitly given; no quantum dynamics requested',28:'EPR anticorrelation explicitly supplied; only classical data inference requested',32:'Meaning of canonical quantum transformation is not explicitly defined'}.get(n,physics if d=='REJECT' else '')
 out.append(dict(screening_unit_id=u['screening_unit_id'],decision=d,confidence='medium' if d=='BORDERLINE' else 'high',primary_spho_domains=';'.join(domains),required_physics=physics,external_physics_if_any=external,decision_reason=reason,format=fmt,page_start=pages[n-1],page_end=pages[n-1],visual_inspection_used=1,solution_used=0,boundary_status='content_boundary_verified',evidence='Complete actual Ortvay 2024 source paper read, all 13 page renders inspected including photos, vector formulas, windings and matrices. Each numbered Q1-Q32 remains one whole problem; no internal a/b/c split. No associated worked solutions are present in this source inventory.'))
 if n==4:c.execute('update units set source_quality_notes=? where screening_unit_id=?',('Problem requests selecting a 2024 satellite pass from an external camera archive, rather than providing a fixed dataset. Archive/calibration links are retained in the statement; no chosen image series is falsely claimed present.',u['screening_unit_id']))
 if n in (27,28):c.execute('update units set source_quality_notes=? where screening_unit_id=?',('Self-contained mathematical/data-analysis task; no specific SPhO physics domain is inferred from quantum context.',u['screening_unit_id']))
c.execute("update paper_boundary_audit set status='full_paper_boundaries_verified',observed_units=32,evidence=?,checked_at=? where file_id=3117",('All 13 physical pages inspected: Q1-Q32, internal subparts remain whole. Final TeX marker is not an additional task.',w.now()));c.commit()
p=w.ROOT/'reviews/resume_ortvay_2024_32.json';w.writejson(p,out);w.decisions(p)
print('Saved 22 KEEP, 3 BORDERLINE, 7 REJECT; focused second checks pending.')
