"""One-time completed physical statement inspection; do not replay."""
import random
import workflow as w
c=w.connect()
rows=[
('raw::346',1113,3,'theory','I_force_motion;II_oscillations_waves','Rigid linked-plate geometry, gravitational and translational/rotational energy, small oscillations and scaling, force work along constrained displacement','The one-degree-of-freedom hinged lattice has explicitly specified geometry and plate inertia. Potential minimization, energy curvature and kinetic-energy sum give equilibrium/frequency. The final least force follows force-displacement work along the permitted geometric motion. No specialized lattice elasticity, formal Lagrangian or continuum constitutive law required.',1,True),
('raw::347',1122,4,'theory','I_force_motion;IV_thermodynamics;XI_quantum_light','Supplied comoving scale and wavelength stretching, particle conservation/photon energy, thermal-radiation temperature scaling, adiabatic first law, geometric photon flux and Newtonian shell energy','The scale-factor/distance model and wavelength proportionality to a are explicitly given. Photon energy can be taken as h*c/lambda, avoiding the key optional E=p*c route. Temperature scaling follows ordinary thermal-radiation physics, density evolution the adiabatic first law. Telescope flux uses expansion of photon separations and energy with geometric dilution. Final expansion equation is derived for nonrelativistic matter with Newtonian shell force/energy; general Friedmann cosmology or a GR metric is not assumed.',1,True),
('raw::348',1130,5,'theory','I_force_motion;VII_magnetic_field;XII_atomic_nuclear','Classical ring magnetic moment/energy, supplied spin magnitude and factor-two correction, given Cooper-pair energy, explicit functional and Gaussian minimization, supplied opposite internal fields','Spin projection, Bohr magneton, quantum factor-two correction, pair binding energy and zero-temperature lowest-energy rule are supplied. The entire diamagnetic functional AND normalized Gaussian trial family/integrals are given: direct substitution and scalar minimization suffice. Ising internal fields are explicitly specified; magnetic energies follow earlier supplied rule and vector addition. No BCS theory, Pauli susceptibility, unsupplied spin operators or quantum harmonic-oscillator spectrum required.',1,True),
('raw::349',1138,11,'experimental','X_wave_optics;XI_quantum_light','Optical grating alignment/pattern measurement, supplied full reflected-diffraction geometry, quadratic inversion and statistics, given relativistic electron-wavelength formula with image scale','All reflected-diffraction equations and limiting geometry are supplied. Graded work is apparatus alignment, measured diffraction coordinates, algebra, linear plotting, mean and standard error. Final RHEED lattice spacing uses an actual provided calibrated image and explicit voltage-wavelength relation including relativistic correction; no unsupplied relativistic mechanics or surface-crystal scattering theory needed. A-G/sample1-5 are internal tasks of one12-point experiment.',1,True),
('raw::350',1146,10,'experimental','X_wave_optics;VI_electric_field','Supplied two-beam etalon intensity, angular/intensity measurements, peak matching and linearization, gap and reflection-phase inference','The statement gives the complete two-beam interference formula and fixes/neglects polarization effects. Work consists of apparatus alignment, photodiode voltage measurement, symmetric-angle correction, peaks/plots, integer-order inference and fitting gap/phase. Neither complex metal-index theory nor Fresnel amplitude coefficients or multi-reflection transfer matrices are required. Numbered1-11 are tasks of one8-point experiment.',0,False)]
for uid,fid,*rest in rows:
 u=c.execute('select decision,source_file_id from units where screening_unit_id=?',(uid,)).fetchone();assert u['decision'] is None and u['source_file_id']==fid
out=[]
for uid,fid,np,fmt,dom,phys,reason,sol,focus in rows:
 out.append(dict(screening_unit_id=uid,decision='KEEP',confidence='high',primary_spho_domains=dom,required_physics=phys,external_physics_if_any='',decision_reason=reason,format=fmt,page_start=1,page_end=np,visual_inspection_used=1,solution_used=sol,boundary_status='content_boundary_verified',needs_second_review=focus,evidence=f'APhO2016 original file{fid}: ALL{np} actual statement pages read from SHA cache and ALL physical page renders inspected. Truncated1138pp6-9 extraction reread in full. Theory instructions1111all2pages read. Alignment chart1141 text/image inspected. Official1114pp1-3,7-15 text+p9 image checks force-work;1123all4text+p3 image checks photon flux/Newtonian shell;1131all7text+pp4/6 images checks fully supplied scalar minimization and fields;1142pp5-7,13-14text+p14image checks experimental inversion/uncertainty and supplied electron wavelength. No experiment performed or data invented.'))
p=w.ROOT/'reviews/shutdown_apho_2016_5.json';w.writejson(p,out);w.decisions(p)
for uid,fid,np,fmt,*rest in rows:
 c.execute("update paper_boundary_audit set status='full_paper_boundaries_verified',observed_units=1,evidence=?,checked_at=? where file_id=?",(f'All{np} physical pages inspected: ONE separately graded {fmt} parent, internal sections/tasks retained. No omitted independent task. ActualT1-T3/E1-E2 correspond acquisitionQ1-Q5; E1twelvepoints/E2eightpoints independently graded despite shared bench.',w.now(),fid))
for uid in ['raw::346','raw::347','raw::348']:
 c.execute('insert or ignore into unit_files values (?,?,?,?)',(uid,1111,1175,'instructions'))
c.execute('insert or ignore into unit_files values (?,?,?,?)',('raw::349',1141,1205,'supplementary'))
c.execute('update units set source_quality_notes=? where screening_unit_id=?',('Essential alignment chart1141/doc1205 already in raw and linked as supplementary; SHA/provenance retained. RHEED calibrated image is embedded in originalp11, electron wavelength including relativistic correction explicitly provided. Other measurements are contestant-generated; no fixed external dataset specified.','raw::349'))
c.execute('update units set source_quality_notes=? where screening_unit_id=?',('Official1131p5 offers optional quantum-oscillator Hamiltonian shortcut. Eligibility follows fully worked direct substitution/minimization Method1 renderedp4, which only needs the statement functional and Gaussian. Unsupplied alternate shortcut is not a required prerequisite.','raw::348'))
c.commit()
assert random.Random(2026100443).sample(['raw::346','raw::347','raw::348'],1)==['raw::346']
assert random.Random(2026100444).sample(['raw::349','raw::350'],1)==['raw::349']
reviews=[
dict(screening_unit_id='raw::346',detail='Theory QC seed2026100443 selects346. All3 actual pages include full hinge/rail geometry and single alpha degree of freedom. Official1114p2text gives ordinary energy curvature/kinetic sum, pp8/9text+p9image and appendix14/15text confirm minimum force from work along allowed vertex displacement. No assumed Lagrangian or specialized constitutive lattice law. Whole KEEP.'),
dict(screening_unit_id='raw::347',detail='Focused cosmology prerequisites. Four actual statement pages provide physical=comoving*a and lambda proportional to a. Ordinary photon h*c/lambda obtains radiation density without unsupplied SR E=p*c. Thermal temperature follows standard radiation scaling, D first law, E expansion of physical photon separation plus reduced photon energy, F/G Newtonian spherical-shell energy/force. Official1123all4text andp3image confirms this dependency chain, including two expansion factors in telescope flux. General curved-spacetime Friedmann equation mentioned only in ungraded key appendix; no outside GR machinery required. KEEP.'),
dict(screening_unit_id='raw::348',detail='Focused supplied-QM check. Original1130pp3-5 images supply spin projection, anomalous factor2, pair-energy comparison, F[psi], full normalized Gaussian family, minimization rule and two opposite internal fields. Official1131p4image directly integrates/substitutes and minimizes one scalar lambda; p6image adds fields and minimizes magnetic energy. Hamiltonian spectrum on keyp5 is an OPTIONAL alternate method. No BCS/Pauli response/unsupplied Born-state calculation central. Whole KEEP.'),
dict(screening_unit_id='raw::349',detail='Experiment QC seed2026100444 selects349. All11 actual pages include optical geometry, full diffraction equations, statistical task and calibrated RHEED image plus voltage-wavelength equation WITH relativistic correction. Alignment chart1141actualimage verified/preserved. Official1142pp5-7text uses quadratic inversion and standard error; p14image uses only supplied electron wavelength and grating geometry. No surface diffraction or SR theory needs reconstruction. A-G remain one12-point problem; whole KEEP.')]
p=w.ROOT/'reviews/shutdown_apho_2016_focused_seeded_4.json';w.writejson(p,reviews);w.review(p)
print('Saved five KEEP, five paper audits, four focused/QC checks and instruction/chart relationships.')
