import workflow as w
c=w.connect();I='I_force_motion';II='II_oscillations_waves';III='III_ideal_gas';IV='IV_thermodynamics';VI='VI_electric_field';VII='VII_magnetic_field';IX='IX_em_oscillations_waves';X='X_wave_optics';XI='XI_quantum_light';XII='XII_atomic_nuclear'
rows=[
(1,'KEEP',[],'theory','Localization using a fully specified moving-target range oracle','Constant straight velocity, binary unit-range observations and one-second query spacing define a geometric information game. Dimensional geometry and algorithms determine localization possibilities; no relativistic or weapons physical model is required.'),
(2,'KEEP',[I],'theory','Frictionless polar cargo transfer on a rotating spherical body','Surface radius, rotation, gravity and station aperture are supplied. Newtonian constrained motion and rotating coordinates determine paths and aiming; axial cargo spin must be considered under a declared skate/contact constraint, not through unsupplied exotic physics.'),
(3,'KEEP',[I],'theory','Maximum string tension for a frictional constrained slope swing','The incline/string geometry was checked. Force, energy and Coulomb friction determine speed/tension along the constrained arc; an elementary analogy is a solution-style request, not a new law.'),
(4,'KEEP',[I],'theory','Comparing slope sliding with a ballistic skier jump','Finite sliding friction and unchanged posture are explicit. Ordinary gravity, momentum direction, path geometry and landing energy/impulse losses explain speed/time differences; no aerodynamic constitutive theory is asked.'),
(5,'KEEP',[I,II],'experimental','Pendulum decay measurements discriminate prescribed drag powers','Actual turning-point measurements, multiple lengths and simple drag hypotheses are explicitly requested. Mechanical energy loss, cycle integration, fitting and uncertainty determine the comparison without assuming a drag law from a title.'),
(6,'KEEP',[I],'numerical','Frictional track speed map and slow/fast asymptotics','The constrained vertical-plane path and no-air-drag assumptions supply mechanics. Newtonian normal-force friction, energy ODE and limiting integration determine endpoint speeds and a testable example.'),
(7,'KEEP',[I,II],'theory','Rolling hoop stability and wobble frequency','The entire bicycle complexity is replaced by an explicit thin-hoop/no-slip model. Rigid angular momentum, gravity and linearized rolling dynamics determine critical speed and wobble.'),
(8,'KEEP',[I],'theory','Cable shape under both cable and deck gravity','Distributed cable/deck weights define ordinary local tension balance. Integrating the resulting curve and comparing parabola/catenary limits determine length; real bridge dimensions are numerical inputs only.'),
(9,'KEEP',[I],'theory','Stable rigid-body suspension on a frictionless sliding rope','Fixed endpoints, total rope length and smooth hook are given. Equal tensions, geometry and gravitational potential variation determine equilibrium and sphere stability.'),
(10,'KEEP',[I],'theory','Steady shapes of a moving bicycle chain on a gear','Both below/above gear arrangements were inspected in the drawing. Local moving-string momentum balance, gravity and tension constraints determine stationary shapes; a specialized elastic bending law is not required in the ideal flexible-chain model.'),
(11,'KEEP',[I],'theory','Contact loss while a rigid body tips from unstable equilibrium','The frictionless horizontal support and zero initial motion define Newtonian rigid dynamics. Center acceleration, energy and normal-force sign establish whether contact can vanish.'),
(12,'KEEP',[I],'numerical','Whole card-tower statics and inelastic cascade robustness','Rendered tower geometry, equal rigid cards, friction and collision idealization are supplied. Force/torque equilibrium and ordinary inelastic impulse/energy calculations determine load and cascade constraints. Final card-bending/world-record comparison is a peripheral validity check, not dominant unsupplied beam work.'),
(13,'KEEP',[I],'theory','Force estimates for a reservoir represented by an elastic ribbon','The source explicitly replaces the real dam by a high-stiffness ribbon with adjustable foundation attachment. Hydrostatic loading, axial tension/Hooke response and corner force balance provide a conventional estimate; it does not require a full unsupplied concrete/soil fracture theory.'),
(14,'REJECT',[],'theory','Polygonal bottle collapse requiring unsupplied elastic shell energy','Ideal-gas pressure is ordinary, but the central shape-dependent energy and buckling sequence require an unsupplied shell bending/curvature constitutive model. Homogeneous isotropic elastic material and thickness alone do not supply it.'),
(15,'KEEP',[I],'numerical','Newtonian coupled motion and stability of interlinked rigid tori','The tori are explicitly rigid/homogeneous. Distributed Newtonian gravity, rigid force/torque equations and numerical linear stability determine admissible trajectories; many degrees of freedom add mathematics rather than an outside physical theory.'),
(16,'REJECT',[],'theory','Elastic spherical-shell bell modes without a supplied shell equation','Radii and copper context do not supply the continuum stress/strain, shell flexural coupling and mode boundary model needed for emitted frequencies. That specialized elasticity is the entire central task.'),
(17,'KEEP',[II],'theory','Projection of a supplied polarization wave packet in a moving frame','Three orthogonal k-dependent polarizations with distinct dispersion/group speeds are stipulated. Fourier superposition, a classical moving coordinate and projection onto the second detector axis determine signal. Deriving crystal elasticity is not requested; the optional quantum analogy is peripheral.'),
(18,'REJECT',[],'experimental','Lifetime and interactions of noncoalescing droplets on a liquid surface','The central delay/rupture mechanism needs unsupplied air-film lubrication, viscous surface dynamics and coalescence/film constitutive assumptions. Basic surface tension and measurements alone do not specify lifetimes and driven interactions; experimental format does not change that prerequisite.'),
(19,'BORDERLINE',[III,IV],'data_analysis','Gas-mixture condensation inferred from a given isotherm','The graph and boiling temperatures support ordinary gas/phase/latent-heat reasoning under an independent-condensate idealization. But liquid-mixture miscibility/activity and temperature-shift phase model are not specified for the final expansion curve. The intended foundational approximation versus substantial mixture-phase model is unresolved.'),
(20,'KEEP',[IV],'theory','Composition consistency of two serial heat-engine efficiencies','The identical temperature-only efficiency function and serial heat flow are supplied. Energy balance and functional-equation/reversible-engine reasoning derive the Carnot form through ordinary thermodynamics.'),
(21,'KEEP',[I,IV,XI],'theory','Orbital eccentricity effect on blackbody equilibrium temperature','Eccentricity interval and blackbody reradiation are supplied. Kepler time weighting of solar inverse-square flux and thermal radiation balance determine the maximum temperature change without an actual climate model.'),
(22,'KEEP',[VII],'theory','Possible circular magnetic field lines from two parallel currents','Biot-Savart/Ampere fields and planar vector geometry determine field-line shapes and exceptional circular conditions. No unsupplied matter/quantum theory appears.'),
(23,'KEEP',[I,VII],'numerical','Classical particle exclusion by solenoid stray field','The source explicitly requests classical motion and supplies geometry/central field; the trajectory drawing was inspected. Lorentz force, axial-field flux/magnetostatic integration and momentum/energy constraints determine threshold speed.'),
(24,'KEEP',[VI,VII,X],'theory','Current and field of a spherical loxodrome and its projected trace','Constant-angle curve, voltage and projection geometry define standard differential geometry, Ohm resistance and Biot-Savart integration. Finite paint width/thickness/contact cutoffs regularize pole estimates. The captain-age bonus is peripheral and cannot be inferred uniquely.'),
(25,'KEEP',[X],'theory','Inferring droplet refractive index from overlapping rainbow colours','Spherical drops and unusual colour order are supplied. Snell paths, internal reflections, dispersion and stationary deflection geometry determine permitted index and observation angle.'),
(26,'KEEP',[X],'numerical','Internal and external principal-rainbow caustics','Spherical water drops supply ray geometry. Refraction/reflection and ray-family envelope calculus determine both caustic shapes; no advanced material law is needed.'),
(27,'BORDERLINE',[XII],'theory','Physical interpretation of a historical nuclear-device mass concern','The source supplies a historical quotation but no intended material/criticality or ancillary-mass assumptions. A qualitative nuclear-energy/fission explanation may be foundational, whereas a quantitative critical assembly/transport account requires unsupplied specialized nuclear engineering. Intended prerequisite depth is unresolved.'),
(28,'KEEP',[],'theory','Euler identity for generic Voronoi-cell faces','The geometric cell definition and target face-count relation are given. Euler polyhedron counting for generic trivalent vertices proves it; amorphous-material context adds no atomic interaction model. Degenerate higher-valence vertices require a stated general-position assumption.'),
(29,'REJECT',[],'theory','Prerequisites of Wiedemann-Franz electronic transport','The law is named but its expression, fermionic occupations and relaxation/energy-dependent scattering model are not supplied. Explaining failure in heavily doped semiconductors centrally requires specialized electronic transport theory.'),
(30,'REJECT',[],'theory','All gravitational light trajectories around a spherical source','No spacetime metric or null-geodesic equations are supplied. The requested paths and closed-light-orbit existence require unsupplied GR throughout.'),
(31,'REJECT',[],'numerical','Mutual images and signal timing for four black-hole infallers','Initial fall geometry is supplied, but Schwarzschild geodesics, null-ray connection, observer tetrads and proper-time/Doppler transformations are not. Those GR prerequisites control all requested images, lengths and communications.'),
(32,'KEEP',[],'numerical','Annular eigenproblem with full model supplied by an explicitly cited reference','The boundary ratios are printed, and the exact cited Berry-Mondragon paper was recovered from the author. Its inspected pp1-8 explicitly define Pauli matrices, the coordinate PDE, current and scalar infinite-wall boundary derivation. Bessel separation, annular determinant and numerical roots then require mathematics; graphene identification is peripheral.'),
(33,'REJECT',[],'theory','Polarization-resolved quantum-box absorption via an unsupplied golden rule','Box geometry alone does not supply quantum eigenfunctions, electric-dipole matrix elements or the Fermi golden absorption rule. These specialized quantum prerequisites centrally determine every line/intensity comparison.'),
(34,'KEEP',[VI],'numerical','Piecewise nonlinear charging under an explicitly supplied leakage ODE','The complete voltage ODE, thermal voltage, threshold, capacitance, drive current and switch intervals are supplied. Separation or numerical integration and repeated boundary matching yield ten cycles; no semiconductor microphysics is needed.'),
(35,'KEEP',[],'numerical','Optimal switching under a fully supplied two-reservoir production model','Capacity equality and both proportional production/extraction rates define a complete toy ODE/control model. Integrating, optimizing switching and iterating feed/rest cycles are mathematics; no biological or medical guidance is required.')]
pages=[1,1,1,1,2,2,2,2,2,2,3,3,3,3,4,4,4,4,4,5,5,5,5,5,6,6,6,6,6,6,6,7,7,7,7]
u={int(r['problem_number']):r for r in c.execute('select * from units where source_file_id=3130')};assert len(u)==35
out=[]
for n,d,dom,fmt,physics,reason in rows:
 assert u[n]['decision'] is None
 out.append(dict(screening_unit_id=u[n]['screening_unit_id'],decision=d,confidence='medium' if d=='BORDERLINE' else 'high',primary_spho_domains=';'.join(dom),required_physics=physics,decision_reason=reason,external_physics_if_any=physics if d in ('BORDERLINE','REJECT') else '',format=fmt,page_start=pages[n-1],page_end=pages[n-1],visual_inspection_used=1,solution_used=0,boundary_status='content_boundary_verified',needs_second_review=n in (12,13,17,28,32,34,35),evidence=f'Complete actual Ortvay 2010 Q{n}, physical p{pages[n-1]}, inspected from valid SHA cache and all seven full-page renders. Chain/card/solenoid geometry, mixture graph and intact PDE/ODE/operator formulas checked. Exact Q32 cited reference additionally inspected in rendered pp1-8 and preserved with provenance/hash; no unrelated physics reference added. No acquired official solution. Whole numbered parent clauses retained.'))
p=w.ROOT/'reviews/shutdown_ortvay_2010_35.json';w.writejson(p,out);w.decisions(p)
c.execute("update paper_boundary_audit set status='full_paper_boundaries_verified',observed_units=35,evidence=?,checked_at=? where file_id=3130",('All seven physical pages read and visually inspected: exactly Q1-Q35; lettered cases, bonuses and alternative designs remain parent tasks. Q12 long tower statement belongs entirely to one unit. Q32 exact cited research model registered as a reference, not a separate contest task. No omitted top-level experiment/MCQ.',w.now()))
notes={1:'No velocity bound, search-domain bound or acquisition initial localization is specified; information-theoretic result must state those conventions.',2:'Blade/point-contact orientation and cargo inertia are not explicitly modelled; spin effect is contingent on a declared ideal skate constraint. Number of tapes is an unprovided joke cost input.',6:'Track shape and friction/material model must be declared for an explicit numerical example; source permits choosing one.',12:'Final bending-validity and world-record comparison are peripheral to rigid-card statics/cascade main work; collision model must specify inelastic contact resolution.',13:'This is a stated simplified ribbon/attachment model, not a validated cause reconstruction for the actual disaster. Geometry and foundation-strength parameters remain declared assumptions.',17:'Polarization/dispersion functions and packet envelope are not numerically specified; general Fourier-projection answer is parametrized. Optional quantum analogy is not the main prerequisite.',19:'Independent vapor pressures versus miscible liquid activities are not specified; graph alone does not uniquely prescribe the raised-temperature phase curve.',24:'Finite paint cross-section/contact cutoff not supplied. Pole asymptotics can diverge in the zero-width idealization; estimates must retain finite physical dimensions. Bonus captain age cannot be uniquely inferred.',27:'Historical material/enrichment/criticality or other mass-budget assumptions not specified; do not fabricate a detailed engineering model.',28:'Target identity requires generic trivalent Voronoi vertices; exact symmetric/degenerate cells can violate it. General-position convention must be stated.',32:'Exact source-cited model reference preserved. Scanned paper has no valid text extraction; pp1-8 actually inspected in renders. It supplies differential equation/current/boundary rules, not the annular solution. Source graphene identification is a peripheral context question.',34:'Voltage V denotes thermal potential, distinct from surface U. Complete exponent and alternating drive/no-drive laws are supplied.',35:'The supplied reservoir toy model is screened as mathematics, not a real infant-feeding recommendation. Optional ll li website is unnecessary to solve the complete given model and was not added as missing biology.'}
for n,note in notes.items():c.execute('update units set source_quality_notes=? where screening_unit_id=?',(note,u[n]['screening_unit_id']))
c.commit();print('Saved 35 decisions and full seven-page boundary audit.')
