"""Actual-source whole-problem decisions, with focused model/prerequisite checks."""
import json
import workflow as w
c=w.connect();I='I_force_motion';II='II_oscillations_waves';III='III_ideal_gas';IV='IV_thermodynamics';VI='VI_electric_field';VII='VII_magnetic_field';VIII='VIII_induction';IX='IX_em_oscillations_waves';X='X_wave_optics';XI='XI_quantum_light'
data={1912:[
('A1',2,3,'KEEP',[X],'Thin-lens correction and circular-aperture diffraction','Geometrical optics and diffraction-limited resolution/intensity dominate the complete problem; the Airy aperture is an ordinary extension of the listed diffraction framework.'),
('A2',4,4,'KEEP',[I],'Force-free constrained motion on a frictionless cone','General relativity is introductory context only. Normal forces, energy, angular momentum and cone geometry determine every part.'),
('A3',5,5,'KEEP',[I,II,III,IV],'Adiabatic parcel buoyancy and prescribed rotating-fluid stability','The source specifies parcel pressure equilibrium and the vortex velocity profile. Ideal-gas first law, force balance and angular momentum determine both instabilities without an unsupplied fluid PDE.'),
('B1',7,8,'KEEP',[I,III,IV,XI],'Supplied ionization/recombination rates, ideal-gas pressure and cooling','Recombination and cooling models are explicitly given. Particle counting, hydrostatics and thermal energy determine all requested scales; stellar plasma microphysics is unnecessary.'),
('B2',9,9,'KEEP',[I,VI],'Coulomb conic orbits and scattering geometry','The conic equations are provided. Central force, angular momentum and geometric fitting determine trajectories and deflection.'),
('B3',10,10,'KEEP',[VI,VIII,IX],'Inductive stored energy, eddy-current loss and quality factor','The Q definition and negligible skin/end effects are stated. Faraday induction, ordinary conductivity and magnetic energy determine all parts without superconductivity theory.')],
1920:[
('A1',4,4,'KEEP',[VI,VIII,IX],'LC oscillations with a supplied dipole-radiation power law','Capacitance and solenoid inductance determine the oscillation. The radiation formula is given, so energy-loss estimates require no unsupplied radiation theory.'),
('A2',5,5,'KEEP',[I,III,XI],'Stellar shell force balance and supplied quantum-pressure estimate','The equation of state and uncertainty-spacing model are supplied. Newtonian gravity, basic kinetic momentum flux and scaling determine stability and white-dwarf radius; external degeneracy theory is not required.'),
('A3',6,6,'KEEP',[X,XI],'Lens distortion, diffraction blur and photon-counting noise','Ray optics, standard diffraction scaling and the supplied square-root counting variance determine all parts; imaging context adds no external theory.'),
('B1',8,8,'REJECT',[],'Relativistic collision invariants and time-dilated muon decay','Unsupplied relativistic collision energy and proper-time laws control three substantial parts and their dependencies. The geometric collision-count part alone does not make most of the whole problem usable.'),
('B2',9,9,'KEEP',[II,III,IV],'Heat capacity from a fully supplied quantum entropy model and gas-piston oscillations','The quantum energy, entropy and dE=T*dS are given. Differentiation plus ideal-gas thermal balance and Newtonian oscillations supply the full method without quantum state machinery.'),
('B3',10,10,'KEEP',[VI,IX],'Damped and driven RLC response with parameter estimation from data','The frequency response and Q definition are supplied; resonance, damping, circuit laws and fitting the given measurements are expressly eligible.')],
1923:[
('A1',4,4,'KEEP',[I],'Repeated ballistic paths with specified elastic reflections','Newtonian projectile motion, specular elastic velocity reversal and the supplied well shapes determine every part; difficult trajectory geometry is mathematical.'),
('A2',5,5,'KEEP',[I,II,VI],'Coulomb potential, small oscillations and circular motion','Electrostatic potential and its derivatives determine equilibrium and restoring/centripetal forces. Radiation is explicitly ignored.'),
('A3',6,7,'KEEP',[III,IV],'Ideal-gas cycle and reversible pressure-dependent freezing engine','The ordinary first/second laws and Carnot comparison derive the phase-transition slope; no unsupplied Clapeyron equation needs to be known.'),
('B1',9,9,'KEEP',[I,II,VII,VIII],'Solenoid inductance, magnetic rod torque and coupled rotation','Magnetic force, motional emf, inductive energy and rotational inertia determine the dynamics; the required integrals are supplied.'),
('B2',10,10,'KEEP',[I,IX,XI],'Laser-sail propulsion with explicitly supplied relativistic transformations','The source supplies gamma, energy, momentum, force definition and both frame transformations. Conservation and photon-interception geometry suffice; no prior unsupplied relativity law is needed.'),
('B3',11,11,'KEEP',[I,VII,XI],'Neutrino flight times and magnetic deflection under supplied relations','The statement explicitly carries forward the preceding relativistic formula sheet and gives magnetic curvature. Algebraic expansion and path geometry determine mass/charge estimates without neutrino microphysics.')]
}
out=[]
for fid,rows in data.items():
 units={r['problem_title'].split('. ',1)[0]:r for r in c.execute('select * from units where source_file_id=?',(fid,))}
 assert len(rows)==len(units)==6
 for label,ps,pe,decision,domains,physics,reason in rows:
  u=units[label];assert u['decision'] is None
  out.append(dict(screening_unit_id=u['screening_unit_id'],decision=decision,confidence='high',primary_spho_domains=';'.join(domains),required_physics=physics,external_physics_if_any=physics if decision=='REJECT' else 'Relativistic equations and frame transformations explicitly supplied' if fid==1923 and label in ('B2','B3') else 'Quantum uncertainty estimate explicitly supplied' if fid==1920 and label=='A2' else 'Quantum solid entropy model explicitly supplied' if fid==1920 and label=='B2' else '',decision_reason=reason,format='data_analysis' if fid==1920 and label=='B3' else 'theory',problem_number=label,round_or_section=u['round_or_section']+' / Part '+label[0],page_start=ps,page_end=pe,location_json=json.dumps({'acquisition_problem_number':u['problem_number'],'shared_formula_pages':[3,10] if fid==1923 and label=='B3' else [1,6] if fid==1912 else [3]}),visual_inspection_used=1,solution_used=int((fid==1920 and label in ('A2','B1','B2')) or (fid==1923 and label in ('B2','B3')) or (fid==1912 and label=='A3')),boundary_status='content_boundary_verified',evidence=f'Entire actual source paper {fid} read, including all reference sheets and page renders. Six printed A1-A3/B1-B3 units remain whole, including their internal sections and subparts. Focused official solution inspected where recorded.'))
 c.execute("update paper_boundary_audit set status='full_paper_boundaries_verified',observed_units=6,evidence=?,checked_at=? where file_id=?",('Complete source paper contains exactly A1-A3 and B1-B3. Blank graph/reference/instruction pages are context rather than extra units.',w.now(),fid))
c.commit();p=w.ROOT/'reviews/resume_usapho_2023_2024_2026_18.json';w.writejson(p,out);w.decisions(p)
focused={
'raw::1019':'Focused second reading: actual 2024 A2 p5 plus official solution pp6-8. Uncertainty times spacing is given; pressure then follows ordinary kinetic momentum flux. No unsupplied Fermi-Dirac statistics is used. KEEP confirmed.',
'raw::1021':'Focused second reading: actual 2024 B1 p8 plus official solution pp13-15. The solution requires relativistic invariant collision energy and time dilation for a, b and d; neither law is supplied by the statement/reference table. REJECT confirmed at whole-problem level.',
'raw::1022':'Focused second reading: actual 2024 B2 p9 plus official solution pp16-18. Supplied entropy/energy derivatives control the quantum part, and given solid heat capacity plus gas first law controls piston motion. KEEP confirmed; unfamiliar solid-state context is not a prerequisite.',
'raw::1053':'Focused second reading: actual 2023 B2 p10 and official solution pp19-21. The primary solution uses only the supplied photon energy-momentum transformations, reflection, momentum conservation and lab interception rate (1-v/c); no unsupplied time-dilation law enters. KEEP confirmed.',
'raw::1054':'Focused second reading: actual 2023 B3 p11 and official solution pp22-24. Gamma-energy and photon momentum relations supplied on the previous source page plus given magnetic radius suffice. The formula page is preserved as shared context. KEEP confirmed.'}
p=w.ROOT/'reviews/resume_usapho_modern_focused_qc_5.json';w.writejson(p,[dict(screening_unit_id=k,detail=v) for k,v in focused.items()]);w.review(p)
print('Saved 17 KEEP, 1 REJECT; five suspicious modern/model cases reviewed.')
