"""Persist explicit reviews of the complete 2022 statement paper."""
import workflow as w
c=w.connect();I='I_force_motion';II='II_oscillations_waves';III='III_ideal_gas';IV='IV_thermodynamics';VI='VI_electric_field';VII='VII_magnetic_field';VIII='VIII_induction';IX='IX_em_oscillations_waves';X='X_wave_optics'
rows=[
(1,'KEEP',[I],'theory','Newtonian descent with normal-force friction on a cycloid','The actual slope drawing defines the path. Gravity, curvature-dependent normal reaction and Coulomb friction determine the stopping condition; cycloid integration is mathematics.'),
(2,'KEEP',[I],'theory','Free-particle kinetic energy expressed in curvilinear coordinates','The supplied quadratic expression is directly recognizable as squared Cartesian speed: set y=sin(theta), z=phi, x=r to obtain rdot^2+r^2 thetadot^2+r^2 sin^2(theta) phidot^2. Thus Newtonian free-particle motion and coordinate conversion solve it without assuming an arbitrary canonical Hamiltonian evolution rule.'),
(3,'KEEP',[I],'theory','Energy and fuel optimization with a supplied drag/power law','Road shape, drag polynomial, idle power and fuel energy are given. Gravitational work, braking loss and travel time determine consumption; optimal speed profiles add mathematical optimization.'),
(4,'KEEP',[I],'theory','Projectile motion and geometric restitution sequences','The velocity-component restitution rule is explicitly supplied and the A-B-C drawing inspected. Flight times and repeated bounce displacements determine k, N and the limiting case.'),
(5,'KEEP',[I,II],'theory','Newtonian variable-length pendulum and numerical phase portraits','The full length history is given. Tangential gravity and changing inertia determine the nonlinear equation; numerical phase-space tracking requires no unsupplied adiabatic or chaos theory.'),
(6,'KEEP',[I],'theory','Bead motion along a uniformly rotating rod','The actual orientation and initial conditions were checked visually. Radial Newtonian acceleration and gravity give a linear driven equation and every requested limiting condition.'),
(7,'KEEP',[I],'theory','Inverse roller-coaster shape for a fixed normal force','Energy conservation and normal acceleration related to curvature determine the track, including loop solutions. Differential geometry and integration do not add physical prerequisites.'),
(8,'KEEP',[I],'theory','Constrained skate motion with explicitly given linear drag','Allowed velocity direction and transverse constraint forces are described operationally. Newton force balance and torque yield trajectory and asymptotics; nonholonomic terminology is not necessary to use the stated constraint.'),
(9,'KEEP',[I,II],'theory','Rigid-wire physical pendula about two axes','Dimensions and suspension corners of the ELTE wire letters were visually inspected. Center of mass and moments of inertia determine both small-angle periods.'),
(10,'KEEP',[I,II],'theory','Normal modes in an explicitly supplied molecular potential','The exact perimeter/area potential was checked in the page render. Its Hessian with Newtonian point masses gives vibrational frequencies; molecular context adds no quantum prerequisite.'),
(11,'KEEP',[I],'numerical','Hydrostatic equipotential surface in a uniform-prism gravitational field','The prism geometry, density and shoreline position define Newtonian gravity and the equipotential liquid surface. Numerical gravitational integration and hydrostatics determine central depth.'),
(12,'KEEP',[X],'theory','Fresnel-zone interference with a finite-distance source','Zone construction, optical path differences and coherent interference determine higher intensity positions and the geometrical limit. Fresnel diffraction is explicitly within operational wave optics.'),
(13,'KEEP',[I,II,VI],'theory','Electrostatic restoring-force Hessian and three-dimensional stability','Coulomb integration along the charged triangle and small-oscillation dynamics determine in-plane frequency; electrostatic potential constraints explain three-dimensional escape. No specialized atomic model is needed.'),
(14,'KEEP',[VII,VIII],'theory','Linear-permeability sphere in a solenoid and magnetic energy','Small spherical geometry and high relative permeability supply the material response. Ordinary magnetostatic boundary matching and flux linkage give the change of inductance.'),
(15,'KEEP',[I,VII,VIII],'theory','Dipole-flux induction and terminal fall in a polygonal tube','The dipole approximation and neglect of self-induction are explicitly stated. Induced emf, Ohmic dissipation and gravitational power determine terminal speed for each polygon; difficult integrations are mathematics.'),
(16,'KEEP',[VII],'theory','Magnetostatic field lines of a wide rectangular solenoid','The apparatus render confirms b much less than h much less than a. Biot-Savart superposition and field-line integration determine the specified cross-sectional pattern.'),
(17,'BORDERLINE',[VI,VIII,IX],'theory','Retarded electromagnetic turn-on of a distributed two-wire circuit','Maxwell waves and circuit fields are in scope, so transmission-line vocabulary alone is no reason to reject. However the requested full voltage transient and simultaneous end cuts lack wire radius, source-switch boundary detail and distributed line parameters. Intended approximations and model completeness are ambiguous without a solution.'),
(18,'KEEP',[VI],'theory','Ohmic surface-current flow on a cone','Unfolding the developable surface and current continuity with local Ohm law determine the current-density field. The actual A/B/C geometry was inspected; conformal/Laplace mathematics adds no external physics.'),
(19,'REJECT',[],'theory','Relativistic Coulomb orbital period in coordinate and proper time','Relativistic momentum-energy dynamics and proper time are unsupplied and required throughout the Kepler-law comparison.'),
(20,'REJECT',[],'theory','Quantum quartic-oscillator perturbation and variational improvement','The Hamiltonian is given, but quantum oscillator states, first-order operator matrix elements and Schrodinger dynamics are not. These specialized rules control all nonoptional parts; numerical work does not supply missing physics.'),
(21,'REJECT',[],'theory','Oscillator creation-operator states and quantum moments','Raising-operator action, number-state basis, position operator representation and quantum expectation rules are unsupplied. They are central to every normalization and deviation task.'),
(22,'KEEP',[],'theory','Convex mixtures of fully specified positive Gaussian kernels','Physical is expressly defined as positive semidefinite with unit trace, and every Gaussian kernel and parameter condition is given. A positive rank-one kernel with a nodal diagonal supplies a mathematical counterexample since each allowed Gaussian diagonal is strictly positive. No quantum evolution or measurement rule is required.'),
(23,'BORDERLINE',[IV],'theory','Gaussian integral-operator entropy with partially supplied quantum thermal model','Entropy, relative entropy and Gaussian kernels are explicitly supplied, supporting substantial mathematical spectral work. The momentum representation needed to derive the requested thermal kernel is not defined, and printed normalization/free-energy formulas contain apparent inconsistencies. Supplied-model sufficiency and intended corrected task are ambiguous.'),
(24,'REJECT',[],'theory','Hawking temperature, emission and absorption dynamics of black holes','No Hawking mass-temperature law or black-hole absorption cross section is supplied. These specialized relations control all radiation exchanges and delay dynamics, so ordinary blackbody physics alone cannot solve the task.'),
(25,'REJECT',[],'theory','General-relativistic metric curvature and Einstein matter tensor','The scalar equation of motion is supplied, but geodesic connection, curvature tensor and Einstein energy-momentum relation are not. They are the structural prerequisites for the entire requested gravitational interpretation.'),
(26,'KEEP',[],'theory','Discrete evolution under explicitly specified cellular-automaton rules','State space, alternating blocks, local permutations and modular map are completely given. Reversibility, causal reach, Green function and numerical recurrence are discrete algebra and programming, without external many-body physics.'),
(27,'KEEP',[IV,VII],'theory','Classical discrete-spin energy and a supplied trial probability model','All spins are classical binary variables; their pair energy and consistent pair-marginal trial distribution are given. Mean energy, Boltzmann entropy and free-energy minimization yield correlation and phase behaviour. No unsupplied quantum spin operators are needed; statistical/probability algebra handles the supplied model.'),
(28,'KEEP',[I,II],'theory','Retarded sound propagation from one supersonic circular source','Full Q28 spans pp11-12, including Tuesday/Wednesday extensions. Sound travel time, circular motion and multiple emission-time roots explain apparent cars and caustics. The supernatural interpretations are stories to disprove, not required physics.')]
pages=[1,1,2,2,2,3,3,4,4,4,5,5,5,5,5,6,6,6,7,7,7,8,8,9,9,10,10,11]
visual_pages={1,2,3,4,6,8,10};units={int(r['problem_number']):r for r in c.execute('select * from units where source_file_id=3118')};assert len(units)==28
out=[]
for n,d,dom,fmt,physics,reason in rows:
    u=units[n];assert u['decision'] is None
    out.append(dict(screening_unit_id=u['screening_unit_id'],decision=d,confidence='medium' if d=='BORDERLINE' else 'high',primary_spho_domains=';'.join(dom),required_physics=physics,decision_reason=reason,external_physics_if_any=physics if d in ('BORDERLINE','REJECT') else '',format=fmt,page_start=pages[n-1],page_end=12 if n==28 else pages[n-1],boundary_status='content_boundary_verified',visual_inspection_used=int(pages[n-1] in visual_pages),solution_used=0,needs_second_review=n in (2,22,27),evidence=f'Complete actual Ortvay 2022 printed Q{n}, physical p{pages[n-1]}'+('-12' if n==28 else '')+' read from SHA-verified cache. Full-page renders pp1-4,6,8,10 checked for diagrams and broken formula extraction. All twelve physical pages read for top-level completeness; no associated official solution exists in the acquired inventory. All internal bullets/letters remain inside the printed question.'))
p=w.ROOT/'reviews/shutdown_ortvay_2022_28.json';w.writejson(p,out);w.decisions(p)
c.execute("update paper_boundary_audit set status='full_paper_boundaries_verified',observed_units=28,evidence=?,checked_at=? where file_id=3118",('All twelve pages inspected: exactly Q1-Q28. Page12 continues Q28 rather than adding tasks; dedication photograph and final TeX marker are not questions.',w.now()))
for n,note in {17:'Full distributed transient lacks conductor size and switching details; BORDERLINE retains the unresolved model interpretation rather than inventing a line impedance.',23:'Printed F_beta formula omits the logarithm of the partition trace; printed thermal-kernel quadratic expression also appears inconsistent with its zero-temperature limit. No corrected worked solution is present.',28:'Q28 continues onto physical p12; retain all Extra Additional and Tuesday/Wednesday tasks as one top-level problem.'}.items():
 c.execute('update units set source_quality_notes=? where screening_unit_id=?',(note,units[n]['screening_unit_id']))
c.commit();print('Saved 28 source-grounded decisions and full paper boundaries; five focused checks queued.')
