import workflow as w
c=w.connect();I='I_force_motion';II='II_oscillations_waves';III='III_ideal_gas';IV='IV_thermodynamics';VI='VI_electric_field';VII='VII_magnetic_field';VIII='VIII_induction';IX='IX_em_oscillations_waves';X='X_wave_optics'
rows=[
(1,'KEEP',[IV,IX],'experimental','Calibrated heating under pulsed microwave power control','The full task requests experiments on a real oven and an empirical repeatable recipe, allowing spatial/time variations. Heat capacity, energy, duty cycling and electromagnetic heating/reflection are ordinary scope; appliance-brand detail is a peripheral source-specific explanation.'),
(2,'KEEP',[I,III],'numerical','Altitude-dependent quadratic-drag fall time comparison','Quadratic drag and barometric density are stipulated. Hydrostatic ideal gas, Newtonian motion and numerical comparison of the two launch heights supply all central physics.'),
(3,'KEEP',[I],'theory','Eigenstructure of the ordinary elastic-collision velocity map','Momentum and kinetic energy define the central elastic collision matrix. Center-of-mass and relative-motion eigenvectors are ordinary mechanics plus linear algebra.'),
(4,'KEEP',[I],'theory','Acceleration recurrence for a cascade of ideal pulleys','The nested massless-pulley geometry was inspected in the render. Newton equations, tension continuity and rope constraints determine all accelerations and the infinite-depth limit.'),
(5,'KEEP',[I],'theory','Newtonian orbital response to slow evaporative mass loss','Ordinary Newtonian gravity and variable-mass momentum accounting determine orbital evolution for declared isotropic/no-recoil evaporation and relative-mass assumptions. The unspecified evaporation rate or anisotropy is a source-model limitation, not an outside law.'),
(6,'KEEP',[I],'numerical','Minimum-time bicycle control with supplied drag and work budget','The prescribed energy budget, arbitrary torque and power-law drag define a Newtonian optimal-control problem. Downhill regeneration changes energy constraints; variational optimization is mathematics rather than human physiology.'),
(7,'KEEP',[I],'theory','Correct reduction of a classical cyclic coordinate at fixed momentum','The paradox concerns ordinary central-force motion and substituting an angular-momentum constraint. Chain rule and constrained variation/partial Legendre transformation recover the correct Newtonian radial equation; no new physical theory is required.'),
(8,'KEEP',[X],'theory','Ray paths under a fully supplied direction-dependent refractive index','Fermat principle is specified as the governing variational model and all index functions/directions are defined. Parameter-invariant calculus and central ray geometry determine the complete requested path equations.'),
(9,'KEEP',[I],'theory','First-order orbital precession for a supplied potential perturbation','Newtonian energy/angular momentum and the given target first-order relation define the task. Perturbing radial orbit integrals and evaluating Kepler angular integrals are mathematics, with no relativistic precession assumption.'),
(10,'KEEP',[I,II],'theory','Small oscillations of a homogeneous cone rolling on an incline','Gravity, rigid inertia and rolling constraints determine the equilibrium and restoring kinetic/potential energy. No elastic bending or specialized material model is needed.'),
(11,'REJECT',[],'theory','Clamped flexible-beam mode spectrum with an attached tip mass','Young modulus is supplied but the bending moment-curvature law, flexural beam PDE and free/tip-mass boundary rules are not. They centrally determine every resonance/design/detuning part; scalar Hooke extension does not supply the required model.'),
(12,'KEEP',[I],'theory','Sag and stability of a weighty rope over two ideal pulleys','Ordinary tension balance, gravity, total length and equal free-end tensions determine catenary equilibria. Stability and asymptotic bifurcations are calculus of mechanical potential energy.'),
(13,'KEEP',[I],'numerical','Inferring a mercury droplet mass from shape and contact angle','Given contact angle and height-to-width ratio, hydrostatic pressure and conventional surface-tension curvature set the shape and capillary length. Material constants and numerical integration are ordinary general-physics tools.'),
(14,'KEEP',[I],'numerical','Maximum hanging droplet under complete wetting','Density, surface tension, gravity and complete wetting supply the equilibrium force/pressure model. Solving the axisymmetric capillary shape and locating loss of stability require mathematics, not an unsupplied droplet constitutive law.'),
(15,'KEEP',[I],'theory','Slowly rotating self-gravitating incompressible liquid sphere','Incompressibility and negligible viscosity are given. Newtonian gravitational potential, centrifugal hydrostatics and surface tension define the small shape perturbation and the two relevant smallness scales.'),
(16,'BORDERLINE',[II],'theory','Wave-equation transformation in both classical and relativistic frames','Classical moving-medium wave transformation, sonic limit and Green functions are ordinary mathematics/physics. The task equally demands special-relativistic transformations that are not supplied. Whole meaningful work is mixed near the boundary; do not split off the classical half.'),
(17,'KEEP',[VI,VIII,IX],'theory','Impedance of the explicitly drawn triangular LC chain','The rendered alternating-branch circuit supplies the topology. Ordinary impedance, Kirchhoff equations and lattice transforms determine contact impedance, DC and resonance after interchange.'),
(18,'KEEP',[VI],'theory','Force ratio for a charged wire near a grounded plate edge','The two explicit wire placements define conventional electrostatic boundary problems. Images or conformal boundary mathematics give forces and their ratio without a new electrostatic theory.'),
(19,'KEEP',[I,VI],'theory','Fall of a charged cylinder toward a grounded conductor','Electrostatic induction/potential energy and Newtonian motion determine impact speed and far-distance fall time. Radiation is expressly neglected, and the finite-radius conductor boundary is specified.'),
(20,'BORDERLINE',[VII],'theory','Dipole force near a sphere with zero London penetration depth','Once interpreted as complete flux exclusion, conventional magnetostatic boundary mathematics solves the force. But the statement only names superconductivity and zero London depth, without defining the local field/flux condition or initial trapped-flux assumptions. Supplied-model adequacy is uncertain at the established superconducting boundary.'),
(21,'KEEP',[I,II,VII],'theory','Energy exchange between two weakly coupled compass rotors','Magnetic moments, inertias, external field and all three geometries are specified. Ordinary dipole torque and coupled small oscillations determine beats, residual amplitude and timing.'),
(22,'KEEP',[I,VIII],'numerical','Falling dipole retarded by a resistive ring with negligible inductance','The exact axial geometry and negligible self-inductance provide the model. Faraday/Lenz induction, Ohm law and Newtonian gravity give the nonlinear ODE and trajectory.'),
(23,'KEEP',[II,IV,VII],'theory','Classical spin-wave model with supplied torque and angular momentum','The source explicitly gives energy, effective field derivative, moment-to-angular-momentum coefficient, torque and classical regime. Newtonian angular-momentum evolution, Fourier normal modes, equipartition and mode integrals yield all five linked parts; quantum-spin or many-body theory need not be imported.'),
(24,'REJECT',[],'theory','Nordstrom free fall requiring unsupplied relativistic normalization','A four-force expression is provided, but four-velocity normalization, proper versus laboratory time and variable rest-mass/energy rules are not operationally supplied. They centrally determine acceleration, elapsed times and impact speed.'),
(25,'KEEP',[X],'numerical','Diffraction spot counts for two rotated or mismatched square gratings','Both Fraunhofer regime and pointwise product of transmissions are explicit. Fourier wave optics, reciprocal-lattice sums and propagation constraints determine spot locations/counts and the small-angle patterns.'),
(26,'BORDERLINE',[IV],'theory','Classical periodic-potential thermodynamics with requested quantum improvement','The complete classical Hamiltonian supplies substantial Boltzmann-integral thermodynamics and comparison with a quadratic oscillator. A meaningful second request asks quantum level-based corrections without supplying their dynamics; the explicitly linked homework cannot currently be retrieved. The classical dominance versus specialized correction is near the boundary, so preserve whole problem as BORDERLINE.'),
(27,'REJECT',[],'theory','Validity of finite effective matrices despite canonical quantum commutators','The relation is named rather than written. A finite-matrix trace proof is mathematical, but the central physical explanation of effective graphene matrices versus canonical Hilbert-space observables needs unsupplied projection/pseudospin and quantum representation theory.'),
(28,'KEEP',[II],'numerical','Zone-folding of a fully given two-band dispersion','The exact dispersion, occupied negative-energy states and cylindrical identification vector are supplied. Periodic wave-phase conditions and sampling the given branches determine curves and gap closure. No derivation of electronic bands, hopping Hamiltonian or quantum transport dynamics is requested.'),
(29,'REJECT',[],'theory','Pigment colour from confined fermionic electron energy levels','A geometric confinement story is supplied, but box quantum spectra, spin/Pauli filling and multi-electron excitation rules are not. Those unsupplied prerequisites centrally determine all absorption wavelengths and colour predictions.'),
(30,'REJECT',[],'theory','Landau spectrum with discontinuous effective electron mass','The formal kinetic Hamiltonian and mass profile are supplied, but momentum representation, magnetic minimal coupling, quantum boundary matching and Landau quantization are not. These specialized quantum dependencies dominate the sole spectrum task.'),
(31,'REJECT',[],'numerical','Near-light-speed photon and particle drag on a spaceship','Full statement spans pp6-7. Relativistic Doppler/aberration, flux transformation and particle energy-momentum relations are not provided. They centrally determine high-speed pressure and saturation; the v-to-zero check does not make the whole task classical.')]
pages=[1,1,1,1,1,1,2,2,2,2,2,3,3,3,3,3,3,3,3,3,4,4,4,5,5,5,6,6,6,6,6]
u={int(r['problem_number']):r for r in c.execute('select * from units where source_file_id=3127')};assert len(u)==31
out=[]
for n,d,dom,fmt,physics,reason in rows:
 assert u[n]['decision'] is None
 out.append(dict(screening_unit_id=u[n]['screening_unit_id'],decision=d,confidence='medium' if d=='BORDERLINE' else 'high',primary_spho_domains=';'.join(dom),required_physics=physics,decision_reason=reason,external_physics_if_any=physics if d in ('BORDERLINE','REJECT') else '',format=fmt,page_start=pages[n-1],page_end=7 if n==31 else pages[n-1],visual_inspection_used=1,solution_used=0,boundary_status='content_boundary_verified',needs_second_review=n in (7,8,23,27,28),evidence=f'Complete actual Ortvay 2013 Q{n}, physical pp{pages[n-1]}-{7 if n==31 else pages[n-1]}, read from verified SHA cache and all seven full-page renders. Pulley/LC geometry and intact field/index/dispersion formulas inspected. Q31 continuation preserved under its parent. Original organizer archive has no worked solution; original source-linked Q26 homework availability checked separately.'))
p=w.ROOT/'reviews/shutdown_ortvay_2013_31.json';w.writejson(p,out);w.decisions(p)
c.execute("update paper_boundary_audit set status='full_paper_boundaries_verified',observed_units=31,evidence=?,checked_at=? where file_id=3127",('Seven physical pages inspected in text and renders: exactly Q1-Q31. Q23 five analysis clauses form one model; Q31 p7 continuation remains same task. No additional experiment, MCQ or unindexed top-level number.',w.now()))
notes={1:'Brand/date exclusion is historical (2013); no universal claim about current ovens. Actual empirical heating/calibration dominates the task.',5:'Evaporation anisotropy/recoil, mass-loss time law and relative mass assumptions are not specified; state assumptions rather than infer a unique orbit law.',20:'Zero London depth is named without explicitly defining flux-exclusion boundary/initial state; retained supplied-model ambiguity.',23:'Classical regime and all torque/angular-momentum laws are explicit. Final divergent mode integral is mathematical within the supplied model, not an assumed quantum theorem.',26:'Original http linked homework returns 403. HTTPS certificate chain fails local validation; a public-byte-only fallback still returns 403 and web tool cannot fetch. Supplement not preserved or treated as inspected. Periodic potential also needs a finite domain/one-cell normalization to define absolute free energy.',28:'Occupied negative-energy states are explicitly stipulated; wrap identification supplies periodicity. Conductive wording interpreted as zero-energy gap closure in that given ideal model.',29:'Text first says n even but compares n=9,11,13; electron/atom indices are inconsistent in source. Quantum spectrum/filling prerequisite remains unsupplied.',31:'No relativistic force/flux model or spectrum/material numerical data supplied; literature permission for estimates does not supply the missing law.'}
for n,note in notes.items():c.execute('update units set source_quality_notes=? where screening_unit_id=?',(note,u[n]['screening_unit_id']))
c.commit()
w.writejson(w.ROOT/'reviews/shutdown_ortvay_2013_q26_supplement_availability.json',{'checked_at':w.now(),'screening_unit_id':u[26]['screening_unit_id'],'url':'http://www-personal.umich.edu/~jbourj/cm/homework%203.pdf','status':'source_linked_quantum_reference_unavailable','checks':['Original HTTP:403','Original HTTPS:certificate-chain failure','Public-byte-only no-credentials HTTPS fallback:403','Web open: inaccessible'],'effect':'Keep complete statement screening as BORDERLINE; quantum model cannot be assumed supplied by an unseen reference. Reference retry remains explicit.'})
print('Saved 31 decisions and full seven-page boundary audit.')
