import workflow as w
c=w.connect();I='I_force_motion';II='II_oscillations_waves';III='III_ideal_gas';IV='IV_thermodynamics';VI='VI_electric_field';VII='VII_magnetic_field';VIII='VIII_induction';IX='IX_em_oscillations_waves';X='X_wave_optics';XI='XI_quantum_light';XII='XII_atomic_nuclear'
rows=[
(1,'KEEP',[I],'theory','Elastic ballistic bounce and rotating-Earth displacement between trees','The equatorial plantation geometry and elastic bouncing set a Newtonian reach/threshold problem. Gravity, rotating-Earth Coriolis motion and impact kinematics provide the required physics; leaf colour and story details do not add biological theory.'),
(2,'KEEP',[I],'theory','Constant-angle descent around a spherical asteroid','The source expressly stipulates the same gliding angle, so no aerodynamic lift law is needed. Local radial/horizontal geometry and a logarithmic-spiral descent determine surface distance.'),
(3,'KEEP',[I],'numerical','Yo-yo unwinding with a changing winding radius','Disk/axle/thread dimensions, inertia and massless no-slip assumptions are supplied. Rotational/translational energy and winding geometry determine speed, acceleration, time and extrema.'),
(4,'KEEP',[I,X],'data_analysis','Inferring geographic coordinates from a supplied sunrise-time table','All observation dates/times and uncertainties were read in the rendered table. Earth rotation, orbital solar geometry, ray/refraction assumptions and weighted fitting determine location estimates; no specialized cosmology is involved.'),
(5,'KEEP',[I,II],'theory','No-slip sphere motion against a vertical cylindrical wall','Rigid sphere/tube geometry and high-friction no-slip condition supply constraints. Newtonian force/torque and rolling kinematics determine center motion and sustained contact.'),
(6,'KEEP',[I],'numerical','Ideal skate trajectories on a rotating rink','The blade permits frictionless motion along itself and prevents transverse motion, an explicit mechanical constraint model. Newton equations and blade orientation/inertia constraints determine trajectories; nonholonomic mathematics is not outside physics.'),
(7,'KEEP',[I,VI],'theory','Slow evolution of Coulomb orbits under supplied quadratic drag','The exact drag, negligible gravity/induction and initial orbit regimes are specified. Electrostatic central force, torque and energy loss determine orbital changes and their elementary interpretation.'),
(8,'KEEP',[I],'theory','Newtonian tidal torque expressed through rigid inertia','The central potential and small spatial variation supply a gravity-gradient expansion. Integrating ordinary gravitational torque and using inertia tensors gives both general and rotating spheroid cases.'),
(9,'KEEP',[I,II],'theory','Rolling stability of a conical barrel under prescribed drag','The rail contact/body shape and velocity-linear drag define rigid mechanical dynamics once dimensions/inertia are declared. Linear stability of coupled rolling equations and possible shape design use Newtonian mechanics and mathematics.'),
(10,'KEEP',[I,IV],'theory','Apparent solar paths and seasons on a specified fast-year planet','Axial orientation, spin/year ratio and Earthlike gross thermal parameters are specified. Rotating solar geometry and seasonal irradiation/thermal-inertia reasoning explain the paths and qualitative seasons; no quantitative unsupplied climate model is required.'),
(11,'KEEP',[I,X],'theory','Uncovered population fraction for an equatorial synchronous satellite ring','Spherical visibility geometry and uniform surface population are supplied. Pole/equator effective gravity determines spin versus Newtonian mass gravity, which sets the synchronous radius and polar blind caps.'),
(12,'KEEP',[II],'numerical','Sound-wave caustic from a uniformly accelerating aircraft','The accelerating path is explicit. Envelopes of ordinary spherical sound fronts locate folds/cusps and the enhanced boom; no nonlinear shock constitutive model is requested.'),
(13,'KEEP',[I,X],'theory','Underwater apparent star paths through refraction','Sky declination/rotation and the underwater viewing context require ordinary Earth geometry and Snell refraction. Plotting apparent night trajectories is mathematical optics, not specialized astrophysics.'),
(14,'KEEP',[II,IX],'numerical','Wavefront envelope for a circular superluminal-in-medium source','The source supplies the wave speed and describes radiation as propagating fronts, asking only their geometry. Retarded circles and envelope calculus determine wavefront curves; no unsupplied Cherenkov emission-rate theory is required.'),
(15,'KEEP',[I,II],'theory','Mass-chain modes under an explicitly supplied delayed boundary','Masses/springs and time-shifted boundary equation are supplied. Newtonian chain equations and delayed eigenvalue algebra determine spectra and orthogonality; possible nonstandard complex modes follow the given mathematical model.'),
(16,'KEEP',[I,II],'numerical','Defect modes of a classical triangular spring lattice','The omitted spring and allowed planar motions were checked in the drawing. Newtonian spring-force dynamical matrices and numerical defect eigenmodes supply all required physics.'),
(17,'REJECT',[],'theory','Rotating solid-sphere deformation requiring unsupplied continuum elasticity','Naming Hooke law does not supply tensor stress-strain/Poisson response or the Navier-Lame elastic boundary equations for a distributed 3D deformation. That substantial continuum elastic model is central to both polar and equatorial displacement.'),
(18,'KEEP',[I],'numerical','Hydrostatic capillary gas-bubble shapes at a vessel floor','Density contrast, surface tension, contact angle and numerical values are supplied. Hydrostatic pressure, curvature tension and surface equilibrium determine stable shapes/sizes through ordinary capillary physics.'),
(19,'REJECT',[],'theory','Blowing versus suction through unsupplied Navier-Stokes symmetry','The full task explicitly demands properties of a named viscous nonlinear continuum-flow equation, but does not supply it or its boundary/viscosity model. That specialized hydrodynamic law is the central prerequisite.'),
(20,'KEEP',[II],'theory','Axial near-field interference from a circular ultrasound emitter','Disk source, frequency, sound speed and last axial intensity zero define ordinary wave interference/diffraction. Integrating coherent aperture contributions gives distance dependence and disk diameter; piezoelectric crystal engineering is not requested.'),
(21,'KEEP',[I,II,VII],'experimental','Design and stability of a contactless magnetic pendulum escapement','The task allows designing the mechanism. Conventional magnetic force/torque, oscillator energy transfer and damping determine a workable design; numerical small-drive/stability analysis addresses chaos avoidance without an unsupplied specialized physical law.'),
(22,'KEEP',[I,VII],'numerical','Force and torque of a rotating charged rigid sphere in a field gradient','Uniform charge/mass and given B geometries supply the model. Integrated Lorentz force/torque and rigid angular momentum yield center/spin equations, solutions and trajectory comparisons.'),
(23,'KEEP',[IX,X],'theory','Optical transfer matrix for a supplied graded-index slab','The exact index profile, thickness/wavelength and thin-layer limit method are supplied. Conventional Maxwell boundary continuity, reflection/transmission and wave propagation determine the limiting transfer matrix.'),
(24,'REJECT',[],'numerical','Antimatter rocket optimization at relativistic cruise speed','Complete fuel-efficiency rules are given, but relativistic exhaust momentum, spacecraft variable-mass equations and proper-acceleration/power transformations are not. Those unsupplied SR dependencies centrally determine optimal fuel and the requested full mission.'),
(25,'REJECT',[],'theory','Nordstrom scalar-relativistic bound orbits with a partial force law','A scalar four-force is supplied but four-velocity normalization, mass coupling, energy definitions and proper-to-coordinate-time transformations are not. Central orbit dynamics requires those unsupplied relativistic rules.'),
(26,'REJECT',[],'theory','Inverse-rest-mass hypergravity with relativistic evolution','One four-force formula is supplied, but changing invariant mass/energy, proper time and relativistic momentum definitions are not. These control the particle fate and onset of the explicitly asked relativistic effects.'),
(27,'BORDERLINE',[I],'theory','Classical gravitational ring oscillations with semiclassical quantization','Ring gravity, equilibrium release point and period are ordinary Newtonian work. A linked meaningful final request asks Bohr-Sommerfeld energy levels for general parameters without supplying its action/domain rule. Classical and specialized semiclassical work are mixed near the whole-problem boundary.'),
(28,'KEEP',[I,XI],'theory','Positronium size from two-body Bohr scaling','The sole request is a hydrogenlike atomic size ratio. Ordinary two-body reduced mass, Coulomb circular motion and the syllabus Bohr quantization give the ratio; annihilation is context and needs no decay theory here.'),
(29,'BORDERLINE',[XII],'theory','Closed-shell counts from a given oscillator energy expression','The energy formula is supplied and supports substantial integer degeneracy counting. But quantum-number ranges, spin multiplicity and the magic-number shell-filling prescription are not operationally stated. Whether ordinary atomic/nuclear prerequisites suffice for that intended counting is genuinely near the boundary.'),
(30,'REJECT',[],'theory','Electronic Peierls dimerization requiring unsupplied tight-binding and filling rules','Hopping dependence and elastic cost are given, but electronic Hamiltonian action, band derivation, fermionic filling and ground-state energy integral rules are not. They centrally determine all dispersions and the dimerization optimum.'),
(31,'REJECT',[],'theory','Electron orbitals and spin-orbit response under an unsupplied Pauli equation','Field and confinement are given, but Pauli dynamics, magnetic minimal coupling, quantum perturbation and measurement rules are not. They dominate orbital calculation and Stern-Gerlach interpretation.'),
(32,'REJECT',[],'theory','Dirac versus Schrodinger spin scattering from formal Hamiltonians','Formal Hamiltonians alone do not supply momentum/Pauli representations, wavefunction evolution, delta matching and flux/probability rules. Those unsupplied quantum prerequisites control the whole scattering matrix comparison.'),
(33,'REJECT',[],'numerical','Arbitrary-spin Dirac Landau spectra and quantum ladder algebra','A symbolic spin-momentum Hamiltonian is given, but spin-matrix representations, magnetic minimal coupling, creation-operator commutators and quantum Landau reduction are not. Those central prerequisites are unsupplied despite the code-writing format.'),
(34,'REJECT',[],'data_analysis','Laboratory photon-energy distribution from moving positronium annihilation','Opposite photons in the COM are stated, but Lorentz photon energy/angle transformation and atom velocity ensemble are not. The entire requested extrema/mean/distribution depends on these unsupplied relativistic ingredients; separate Q28 Bohr sizing is not inherited.'),
(35,'KEEP',[I,III],'experimental','Controlled material subdivision and atom-count estimation','Material and cutting method are explicitly open choices. Mechanical preparation, mass/volume/density, molecular mass/Avogadro counting and measurement resolution can define a reproducible experiment/ranking; advanced nanofabrication is not structurally required.'),
(36,'KEEP',[III],'theory','Effusive escape for a prescribed gas velocity distribution','Kinetic particle flux through a hole and a declared isotropic well-mixed dilute-gas approximation determine escape fractions and fixed-speed decay. Velocity integration and survival mixture are ordinary kinetic theory; collisionless wall-memory alternatives are noted as model limitations.'),
(37,'KEEP',[III,VII,XII],'experimental','Thermal magnetic-curvature identification of hydrogen isotopes','The oven/field/track measurement is specified. Thermal kinetic energy distributions and Lorentz curvature scale as square-root mass over charge, allowing isotope ratios and mixture fitting without plasma-ionization-rate theory.'),
(38,'KEEP',[I,XII],'theory','Decay thresholds with an explicitly supplied species-dependent dispersion','The full E-squared momentum/mass relation and each species limiting-speed condition are explicitly supplied. Energy/momentum conservation, collinear threshold optimization and asymptotic expansion determine both processes without deriving Lorentz transformations or the underlying new field theory.'),
(39,'REJECT',[],'numerical','Gravitational neutrino travel-time correction requiring unsupplied GR','Only distance, alleged time anomaly and potential context are supplied. Spacetime/light-travel delay and observer clock rules are not; these GR prerequisites are the complete correction mechanism.'),
(40,'KEEP',[],'data_analysis','Optimization under a supplied toy lifetime utility and annuity model','The full utility, wealth recursion, annuity pricing and inflation assumptions are explicit. Conditional survival data, sums and constrained optimization determine all requests without financial theory; original linked official real life-table data were preserved and inspected.'),
(41,'KEEP',[I],'numerical','Frictionless straight Earth-rotating coaster and latitude constraints','Complete long story p8 supplies a rigid straight rotating rail and synchronous endpoints. Newtonian gravity, centrifugal/Coriolis force, potential-energy integrals and contact constraints determine travel and latitude/direction failures.'),
(42,'KEEP',[IV,XI],'numerical','Self-contained blackbody greenhouse and chosen-albedo climate model','All three model stages are supplied: incoming solar flux, transparent/absorbing isotropically reradiating layer and tunable albedo. Ordinary radiation/energy balance and small temperature-feedback stability determine temperatures and scenarios; actual climate microphysics is deliberately replaced by the given model.')]
pages=[1,1,1,2,2,2,2,2,2,3,3,3,3,3,3,3,4,4,4,4,4,4,4,5,5,5,5,5,5,6,6,6,6,6,7,7,7,7,7,8,8,9]
u={int(r['problem_number']):r for r in c.execute('select * from units where source_file_id=3129')};assert len(u)==42
out=[]
for n,d,dom,fmt,physics,reason in rows:
 assert u[n]['decision'] is None
 out.append(dict(screening_unit_id=u[n]['screening_unit_id'],decision=d,confidence='medium' if d=='BORDERLINE' else 'high',primary_spho_domains=';'.join(dom),required_physics=physics,decision_reason=reason,external_physics_if_any=physics if d in ('BORDERLINE','REJECT') else '',format=fmt,page_start=pages[n-1],page_end=pages[n-1],visual_inspection_used=1,solution_used=0,boundary_status='content_boundary_verified',needs_second_review=n in (14,17,20,28,34,38,40,42),evidence=f'Complete actual registered Ortvay 2011 Q{n}, physical p{pages[n-1]}, read from verified SHA cache and all nine rendered pages. Exact sunrise table, spring-defect geometry, operator/dispersion formulas and climate diagram inspected. Source heading misprints 2010; registered provenance retained. Q40 original CDC-linked life table additionally preserved/read. All lettered/numbered internal clauses remain whole tasks; organizer archive provides no acquired worked solution.'))
p=w.ROOT/'reviews/shutdown_ortvay_2011_42.json';w.writejson(p,out);w.decisions(p)
c.execute("update paper_boundary_audit set status='full_paper_boundaries_verified',observed_units=42,evidence=?,checked_at=? where file_id=3129",('All nine physical pages inspected in cache and renders: exactly Q1-Q42. Q38 internal 1/2 and Q42 model stages 0/1/2 are subparts, not separate tasks. Q28 and Q34 are separate printed positronium questions with different requirements, not aliases. Q40 life-table links remain source associations. No omitted top-level experiment/MCQ.',w.now()))
notes={1:'Rebound restitution and launch/contact details not numerically fixed; elastic idealization and rotating-Earth geometry must be stated.',4:'Geolocation requires solar ephemeris/refraction and horizon assumptions. Supplied timings/uncertainties preserved; exact unique coordinates are not guaranteed without those conditions.',6:'Mass/inertia, stance/blade orientation evolution and idealization must be declared; blade transverse constraint is explicitly supplied.',9:'Body dimensions, mass distribution and exact rail geometry are not numerically supplied; stability threshold remains parametric under a declared rigid model.',10:'Qualitative seasonal irradiation model is specified; exact climate evolution is not determined by gross Earthlike data alone.',14:'Only wavefront geometry is asked, not microscopic Cherenkov intensity or spectral law.',15:'Delayed boundary can produce nonstandard/non-Hermitian spectral or complex modes; do not impose usual periodic orthogonality automatically.',17:'Scalar Hooke-law name does not provide tensor elasticity/Poisson response needed for the rotating solid sphere.',20:'Uniform coherent piston-source idealization and use of the last axial zero are conventional assumptions; piezoelectric constitutive theory not required.',27:'Bohr-Sommerfeld is named without action/phase/boundary quantization expression.',29:'Energy is given, but quantum-number ranges, spin count and closed-shell/magic-number definition are not written.',34:'Atom speed distribution and laboratory relativistic photon transformation are unspecified. Distinct from Q28 atomic sizing.',36:'Effusive well-mixed/isotropic approximation must be declared. Collisionless finite-container geometry and wall correlations could change late-time escape and are not specified.',38:'Complete modified dispersion is actually supplied for all species. Numerical particle masses are not provided, so threshold results are parametric; no unsupplied weak-interaction rate is requested.',40:'Original portal permits a chosen real table. Preserved historical official US 2007 report published September 2011, total-population pp8-9. Timing convention for annual spending and unspecified insurer margin remain explicit model choices.',42:'Albedo function is intentionally contestant-designed; this toy model is not an asserted quantitative prediction of real climate.'}
for n,note in notes.items():c.execute('update units set source_quality_notes=? where screening_unit_id=?',(note,u[n]['screening_unit_id']))
for r in u.values():c.execute("update units set source_quality_notes=coalesce(source_quality_notes,'')||? where screening_unit_id=?",(' Physical header prints contest year 2010 although registered official-year source is 2011 and contained observation dates extend into 2011; raw/provenance not changed.',r['screening_unit_id']))
c.commit();print('Saved 42 decisions and full nine-page boundary audit.')
