"""One-time five parent decisions; preserve simulator archive and instructions."""
import json,zipfile,hashlib
import workflow as w
c=w.connect()
rows=[
('raw::323',1003,4,'theory','I_force_motion;III_ideal_gas;VII_magnetic_field','Given two magnetic-moment orientations, classical dipole-gradient force, long-wire magnetic fields, beam kinematics and uncertainty','The two allowed atom moments +/-mu along x are explicitly assumed, not to be derived using spin operators. C3 explicitly supplies the air-gap field assumption and exempts its derivation. Remaining A-H is equipartition (given), classical magnetic force/fields, differentiating geometry, trajectories and error propagation.',1,True),
('raw::324',1010,4,'theory','I_force_motion;II_oscillations_waves','Rotating-hoop bead force balance, supplied friction model, equilibrium stability, potential Taylor expansion and given magnetic-transition analogy','The full A-C parent supplies the free-body diagram, restriction to the shown forces, polar acceleration, friction rule, Taylor expansions and small-oscillation formula. Magnetic Landau free energy and magnetization law are explicitly supplied only for comparison with a mechanically derived bifurcation. No critical-fluctuation, microscopic magnetism or advanced thermodynamic prerequisite is required.',0,True),
('raw::325',1016,4,'theory','VI_electric_field;II_oscillations_waves;IX_em_oscillations_waves;X_wave_optics','Uniform-cloud electrostatic restoring force, driven oscillator, dimensionally specified radiation model, intensity-loss ODE and horizon geometry','The molecule is explicitly a rigid uniform spherical charge cloud. Gauss/Coulomb force and the driven oscillator close A. B lists every radiation variable and supplies the dimensionless coefficient, so dimensional analysis gives dipole power without deriving a specialized radiation law. Intensity/power loss relations are given; aerosol cross section dependence and coefficient supplied. Geometry and elementary attenuation close D-G.',0,True),
('raw::326',1022,5,'experimental','VII_magnetic_field;VIII_induction;I_force_motion','Given dipole field, magnetometer location/calibration, graph-based falling-magnet speed and hidden pipe lengths','The full A-B simulation experiment supplies both bar-magnet field formulas, point-dipole approximation and m*y-double-dot=m*g-k*y-dot. Hall-effect microscopic transport and eddy-current field derivation are not requested. Central work locates a sensor, fits the dipole moment, inverts magnetic-field data and infers velocities/section lengths. Source-linked simulator archive preserved with provenance and limited runtime validation.',0,False),
('raw::327',1026,4,'experimental','I_force_motion;II_oscillations_waves','Classical sound Doppler effect with propagation delay, circular-plus-linear source kinematics, triangulation and experimental parameter fitting','The complete A1-A7 task is a single sound-simulation experiment with speed of sound and subsonic source specified. Ordinary sound Doppler and retarded travel-time geometry close all parameter inference. Official solution uses stationary detectors for the meaningful inference, remaining available despite the preserved simulator moving-detector input bug. No relativity or specialist inverse-wave theory required.',1,True)]
for uid,fid,*rest in rows:
 u=c.execute('select * from units where screening_unit_id=?',(uid,)).fetchone();assert u and u['decision'] is None and u['source_file_id']==fid
runtime=json.loads((w.ROOT/'reviews/shutdown_apho_2022_simulator_validation.json').read_text())
archive=w.ROOT/runtime['archive'];assert w.digest(archive)==runtime['sha256']
out=[]
for uid,fid,np,fmt,dom,phy,reason,sol,focus in rows:
 out.append(dict(screening_unit_id=uid,decision='KEEP',confidence='high',primary_spho_domains=dom,required_physics=phy,decision_reason=reason,external_physics_if_any='',format=fmt,page_start=1,page_end=np,visual_inspection_used=1,solution_used=sol,boundary_status='content_boundary_verified',needs_second_review=focus,evidence=f'APhO 2022 file {fid}: all {np} physical statement pages read in full SHA-cached extraction and all actual rendered pages viewed, including every diagram and equation. One complete top-level parent per PDF. Theory transcriptions 1007(2p),1014(3p),1019(2p) also read and all rendered pages checked; same respective tasks, no extra units. S1 1004 pp2-4 text and p2 image; S5 1027 all12 text and pp2/4/5/7/12 images inspected. Experiment instructions1002 all3 text/images. Preserved original simulator archive CRC/SHA and headless runtime checks recorded.'))
p=w.ROOT/'reviews/shutdown_apho_2022_5.json';w.writejson(p,out);w.decisions(p)
for uid,fid,np,fmt,*rest in rows:
 c.execute("update paper_boundary_audit set status='full_paper_boundaries_verified',observed_units=1,evidence=?,checked_at=? where file_id=?",(f'All {np} physical pages inspected. Single independently headed {fmt} problem; every internal letter and task number belongs to this parent. No omitted independently headed task. Transcriptions, when present, checked against original with same complete subtask list.',w.now(),fid))
for uid in ['raw::323','raw::324','raw::325']:
 c.execute('insert or ignore into unit_files values (?,?,?,?)',(uid,1000,1059,'instructions'))
for uid in ['raw::326','raw::327']:
 for fid,did,role in [(1002,1060,'instructions'),(1005,1061,'supplementary')]:
  f=c.execute('select * from source_files where id=?',(fid,)).fetchone();assert w.digest(w.RAW/f['local_path'])==f['sha256']
  c.execute('insert or ignore into unit_files values (?,?,?,?)',(uid,fid,did,role))
 c.execute('insert into screening_references values (?,?,?,?,?,?,?,?,?)',('apho2022_simulator_archive_'+uid.split('::')[1],uid,runtime['archive_url'],runtime['archive'],runtime['sha256'],runtime['byte_size'],None,'Essential source-linked simulation archive pinned at commit '+runtime['commit']+'. Both statement PDFs SHA-identical to immutable raw originals. Simulator authors match printed source. CRC/SHA and isolated local headless loading checked; known acoustic moving-detector defect disclosed in reviews/shutdown_apho_2022_simulator_validation.json. Archive original files unmodified; serve repository root over HTTP because assets use root-relative URLs.',w.now()))
c.execute('update units set source_quality_notes=? where screening_unit_id=?',('The statement explicitly restricts forces to the given in-plane free-body diagram. Its friction f=+1 equilibrium is a prescribed limiting branch; it is not a complete 3D rotating-contact/Coriolis model. Solve the supplied mechanical model rather than add unsupplied forces.','raw::324'))
c.execute('update units set source_quality_notes=? where screening_unit_id=?',('Required original simulation preserved in pinned source archive. Root-relative libraries require an HTTP server at the extracted repository root, not opening standalone HTML. Runtime check covered initial rendering/field/chart and measurement samples, not full drag/drop parameter-inference experiment. No actual contestant dataset generated.','raw::326'))
c.execute('update units set source_quality_notes=? where screening_unit_id=?',('Preserved simulator ABB/simulation.js passes v*cos(gamma) for BOTH detector vx and vy and treats gamma input as radians despite degrees label. Runtime v=10,gamma=0 demonstrably gives [10,10,0], not [10,0,0]. Official key uses stationary-detector methods, which remain functional. Key 1027 rendered p5 prints f_min=5327.82 Hz for the far-right substitution, inconsistent with its own ~543.96 Hz extrema and reported f0~990 Hz. Source archive also contains identical bytes for Experimental_Solution 1.pdf and 2.pdf; canonical acoustic key is raw1027, not that mislinked archive PDF. No source repaired.','raw::327'))
c.commit()
w.writejson(w.ROOT/'reviews/shutdown_apho_2022_variant_and_supplement_boundaries.json',dict(checked_at=w.now(),variant_relationships=[dict(unit='raw::323',original=1003,transcription=1007,subtasks='A1 B1 C1-3 D1 E1 F1 G1 H1'),dict(unit='raw::324',original=1010,transcription=1014,subtasks='A1 B1-9 C1-2'),dict(unit='raw::325',original=1016,transcription=1019,subtasks='A1-4 B1-2 C1-3 D1 E1 F1 G1')],evidence='Entire original/transcription texts and all rendered pages inspected. Alternate file provenance already belongs to the same unit; no additional logical alias unit or unique-problem count added. Instructions1000/1002 supply general examination directions/constants only, not independently graded problems. Presentation1005 all18 text pages read: repeats the two experiments and sample explanatory methods/data, no extra independent task. No claim all presentation images inspected.',simulator_validation=runtime['validation_status']))
reviews=[
dict(screening_unit_id='raw::323',detail='Theory QC Random(2026100433) selects raw::323. All four statement images and two-page transcription reviewed. Fixed +/-mu_x supplied explicitly, and C3 air-gap continuation assumption supplied/exempted. Classical F_x=mu*dB/dx and constant-acceleration then free-flight geometry confirmed by official key1004 p2 image; no quantum spin measurement/state theory or boundary-field derivation is needed. Whole KEEP confirmed.'),
dict(screening_unit_id='raw::324',detail='Focused specialized-model check. The actual full statement supplies Landau polynomial and M=M0*(1-T/Tc)^.5, asking only an analogy to bead equilibrium. Mechanical equilibrium cos(theta0)=g/(omega^2*R) and Taylor expansion give the square-root onset through elementary calculus. Potential defined by tangential force and oscillation formula given. Friction/force model restriction disclosed. Whole KEEP; no unsupplied Landau/critical theory.'),
dict(screening_unit_id='raw::325',detail='Focused radiation prerequisite check. Charge-cloud electrostatics gives linear restoring force. Given variables imply s proportional p0^2*omega^4/(epsilon0*c^3), and coefficient1/(12*pi) explicitly supplied. Thus deriving radiation fields is not required. Given I=.5*c*epsilon0*E0^2 and S=n0*s close loss ODE; aerosol geometric coefficient also given. All A-G inside operational scope and supplied models. Whole KEEP.'),
dict(screening_unit_id='raw::327',detail='Experiment QC Random(2026100434) and focused simulator/source conflict check. Full four-page task and twelve-page acoustic key read; rendered pp2/4/5/7/12 establish classical Doppler, arrival-time triangulation and stationary-detector extrema inference. Preserved original JS archive contains SHA-identical original statements and explicit author credits. Headless stationary detector5-55s gives2500 finite samples and min543.5788577Hz, consistent with key trend; separate v10/gamma0 test proves moving-detector input bug. No simulated QC output is represented as an actual laboratory measurement. Archive mislinked solution2 and key p5 frequency typo recorded. Physical scope KEEP; original code retained unmodified.')]
p=w.ROOT/'reviews/shutdown_apho_2022_focused_seeded_4.json';w.writejson(p,reviews);w.review(p)
print('Saved five 2022 decisions/audits, four focused/QC reviews and verified simulator/source associations.')
