"""Historical one-time source-grounded batch; do not replay after commit."""
import json
import workflow as w
c=w.connect()
rows=[
('raw::328',1031,4,'theory','I_force_motion;II_oscillations_waves','Mass continuity, momentum/pressure impulse, supplied bulk modulus, Bernoulli flow and wave reflections with valve recurrence','All A-D are closed by the explicitly inviscid one-dimensional pipe, bulk modulus relation and valve contraction table. Traveling compression speed and excess pressure follow from mass/momentum and compressibility; reflections use fixed/free pressure boundaries. The substantial stepped-closing recurrence uses these results and ordinary flow energy, not unsupplied viscous-fluid modes.'),
('raw::329',1035,5,'theory','IX_em_oscillations_waves;X_wave_optics;XI_quantum_light','Supplied anisotropic constitutive/Maxwell model, ray and phase velocity, stationary travel time, nonlinear wave phase matching, supplied two-photon amplitude/intensity and CHSH models','The statement supplies anisotropic D(E), Maxwell vector equations, energy/flux, quadratic susceptibility, photon energy/momentum and the prepared state. Crucially C4 defines the state coefficients as field-amplitude products and the probability as proportional to intensity products after superposition. Linear polarizer projection and normalization therefore close C4 without an unsupplied Born/state-measurement law. C5 defines the correlation observable and CHSH bound; only trig/probability algebra is requested. Most meaningful work is classical wave optics with provided models.'),
('raw::330',1040,5,'theory','VII_magnetic_field;VIII_induction;II_oscillations_waves','Supplied magnetic monopole/image and film diffusion models, Ohmic induction, superposition, dipole forces, given skin depth, equilibrium and small oscillations','Monopole field and force, initial images, magnetic diffusion PDE, moving-image continuation and discrete source construction are explicitly supplied. Thin-film integration/symmetry and characteristic solution are mathematical analysis of that model. Skin depth and frequency prescription are given; effective penetration thickness is its ordinary stated physical interpretation and only 0.7 points. Superconductivity is explicitly prescribed as complete field exclusion via sigma to infinity; no London, BCS or unsupplied Meissner derivation is requested.'),
('raw::331',1044,12,'experimental','I_force_motion;X_wave_optics','Laser/PSD calibration, stability averaging, supplied cantilever and bilayer thermal-curvature models, regression and coverage-ratio calibration','The full A-D experiment supplies delta=F*L^3/(3*E*I), rectangular I, bilayer strain/moment compatibility AND final curvature and displacement formulas. No beam differential equation or Timoshenko constitutive theory must be derived. Molecular absorption uses a fully supplied empirical response calibrated on known coverage, not microscopic van der Waals/protein theory. Dominant work is alignment, measurement, plotting and inference using the given models.'),
('raw::332',1047,7,'experimental','X_wave_optics','Double-slit calibration, grating diffraction/triangular close-packing geometry, visible/IR spatial sampling, rectangular grid dimensions and uncertainty','All A-E use classical interference/diffraction, screen-angle geometry and measurement. The statement explicitly describes densest two-dimensional sphere packing with varying orientations and a rectangular array/grid. Ring spacings yield row distance, sphere diameter follows triangular geometry, and cross/fine spots give reciprocal spacings and rotation. No photonic-band structure, dynamical scattering or unsupplied solid-state model is required.')]
for uid,fid,*rest in rows:
 u=c.execute('select * from units where screening_unit_id=?',(uid,)).fetchone();assert u['decision'] is None and u['source_file_id']==fid
sv=json.loads((w.ROOT/'reviews/shutdown_apho_2021_software_static_validation.json').read_text());f=c.execute('select * from source_files where id=1034').fetchone();assert w.digest(w.RAW/f['local_path'])==sv['sha256']
out=[]
for uid,fid,np,fmt,dom,physics,reason in rows:
 out.append(dict(screening_unit_id=uid,decision='KEEP',confidence='high',primary_spho_domains=dom,required_physics=physics,decision_reason=reason,external_physics_if_any='',format=fmt,page_start=1,page_end=np,visual_inspection_used=1,solution_used=1,boundary_status='content_boundary_verified',needs_second_review=True,evidence=f'APhO2021 file{fid}: all{np} SHA-cached statement pages read and ALL rendered physical pages actually viewed. One headed parent, all internal parts retained. S1 1032 all8 text and pp1/6/7 images; S2 1036 pp7-10 text and pp9/10 images; S3 1041 all7 text and pp2/4/5/6 images; E1 key1045 pp1-4 text/p4 image; E2 key1049 pp1-3 text/pp1/3 images. Instructions1030 all2 text and images. Essential existing software1034 SHA/CRC, every ZIP member SHA and static managed-code experiment identifiers checked; no executable launched or experiment performed.'))
p=w.ROOT/'reviews/shutdown_apho_2021_5.json';w.writejson(p,out);w.decisions(p)
for uid,fid,np,fmt,*rest in rows:
 c.execute("update paper_boundary_audit set status='full_paper_boundaries_verified',observed_units=1,evidence=?,checked_at=? where file_id=?",(f'All{np} actual pages inspected: one complete top-level {fmt} parent, with all internally numbered/lettered tasks belonging to it. No omitted independent question. Experiment files labelled Q1/Q2 despite acquisition numbering4/5; source relationship retained.',w.now(),fid))
for uid in ['raw::331','raw::332']:
 for fid,did,role in [(1030,1089,'instructions'),(1034,1090,'experimental_data')]:
  f=c.execute('select * from source_files where id=?',(fid,)).fetchone();assert w.digest(w.RAW/f['local_path'])==f['sha256']
  c.execute('insert or ignore into unit_files values (?,?,?,?)',(uid,fid,did,role))
 c.execute('update units set source_quality_notes=? where screening_unit_id=?',('Required shared Windows Unity simulator1034 preserved intact once with both source relationships. ZIP CRC and full member hashes verified; app.info identifies APHO, managed assembly includes CantileverBeam/PointLoadBeam and Diffraction classes/scene names matching both statements. Static validation only; executable not launched, runtime compatibility and simulated measurement datasets not validated. Printed instructions1030 specify Windows10/8GB RAM.',''+uid))
c.execute('update units set source_quality_notes=? where screening_unit_id=?',('Official key1036 p9/p10 has inconsistent C4 listings: p10 swaps perpendicular probability expressions relative to p9. C5 trig line equates sin(2a)sin(2b)-cos(2a)cos(2b) to -cos(2(a-b)); the identity gives -cos(2(a+b)). The supplied symmetric example still gives CHSH magnitude2sqrt(2). These are actual rendered-source errors, not extraction repairs or grounds for importing unsupplied quantum theory.','raw::329'))
c.commit()
reviews=[
dict(screening_unit_id='raw::328',detail='Theory QC Random(2026100435) selects328, plus focused water-hammer prerequisite check. Whole statement and official8-page solution read. Rendered key1 derives pressure change by momentum impulse and continuity; bulk modulus closes sound speed. Rendered key6/7 derive the four-step recurrence through fixed/free reflections and Bernoulli valve relation/graph intersections. No Navier-Stokes or unsupplied constitutive law. KEEP confirmed.'),
dict(screening_unit_id='raw::329',detail='Focused supplied quantum/anisotropic model review. Actual statementp4 expressly defines field-amplitude coefficients and intensity-product probability after superposition, while p5 supplies CHSH bound and observable. Official C4/C5 renders9/10 show only linear polarizer projection, squared amplitudes and elementary probabilities/trig. C3 official7/8 uses supplied refractive dispersion, Taylor and vector geometry, not additional photon interaction theory. Key sign/probability conflicts recorded. Whole KEEP; no arbitrary exemption for a quantum title.'),
dict(screening_unit_id='raw::330',detail='Focused specialized magnetic model review. Statementp3 supplies full film PDE and p4 explicitly permits extending image picture and describes +/- hopping sources. Official1041 all7 text, images2/4/5/6 confirm integration/symmetry, supplied skin-depth effective thickness and classical dipole force/oscillations. Statementp5 supplies field exclusion sigma to infinity; no superconducting microscopic theory. Skin correction is peripheral and uses defined penetration depth. KEEP confirmed.'),
dict(screening_unit_id='raw::331',detail='Focused unsupplied beam-theory check. Actual p7 supplies entire bending compliance/I; p9/10 supplies bilayer strains, moment balance and complete final curvature/displacement formulas. Key1045 p4 image obtains C1 from plotted supplied-model displacement versus PSD measurements, not solving beam-shape PDE. D empirical coverage response is given and calibrated. Whole KEEP confirmed; software preserved, no simulated experiment falsely claimed.'),
dict(screening_unit_id='raw::332',detail='Experiment QC Random(2026100436) selects332. All seven statement images inspected, including actual close-packed sphere micrograph and every A-E task. Key1049 pp1-3 text/pp1/3 renders give ordinary d=m*lambda/sin(atan(S/L)) and a/d=2/sqrt(3), confirming phase geometry/triangular packing. Visible and IR spot spacing inference uses same classical wave-optics relation. No advanced solid-state scattering model needed. Whole KEEP; existing software/provenance verified.')]
p=w.ROOT/'reviews/shutdown_apho_2021_focused_seeded_5.json';w.writejson(p,reviews);w.review(p)
print('Saved five2021 whole-parent decisions/audits and five focused/QC reviews; shared original instructions/software associations preserved.')
