"""Explicit judgements after reading all statements and all twelve renders."""
import hashlib
import workflow as w
c=w.connect();I='I_force_motion';II='II_oscillations_waves';III='III_ideal_gas';IV='IV_thermodynamics';VI='VI_electric_field';VII='VII_magnetic_field';IX='IX_em_oscillations_waves';X='X_wave_optics';XI='XI_quantum_light';XII='XII_nuclear_physics'
rows=[
(1,'BORDERLINE',[X],'theory','Unequal coloured flag areas and perceived visual width','The actual colour bands were inspected. Optical irradiation/chromatic imaging may explain the proportions, but no perceptual response or optical-eye model is supplied. The qualitative intended mechanism is uncertain rather than inferable from the historical flag title.'),
(2,'KEEP',[II,X],'theory','Repeated focused sound echoes in a truncated spherical hall','The hall photos and intact height/radius/sound-speed numbers were inspected. Near-axis reflection geometry and repeated sound travel/focusing explain which returns are audible; no specialized acoustic constitutive law is needed.'),
(3,'REJECT',[II],'theory','Spontaneous roll-wave instability in runoff down an inclined ramp','Steady input does not specify shallow-water dynamics, frictional flow closure or instability selection. Those unsupplied fluid-dynamical prerequisites centrally determine wave emergence, speed and spacing.'),
(4,'KEEP',[I],'theory','Deterministic coin flipping and probability under parameter spread','Thin rigid-body rotation, ballistic flight and the no-rebound landing assumptions are explicit. Newtonian motion and ordinary probability over uncertain launch parameters determine heads/tails and stochasticity.'),
(5,'KEEP',[X],'numerical','Repeated ray reflections between spherical ornaments','Source/observer geometry and sphere separations are supplied. Ordinary reflection and iterative ray geometry give bright spots, infinite-bounce trajectories and asymptotic positions.'),
(6,'KEEP',[I],'theory','Central-force potentials producing specified common-endpoint trajectories','Newtonian central force, angular momentum and energy permit inverse orbital construction. The special trajectories are mathematical constraints, not a request for an unsupplied physical force model.'),
(7,'BORDERLINE',[I],'theory','Nonunique Newtonian dome motion followed by a quantum surface problem','The dome shape and scalar equation are supplied, supporting substantial classical solution and model-validity work. The mandatory quantum surface eigenstate requires unsupplied Schrodinger/curved-surface Hamiltonian rules. Whole-problem conceptual weight is near the boundary; subparts are not split.'),
(8,'KEEP',[I,II],'theory','Normal modes of a finite free-ended equal-mass spring chain','Hooke forces and Newtonian acceleration give the finite tridiagonal eigenproblem. Free-end conditions and all components are specified; diagonalization adds mathematics only.'),
(9,'KEEP',[I],'theory','Gravitational work on the surface of a two-density sphere','Coulomb-type Newtonian gravitational integration over the two homogeneous hemispheres determines potential differences; arbitrary surface endpoints introduce mathematical quadrature.'),
(10,'KEEP',[I,II],'theory','Rolling small-oscillation bounds for a singly stable convex body','Rigid-body inertia and gravitational height curvature determine frequency near stable equilibrium. The unspecified family of shapes may yield only trivial bounds, but no external physical law is needed.'),
(11,'KEEP',[I,II],'experimental','Inferring rod Young modulus from axial collision contact time','The rod-end collision apparatus was checked. Ordinary Hooke stress/strain, longitudinal momentum and elastic wave travel determine contact time and modulus. This is axial compression, not unsupplied flexural beam dynamics.'),
(12,'REJECT',[],'theory','Relativistically transformed elliptic planetary trajectory','The boost speed is a significant fraction of c. Lorentz coordinate/time transformations are not supplied and are central to the requested new orbit and time parameterization.'),
(13,'KEEP',[I,II],'theory','Classical oscillator coupled to a fully specified continuum bath','The intact quadratic kinetic, spring and bilinear coupling expression was inspected. It operationally defines masses/frequencies/couplings; Newtonian coupled-oscillator equations and elimination yield a memory kernel. Continuum integration and energy accounting are mathematics and classical mechanics.'),
(14,'KEEP',[II],'numerical','Membrane wave superposition and possible nodal/amplitude images','The source expressly substitutes an ideal membrane with fixed/free boundaries for an elastic plate. Ordinary wave eigenmodes and superposition constrain images; simulation and optional apparatus remain one task.'),
(15,'KEEP',[I],'theory','Low-viscosity capillary-rise dynamics and overshoot','Wetting, tube geometry and negligible-viscosity regime are specified. Surface-tension pressure, gravity and incoming-fluid momentum balance give one-dimensional motion. Variable liquid mass requires care but no unsupplied specialized flow instability.'),
(16,'KEEP',[I,II,VI],'theory','Nonlinear oscillations near a tetrahedral electrostatic equilibrium','Charge symmetry and Coulomb potential expansion determine the constrained restoring force and amplitude-period dependence. The motion line and finite-amplitude approximation require interpretation, not a new physical theory.'),
(17,'KEEP',[VI],'experimental','Four-contact resistance across a two-conductivity sheet interface','The A/B current and C/D voltage diagram was inspected. Local Ohm law, current continuity and interface matching determine potential/resistance using standard electrostatics mathematics.'),
(18,'KEEP',[I,II],'theory','Pulsatile hydraulic flow through a compliant chamber and resistance','The source supplies the chamber/resistance model and sinusoidal-squared input. Linear compliance plus volume balance and the defined hydraulic resistance give a driven first-order equation; biological context adds no necessary physiology.'),
(19,'KEEP',[IV],'numerical','Changing cylinder shape under conductive heating and melting','The microgravity, still-air, no-radiation setup is explicit. Fourier heat flow, sensible heat and latent-heat balance define the moving melting surface. Numerical boundary tracking is mathematics, without an unsupplied crystal or fracture model.'),
(20,'KEEP',[X,XI],'numerical','Temperature dependence of visible incandescent-light efficacy','Planck spectral radiation, photon/energy flux and visible sensitivity weighting estimate the change in apparent illumination and efficacy. Eye spectral response and tungsten emissivity are calibration data, not a new specialized law.'),
(21,'KEEP',[X],'theory','Imaging through a supplied negative-index slab and chromatic error','Negative refractive index is a stated optical model. Snell rays, wavelength-dependent index and image geometry determine focusing and aberration reduction. A microscopic metamaterial realization is not required by the task.'),
(22,'KEEP',[X,XI],'numerical','Lunar corner-cube laser return, diffraction and photon arrival times','Array/element sizes, telescope, energy and pulse duration are explicit and the array photo was checked. Gaussian/aperture diffraction, reflection, path delays and photon energy determine return scale and count. No new laser generation model is needed.'),
(23,'KEEP',[I,VI,VII],'experimental','Electron charge-to-mass measurement by magnetic beam focusing','The complete instrument dimensions and intact acceleration voltage were read from the render. Electrostatic energy, Lorentz helical motion and solenoid current-field relation give speed and first refocus; measurement design is eligible.'),
(24,'KEEP',[XII],'data_analysis','Statistics of a completely supplied correlated decay-time density','The positive-time joint density is explicitly given. Normalization, cumulative probability, moments and numerical integration are ordinary mathematics; independent exponential decay is not assumed.'),
(25,'REJECT',[],'theory','Relativistic tensor coupling and field-action reconstruction','Only one tensor kinetic term is given. Covariant coupling/action, proper-time dynamics and specialized field variation are unsupplied and central to all new particle/Maxwell equations and conservation laws.'),
(26,'REJECT',[],'theory','Lorentz-invariant homogeneous expansion velocity fields','The Galilean example is supplied, but the target Lorentz transformations, velocity addition and simultaneous-time comparison rules are not. They are the sole central physical prerequisites.'),
(27,'REJECT',[],'theory','Satellite clock equality including special and general relativity','Time-dilation and gravitational-redshift laws are named but not supplied. These control the synchronous altitude and rotation correction; ordinary orbital mechanics alone cannot give them.'),
(28,'BORDERLINE',[VI,VII],'theory','Differential momentum representation and gauge/topological unitary equivalence','Position/momentum operators and the target unitary equation are explicit, supporting substantial differential-operator mathematics. Canonical commutation requirements and physical representation/domain conventions are not defined. Intended self-contained mathematics versus an unsupplied quantum prerequisite remains ambiguous.'),
(29,'REJECT',[],'numerical','Quantum spin rotation, adiabatic limits and measurement probability','The time-dependent spin Hamiltonian is supplied but Schrodinger time evolution and Born measurement rules are not. These determine every probability/polarization trajectory; the task is not merely diagonalizing a finite matrix.'),
(30,'REJECT',[],'theory','Sudden two-spin coupling and failure of perturbative transition probability','Spin-coupling operator and one basis relation are given, but spin operator matrix rules, time-dependent perturbation and quantum transition probabilities are not. They centrally control the exact and approximate comparisons.'),
(31,'REJECT',[],'theory','Spin-two rotation symmetry, Berry phases and state-space topology','One state and coherent-state condition are given. Spin rotations, time-reversal action and Berry geometric phase rules are unsupplied and dominate all symmetry/phase/homotopy tasks.'),
(32,'REJECT',[],'theory','Effect of an unread intervening quantum measurement','Energies and basis vectors alone do not supply unitary time evolution, Born probabilities or unread-measurement state update. Those specialized rules are central to both compared scenarios.'),
(33,'REJECT',[],'numerical','Quantum coherent-state basis and oscillator number-state expansion','Coherent states, their completeness/normalization and number-state construction are not defined. These unsupplied quantum-oscillator rules are the sole physical model requested.'),
(34,'REJECT',[],'theory','Heisenberg motion under a momentum-dependent matrix quantum Hamiltonian','The dyadic Hamiltonian is supplied, but Heisenberg evolution, canonical commutators and wavepacket expectation rules are not. They control position evolution and its physical interpretation.'),
(35,'REJECT',[],'theory','Hydrogen Stark multipole splittings from polygonal external charges','Ordinary Coulomb geometry is only an opening. The central p,d,f shifts require unsupplied hydrogen wavefunctions, degenerate perturbation and Stark selection rules; hyperfine/Lamb comparisons further depend on specialized data.'),
(36,'KEEP',[IX,XI],'theory','Analytical approximation to a quantum model explicitly supplied by a linked paper','The source explicitly links arXiv:1605.01087. Its Sections II-III and Appendix supply a closed scalar expectation-value ODE system, definitions and permitted factorizations. Weak-coupling expansion and integration of those supplied equations answer the requested approximation with ordinary mathematics, without deriving missing quantum rules.'),
(37,'BORDERLINE',[I],'theory','Newtonian hierarchical binary stability with abrupt mass loss and wave disruption','Newtonian point-mass estimates and the mass-loss fraction are expressly allowed, covering substantial tidal stability/orbit work. The final direct gravitational-wave disruption may require a wave-to-tidal-acceleration model not supplied. Whether the intended estimate means only mass-loss effects is unclear.'),
(38,'KEEP',[I,II],'theory','Decreasing-frequency gravitational sources under supplied radiation rates','Strain, frequency relation and orbital radiation-evolution equations are explicitly provided. Combining them with Newtonian energy exchange among point masses permits leading-order configurations and orbital-element evolution. No additional unsupplied GR emission law is necessary.'),
(39,'REJECT',[IV,VII],'numerical','Ising critical behaviour on an Escher hyperbolic tiling','The source names Ising and a linked tiling but does not define its spin energy, probability ensemble or square-grid comparison rules. Those specialized statistical spin-model prerequisites centrally determine transition temperature and finite-size effects.'),
(40,'KEEP',[I,X],'theory','Inferring density-dependent refractive index from a delayed self-image orbit','The complete story spans pp11-12 and supplies radial density, transparency and ordinary gravity conditions. Circular speed from enclosed mass and curved-ray travel determine the half-orbit self-image delay and n(rho). Fictional propulsion is explicitly irrelevant to the gas model.')]
pages=[1,1,2,2,2,2,3,3,3,3,3,4,4,4,4,5,5,5,5,5,5,6,6,6,7,7,7,7,8,8,8,9,9,9,10,10,10,11,11,11]
units={int(r['problem_number']):r for r in c.execute('select * from units where source_file_id=3123')};assert len(units)==40
ref=w.ROOT/'references/ortvay_2017_q36_arxiv_1605.01087v3.pdf';sha=hashlib.sha256(ref.read_bytes()).hexdigest()
c.execute('insert or ignore into screening_references(reference_id,screening_unit_id,url,local_path,sha256,byte_size,page_count,purpose,acquired_at) values (?,?,?,?,?,?,?,?,?)',('ortvay_2017_q36_arxiv_1605.01087v3',units[36]['screening_unit_id'],'https://arxiv.org/pdf/1605.01087v3',str(ref.relative_to(w.ROOT)).replace('\\','/'),sha,ref.stat().st_size,9,'Explicit source-linked model supplied by Q36 p10. Sections II-III and Appendix equations24-33 read; renders checked. Essential to future use.',w.now()));c.commit()
out=[]
for n,d,dom,fmt,physics,reason in rows:
 u=units[n];assert u['decision'] is None
 out.append(dict(screening_unit_id=u['screening_unit_id'],decision=d,confidence='medium' if d=='BORDERLINE' else 'high',primary_spho_domains=';'.join(dom),required_physics=physics,decision_reason=reason,external_physics_if_any=physics if d in ('BORDERLINE','REJECT') else '',format=fmt,page_start=pages[n-1],page_end=12 if n==40 else pages[n-1],visual_inspection_used=1,solution_used=0,boundary_status='content_boundary_verified',needs_second_review=n in (11,13,15,18,21,36,38),evidence=f'Full actual Ortvay 2017 Q{n}, physical p{pages[n-1]}'+('-12' if n==40 else '')+' read from SHA cache and full-page render. All twelve physical pages rendered and inspected because extraction damages symbols/spacing and omits diagrams. Q36 explicitly supplied reference preserved and read separately. Organizer archive provides no 2017 worked solutions. All internal parts kept with their printed number.'))
p=w.ROOT/'reviews/shutdown_ortvay_2017_40.json';w.writejson(p,out);w.decisions(p)
c.execute("update paper_boundary_audit set status='full_paper_boundaries_verified',observed_units=40,evidence=?,checked_at=? where file_id=3123",('All twelve physical pages read and visually inspected: exactly Q1-Q40. Q40 continues on p12; hyperlinks/figures/preface add no independent task. No omitted experimental/short-answer/MCQ task found.',w.now()))
notes={1:'Final sentence repeats qualitatively rather than specifying a numerical perception model.',4:'Numerical heads-probability bound depends on launch-parameter distribution, not specified.',10:'No body size/shape normalization given, so universal frequency bounds may be trivial or scale dependent.',16:'Motion line orientation and small-amplitude approximation are unspecified; symmetry cancellation and stability depend on direction.',18:'Flexible aorta does not state numerical pressure-volume compliance; linear small-strain compliance must remain an explicit approximation/input.',19:'Thermal conductivities, latent heat and interface/contact transfer data require ordinary material inputs; source asks a numerical model rather than supplying a fixed data set.',20:'Tungsten emissivity and eye spectral-response weighting are not supplied numerically.',21:'Negative-index dispersion curve is unspecified; realistic chromatic estimates require stated material/index inputs, not assumed zero dispersion.',24:'Printed c is any real number; normalization requires c > -2*sqrt(a*b). The mathematical task must address nonnormalizable parameter choices.',36:'Essential original problem-linked arXiv reference is preserved with hash and provenance outside raw acquisition. Closed scalar model, not Hamiltonian alone, supports KEEP.',37:'Final wave-disruption wording can mean direct wave tidal forcing or only sudden central mass loss; no direct wave force/strain model is given.',38:'Rendered da/dt and de/dt prefactors use G^2, whereas conventional orbital-radiation rates need G^3 for dimensions. Supplied qualitative evolution model retained, typo flagged rather than silently rewriting source.',39:'Original Escher gallery URL inaccessible via both HTTP and HTTPS on recovery date. No replacement physics source inserted; graph reference remains explicitly unresolved.',40:'Q40 spans pp11-12. Index-density inference assumes circular refracted self-ray and the narrative half-orbit travel delay; inversion is model inference, not a supplied microscopic material theory.'}
for n,note in notes.items():c.execute('update units set source_quality_notes=? where screening_unit_id=?',(note,units[n]['screening_unit_id']))
c.commit();print('Saved 40 explicit decisions, linked model reference and twelve-page boundary audit.')
