import workflow as w
c=w.connect();u={int(r['problem_number']):r for r in c.execute('select * from units where source_file_id=3142')}
details={
1:'Focused whole thermal-versus-biochemical requirement: all Q1 a-c reread. Treat fermentation heat source/rate and lethal temperature as empirical parameters; thermal diffusion/loss balances and size scaling then answer temperature/viability. No microscopic metabolic derivation is explicitly required. KEEP confirmed, no wine-specific numeric data or experiment fabricated.',
3:'Focused freezing-premise review: complete Q3 reread. Source supplies no weather, orientation/exposure history or initial thermal state, so east-only is not universal. Ordinary radiation/convection/latent-heat model can establish conditional freezing/thawing and identify missing parameters. KEEP confirmed without asserting a fabricated universal quantitative explanation.',
5:'Seeded QC (Random 2026100425 first selection) and focused elastic-depth review: actual Q5 reread. Lame constants and brick size alone do not give tensor constitutive response, contact/column stability or buckling law. Predicting maximal stable height needs that central specialized elastic model; mere weight balance is insufficient. REJECT confirmed.',
6:'Focused supplied strain model: actual Q6 tensor definition and compatibility reread. Differentiating epsilon gives u_i,jk=epsilon_ij,k+epsilon_ik,j-epsilon_jk,i. Integrating the resulting gradient/Hessian recovers u modulo rigid modes on a suitable domain. All needed kinematic relations provided; no missing elastic force law. KEEP confirmed with topology/global boundary qualifications.',
7:'Focused wave-model and premise review: full Q7 reread. Mode spacing/coupling, tension/damping and finite observation time govern discrimination; shape alone cannot guarantee every regular membrane is superior. An ordinary scalar-wave/resonance analysis can test that claim. KEEP confirmed, no specialized biological transduction calculation demanded.',
8:'Focused actual red-cell work dependencies: full Q8 and all three suggested effects reread. Narrow-capillary deformation and relative cell/plasma motion require unprovided membrane rheology and local hydrodynamic laws/geometry; they dominate meaningful daily-energy calculation. Closed-loop gravity alone gives no net energy cost from density. REJECT confirmed based on actual prerequisites, not biological context.',
9:'Focused full drop/film dynamics: complete Q9 reread. Capillary instability intuition is permitted but x(t), detachment and catch-up depend on unprovided wetting/contact-line and viscous mobility. No complete dynamical model supplied. Whole REJECT confirmed, not rejecting static surface tension.',
10:'Focused static versus whole evolving-drop work: complete Q10 reread. Gravity/surface-tension balance can estimate detachment, but requested evolving shape and drop/jet regime centrally require unprovided free-boundary fluid/breakup closure and material boundary data. Whole REJECT confirmed, not rescuing only a static subpart.',
11:'Focused whole granular experiment depth: actual Q11 reread. Conservation with empirical flux q(rho) gives wave speed q-prime and upstream jams, an ordinary explanation. Predicting that flux and instability for dry grains/tube air can need unsupplied rheology. Intended quantitative closure remains unclear. BORDERLINE retained; no experiment or measurements claimed.',
12:'Focused point-mass chain versus elastic-shell model: full Q12 reread. Newton star gravity and individual link tension/inextensibility close discrete perturbation dynamics. Longitudinal motion may be constrained away or coupled to radial displacements; report that rather than add a fictitious stretch modulus. KEEP confirmed; exotic satellite ring context changes no required force law.',
14:'Focused finite-wire optimization: complete Q14 dimensions and warm-up reread. Magnetic energy and self/mutual inductance permit coil-packing/loop comparison with supplied nonoverlap radius. Mathematical global search and return/termination assumptions matter but no unprovided ferromagnetic response exists. KEEP confirmed.',
17:'Focused actual claimed measured telegraph model: complete Q17 reread. No coefficients/equation are actually printed; more centrally no SR simultaneity/frame/length boundary laws are supplied for the two rockets. Ordinary axial-wave intuition cannot resolve final relativistic length. REJECT confirmed.',
21:'Focused exactly supplied averages: all Q21 formulas and a-b reread. Inner-product and time averages are given, but hydrogen orbital wavefunctions and momentum representation are only called well-known. They are central to quantitative quantum uncertainty comparison. REJECT confirmed, not denying ordinary classical orbital averages.',
22:'Focused fully supplied quantum representation and rendered conjugation: complete Q22 p5 reread. Momentum=-i*hbar*partial_q and coordinate multiplication are explicitly printed, as is conjugated inner product. Adjointness follows integration by parts; measure preservation gives half-density Jacobian transform, with residual scalar-ordering freedom to disclose. Cartesian/polar example is differential mathematics of this complete supplied rule. KEEP confirmed; no missing Born/time-evolution law needed by actual requests.',
26:'Focused full condensate operator: actual Q26 p6 G, harmonic U, domain/norm and energy relation reread. Commutator expansion for coordinate/derivative operators is closed mathematics; boundary/domain preservation must be checked. No condensate derivation or many-body state rule is required. KEEP confirmed. Compared complete 2008 Q31: same physical PDE but axial ansatz/spectrum task differs from this anisotropic commuting-operator task, so no exact logical equivalence recorded.',
27:'Focused ordinary collisionless Maxwell gas: full Q27 reread. Free Newton transport is f(t,x,p)=f0(x-p*t/m,p). Gaussian joint initial distributions stay Gaussian under that linear map, with conditional momentum mean/covariance giving local u/T and marginal n. Only special families preserve isotropic local temperature; generic profiles do not. KEEP confirmed without importing an unsupplied interaction/kinetic closure.',
28:'Focused supplied thermion toy laws: all Q28 reread. m proportional T and gradient/cross-product force directions are expressly stipulated, not theories to derive. In a declared ordinary ideal-gas variable-mass/thermalization convention, momentum flux, energy/entropy and piston/mixing balances analyze species with coefficients left parameters. No Lorentz law needed. KEEP confirmed; distinguish assigned mass energy from kinetic contribution and report ambiguity rather than claim unique real particle thermodynamics.',
29:'Seeded QC (Random 2026100425 second selection) and classical-spin model review: full actual Ising energy/Si=+/-1 and both averaging procedures reread. Single-spin Boltzmann sum and selected-chain transfer sum are finite-state classical statistical mathematics. Mean-field linear self-consistency supplies transition estimates, not microscopic exchange derivation. KEEP confirmed; no quantum spin representation assumed.',
30:'Focused static supplied-energy spiral: full Q30 p7 reread. The task only asks impurity distortion at T=0; Si*Sj*cos(phi_i-phi_j) energy is explicitly defined by the fixed-spin model. Angular minimization/linearization with arbitrary Jij is ordinary mathematical variation, not quantum spin dynamics. KEEP confirmed; microscopic source story is unnecessary.',
33:'Focused experimental superfluid prerequisite: full Q33 a-b reread. Converting temperature into displacement requires the actual superfluid thermomechanical/fountain constitutive relation and realistic material response, neither supplied. Those laws select the apparatus and sensitivity before laser precision enters. REJECT confirmed, experimental format fully considered.',
34:'Focused fully supplied thermal angular inference: all Q34 energy, antiparallel premise and moment measurement reread. Boltzmann angle weights and moment-tensor principal axes/eigenvalue ratio infer coupling, subject to isotropic/head-tail/sign degeneracies. This is classical thermal statistics of supplied energy. KEEP confirmed; no sample photographs or measured tensor fabricated.',
35:'Focused whole original-image estimate: Q35 and full original 1124x1705 JPEG visually reread. Two foreground hikers and notch are visible but depth/perspective preclude exact scale without assumptions. Mass/displacement work, momentum and a declared empirical fracture-energy scale provide a general-physics estimate of mythical consequences. KEEP confirmed; no precise crack mechanics or actual strike/weapon procedure required. Original source/hash/reference preserved.'}
required={int(r['problem_number']) for r in c.execute("select problem_number from units where source_file_id=3142 and review_status='pass_1_complete'")};assert required<=set(details),(required-set(details))
p=w.ROOT/'reviews/shutdown_ortvay_1998_focused_seeded_formats_22.json';w.writejson(p,[dict(screening_unit_id=u[n]['screening_unit_id'],detail=d) for n,d in details.items()]);w.review(p)
w.writejson(w.ROOT/'reviews/shutdown_ortvay_1998_2008_non_equivalence.json',{'checked_at':w.now(),'comparison':'Complete 1998 Q26 p6 versus complete 2008 Q31 supplied condensate PDE','result':'Shared physical model, different whole task: anisotropic commuting differential operators versus axially symmetric polynomial-factor ansatz/frequencies. Preserve separate logical problems; no equivalence inserted.'})
assert not c.execute("select 1 from units where source_file_id=3142 and review_status='pass_1_complete'").fetchone();print('Saved twenty-two focused/seeded/format reviews and explicit non-equivalence evidence.')
