import workflow as w
c=w.connect();u={int(r['problem_number']):r for r in c.execute('select * from units where source_file_id=3129')}
# Focused inspection corrects one new provisional decision; historical pass-one event remains.
change={'screening_unit_id':u[34]['screening_unit_id'],'old_decision':'REJECT','new_decision':'BORDERLINE','source_evidence':'Q34 p6 does not specify a high-speed atom regime or any atom-speed ensemble. Ordinary slow-atom photon Doppler broadening and nuclear energy accounting may suffice; an exact relativistic distribution is a different unprovided model. The pass-one reason had assumed that latter model was necessarily dominant. No rubric change or earlier batch alteration.'}
assert u[34]['decision']=='REJECT'
c.execute("update units set decision='BORDERLINE',confidence='medium',primary_spho_domains=?,required_physics=?,decision_reason=?,external_physics_if_any=?,review_status='pass_1_complete' where screening_unit_id=?",('XI_quantum_light;XII_atomic_nuclear','Annihilation photon Doppler broadening with an unspecified atom velocity ensemble','The COM photon pair is supplied. Slow-atom photon Doppler broadening and nuclear energy/momentum accounting can be foundational, while an exact fast-atom distribution requires unsupplied relativistic transformations. Neither the speed regime nor the atom velocity ensemble is given, so the intended required method is unresolved.','Exact relativistic photon transformation if fast atoms are intended; no fast regime is actually stated.',u[34]['screening_unit_id']))
c.commit();w.writejson(w.ROOT/'reviews/shutdown_ortvay_2011_q34_focused_change.json',change)
details={
14:'Focused context/model review: complete Q14 p3 reread. Cherenkov cone is described, and the task only requests planar wavefront shape for a circular path. Envelopes of ordinary fronts with material speed c give the curves. No microscopic emission coefficient or relativistic velocity transformation is needed. KEEP confirmed.',
17:'Focused elasticity scope review: full Q17 p4 reopened. Scalar Hooke law names linear response but does not operationally supply the isotropic tensor strain/stress law and Poisson coefficient or elastic equilibrium PDE needed for a solid-sphere displacement field. This is a distributed continuum deformation, unlike ordinary axial rod/spring compression. REJECT confirmed under established elasticity boundary, not because of rotational speed or difficult mathematics.',
20:'Focused emitter versus material prerequisite review: all Q20 p4 reread. Resonant disk supplies the oscillating aperture; requested axial zeros/intensity and diameter follow coherent wave superposition and path difference. Piezoelectric electromechanical constitutive derivation is not requested. KEEP confirmed with piston-source idealization noted.',
27:'Focused whole-problem review: all Q27 p5 reread. Newtonian ring force and finite-amplitude period are meaningful conventional work. The final general-parameter energy spectrum expressly invokes unprovided Bohr-Sommerfeld rules, beyond simply using atomic circular-orbit Bohr quantization. Mixed work remains near boundary. BORDERLINE confirmed without splitting.',
28:'Focused foundational atomic-model review: entire Q28 p5 reread. It asks only positronium size relative to hydrogen. Coulomb two-body reduced mass and conventional Bohr angular-momentum quantization determine radius; annihilation lifetime is context. KEEP confirmed; it is distinct from Q34 spectroscopy.',
29:'Focused supplied-spectrum versus state-count review: full Q29 p5 reread. E= hbar*omega*(2n+l+3/2) is actually given, so no quantum eigenproblem is required. But n/l/m domains, spin occupancy and magic-number definition are not explicitly given; different degeneracy conventions change counts. Substantial combinatorics remains ordinary mathematics after those conventions. BORDERLINE confirmed, not blanket quantum-spectrum rejection.',
34:'Focused review changed this newly saved REJECT to BORDERLINE. Complete Q34 p6 reopened: no relativistic/high-speed atom regime is specified. A slow-atom Doppler-broadened annihilation line can use foundational wave/nuclear physics, while exact fast-atom transformation uses outside SR. Speed distribution/ensemble is also absent. The first reason assumed the fast exact model was necessarily required; that assumption was not source-grounded. BORDERLINE records the actual ambiguity. Change documented separately; original pass-one event preserved and no earlier decisions/rubric changed.',
38:'Focused supplied-dispersion review: full Q38 p7 and both processes reread. Complete species E(p) relations and speed inequalities are written. Thresholds follow minimizing final energy under vector momentum conservation, using triangle/collinearity conditions and small-delta expansion. No boost, proper time, weak-decay amplitude or QFT loop law is needed. KEEP confirmed for both numbered clauses together.',
40:'Focused supplied toy/data review: full Q40 p8 equation/three clauses reopened. Expected log utility with wealth recursion and stated zero-profit-plus-margin annuity defines mathematical optimization. Real mortality weights are available in the original CDC-linked portal; preserved US 2007 report existed before the contest and total-population ages including 100+ were actually inspected. No real financial advice/model is assumed. KEEP confirmed with table choice/payment timing/margin documented.',
42:'Focused supplied climate-model review: all Q42 p9 and figure reread. Blackbody Earth, explicit transparent-shortwave/absorbing-longwave reradiating layer, solar constant and contestant-selected albedo define the complete toy physics. Radiation balance and derivative stability suffice; no cloud microphysics or actual climate prediction law is imported. KEEP confirmed.',
35:'Experimental format QC: whole Q35 p7 reread. Material and carving method are free choices, with measurable controllability and atom count as criteria. Repeated mechanical subdivision and ordinary mass/density/Avogadro calibration are legitimate solutions; advanced atomic manipulation is not required by the text. KEEP confirmed.',
36:'Seeded QC (Random 2026100412, first selection): complete gas-escape task p7 reread. General velocity flux through a small aperture and declared well-mixed isotropic effusion produce a hazard conditional on speed; fixed speed permits exponential survival in that model. Collisionless billiard-memory alternatives are not uniquely excluded and are recorded as source-model limits, not a specialized prerequisite. KEEP confirmed.',
15:'Seeded QC (Random 2026100412, second selection): entire chain/delayed-boundary task p3 reread. Newtonian spring equations with the explicitly supplied time-shift constraint give a frequency-dependent phase/eigencondition. Complex/unstable modes and nonstandard orthogonality are mathematical consequences of that stipulated boundary. KEEP confirmed.'}
p=w.ROOT/'reviews/shutdown_ortvay_2011_focused_seeded_qc_13.json';w.writejson(p,[dict(screening_unit_id=u[n]['screening_unit_id'],detail=d) for n,d in details.items()]);w.review(p)
print('Saved thirteen focused/seeded/format reviews, including documented Q34 REJECT-to-BORDERLINE correction.')
