import workflow as w
c=w.connect();u={int(r['problem_number']):r for r in c.execute('select * from units where source_file_id=3137')}
details={
2:'Focused actual folded-rope review: complete Q2 p2 and U-shaped drawing reread. The first two central parts admit a flexible-line Newton tension/momentum-flux and energy-transfer model, with conservation versus inelastic pickup distinguished. Radius is only requested in a first approximation under the supplied semicircle shape; negligible bending stiffness and circle-model limits can be declared. No unsupplied beam bending law is centrally needed. Whole KEEP confirmed.',
7:'Focused rope-contact model review: full Q7 p3 reread. Fixed finite rope radii, lengths, twists and no stored torsion energy define geometrical lift and gravity drive. Ordinary contact normal force and the stated Coulomb coefficient model resistance, with no material torsional elasticity to import. Whole KEEP confirmed with contact approximation explicit.',
11:'Focused membrane versus beam review: entire Q11 p3 reread. Drum is explicitly a membrane, so transverse inertia and scalar pretension produce the ordinary wave equation, with patch areal density/pretension treated as parameters and force/displacement matched at its circle. Bending plate stiffness and tensor-elastic constitutive theory are not demanded by this idealization. KEEP confirmed.',
12:'Focused experimental estimation review: full Q12 p3 reread. It asks some methods to estimate lifetime, not an unprovided microscopic wear-law derivation. Measured play/vibration/current histories, endurance statistics or a calibrated accelerated-test model can supply a defensible estimate/uncertainty. No actual fan test or numerical lifetime is claimed. KEEP confirmed; experiments are eligible.',
13:'Seeded QC (Random 2026100420 second selection): complete homogeneous-potential theorem Q13 p3 reread. At static unconstrained equilibrium, Euler homogeneity gives sum r dot grad U=nU=0; K=0 then U=0 for n nonzero. Constants, degree zero and external constraints give requested counterexamples. The claim needs these ordinary mathematical caveats, not additional specialized physics. KEEP confirmed.',
14:'Focused capillary experimental review: full Q14 p3 reread. Sharp immiscible interface and differing tensions admit surface-energy/curvature-pressure/buoyancy reasoning for deforming/trapped/transmitted bubbles. Measured wetting/tensions and qualitative film stability are allowed apparatus parameters; no full viscous trajectory is explicitly asked. KEEP confirmed with no fabricated bubble observations.',
15:'Focused whole tidal-estimate review: entire Q15 p4 reread. Quantitative equilibrium tide follows differential Newton gravity and hydrostatic balance. Closing try-to-explain extreme bay/estuary values can use rough forced-wave resonance and geometric amplification, without a mandated exact coastal mode/hydrodynamic computation. Unlike a task whose main result is a full stratified-fluid eigenproblem, that open explanatory extension does not dominate. Whole KEEP confirmed; no precise measured heights are claimed as reproduced.',
16:'Focused stratified-wave prerequisite/calibration review: complete Q16 p4 and actual 2023 Q19 raw::5473 reread. Gamma=1 and equilibrium exp(-h/h0) are acknowledged and simplify some restoring terms, but the task centrally asks complete coupled gravity/radial modes, vertical dispersion and outer energy/reflection/dissipation. No perturbation velocity/pressure dynamics or boundary prescription is supplied. This matches the existing full stratified-fluid mode boundary, unlike a given acoustic wave driving a rigid box or mere ray refraction. REJECT confirmed; prior record untouched, no rubric shift.',
17:'Focused rigid-dipole model review: full Q17 p4 reread. A pair of small opposite rigidly attached charges realizes the specified electric dipole and inertia. Applying ordinary Lorentz forces to centre plus rotational velocities gives net force/torque and conservations, with stated initial orientation. No quantum spin or relativistic dipole field transform is necessary in this ordinary mechanical limit. KEEP confirmed.',
18:'Focused spatial-geometry/PDE review: complete Q18 p4 reread. Spherical Poisson is explicitly the defining field law; integrating over the compact sphere requires net neutrality and a zero-mode-removed Green function. Multipoles and Fourier circle-boundary matching are geometry/calculus applied to that supplied equation. No GR is necessary. Whole KEEP confirmed.',
19:'Focused free-carrier and suspicious-overlap review: Q19 p4 compared directly to actual 2006 Q19 raw::6023. Free electrons are explicitly supplied in 2003; Newton centrifugal/electric balance and rotating-charge current yield its dipole moment. 2006 additionally asks full internal/surface charge and external field; these are different printed task sets, not exact reprints. KEEP confirmed with both separate provenance records and no alias invented.',
21:'Focused supplied circuit/reference review: full Q21 p4 reread. Diagonal cuts, periodic seam, edge R/L, cylinder width and queried nodes define a Kirchhoff Laplacian problem. Finite circumference permits Fourier blocks even along the infinite axis; numerical N=2,3 cases follow the graph. Suggested article is not necessary for missing physics and need not be substituted for the actual circuit. KEEP confirmed.',
22:'Focused full-space radiation review: all Q22 p5 reread. Standard retarded Maxwell dipole potentials support field derivation and distributional source terms at the origin. Checking only r>0 would miss the whole-space requirement, but completing the source distribution is mathematical general EM, not QED. KEEP confirmed; citation is a standard EM reference, not an advanced supplied model requirement.',
26:'Focused experimental-optics review: full Q26 p5 reread. Bright spots can arise from geometrical reflection/refraction/focusing in a curved thin film, with interference affecting colours/brightness. Capillary shape and optical geometry remain ordinary physics. No observation/experiment was performed or claimed. Whole KEEP confirmed.',
27:'Focused explicit idealization review: entire Q27 p5 reread. The problem specifically sets aside creating a star and fixes minimum luminosity by Europa melting/temperature. Flux dilution, radiative equilibrium and viewing/illumination estimates solve the actual tasks; detailed stellar structure or climate dynamics are not requested. Whole KEEP confirmed.',
28:'Focused partially supplied relativistic-law review: full Q28 pp5-6 reread, including reciprocal-mass variant. Four-force equations are provided, but turning them into three-acceleration requires proper time, four-momentum/rest-mass evolution and time-component consistency not given. Those missing relativistic rules centrally precede every trajectory and asymptotic result. Whole REJECT confirmed without falsely saying the force is absent.',
29:'Focused supplied frequency and rate review: complete Q29 p6 reread. f=v/b is explicit, so frequency-window encounters can be counted with number density, cross section and chosen/virial Newton speed. Hyperbolic Newton focusing maps asymptotic impact parameter to closest separation. No gravitational-wave luminosity or detector amplitude/SNR calculation is asked. KEEP confirmed; masses, velocity distribution and small-distance cutoff remain stated estimate assumptions.',
31:'Focused spatial-manifold modelling review: full Q31 p6 reread. The explicit classical/strong-spring framing allows an embedded-surface spring-energy construction; exotic manifold language alone is insufficient for rejection. But a universal intrinsic curvature force/minimum arrangement depends on unspecified spring-distance/constraint/coupling choices and dimension/metric. No official worked model resolves that ambiguity. Whole BORDERLINE retained, consistent with allowing fully defined fixed spatial geometry elsewhere.',
32:'Focused diffusion/decay and overlap review: full Q32 p6 compared directly with actual 2008 Q32 raw::5968. This task computes activity versus radius from known D/source density; the other infers D from measured ratios. They are different direct/inverse printed tasks, not exact aliases. Both use ordinary nuclear decay and diffusion conservation with declared free escape boundary. KEEP confirmed; prior decision unchanged.',
33:'Focused whole nuclear trajectory review: Q33 p7 reread including the explicit negligible transferred momentum condition. 2333/2033/300 keV energy accounting and Coulomb force on the charged daughter give a Newtonian fragment model; neutron is force-free. Centre trajectory depends on breakup position/relative direction, which the source does not fix, so retain a family/insufficiency rather than fabricate uniqueness. No advanced nuclear-transition or Lorentz boost law is required by the stated toy approximation. KEEP confirmed.',
34:'Focused supplied-potential/reference review: all Q34 p7 classical and quantum parts reread. Coupled quadratic potential helps the classical calculation but does not provide phonon kinetic/restoring Hamiltonian, electron oscillator basis or first-order and restricted-Hilbert-space quantum rules. Two quantum parts carry the central Jahn-Teller insight. Original cited APS article abstract inspected; full PDF explicitly returns 401 authorization required, so no complete supplied paper is claimed. REJECT confirmed without substituting unrelated missing theory.',
35:'Focused partial Hamiltonian and seeded QC (Random 2026100420 first selection): full Q35 p7 reread. Minimal-coupling kinetic term and Zeeman labels are acknowledged, but momentum representation/periodic state spectrum and Pauli spin eigenproblem are only named. These outside quantum prerequisites are central to the entire energy-level request. REJECT confirmed.',
36:'Focused supplied evolution versus remaining prerequisites review: full metric and conditional phase Q36 p7 reopened. Evolution exp(i*omega*tau_a) genuinely is provided, as is Gaussian f(a). But mapping a metric to proper time and tracing the joint state to a reduced quantum density matrix are not operationally defined. They centrally determine the off-diagonal factor before the Gaussian mathematics. REJECT confirmed on those specific missing relativistic/quantum rules, not a false absence-of-evolution claim.',
37:'Focused gate versus measurement review: whole Q37 p8 reread. Explicit singlet and I/X/Z/Y/conditional spin operations permit algebraic gate propagation. Certain decoding and Eve ignorance still require quantum observable/measurement probabilities and reduced-state interpretation, which are not provided. Those are the key physical outputs. Whole REJECT confirmed; supplied gates alone are not a supplied measurement model.',
38:'Focused fictional-beam prerequisite review: entire Q38 p8 reread. An ordinary Maxwell beam does not self-terminate into the requested finite rigid rod; intensity alone is not an operational confinement law. No nonlinear photon/self-gravity/termination mechanism is supplied. The requested threshold and usable mechanical arm depend on that missing specialized physical model. REJECT confirmed without rejecting fiction by itself.',
39:'Focused complete stochastic-rule review: all Q39 p8 reread. State lattice, initialization, two-neighbour eligibility and duration probabilities are completely defined. Renewal/Markov mathematics supplies performance with a declared simultaneous-update convention, and analytical approximation is allowed while simulation alone is not accepted as an answer. KEEP confirmed; no hardware/quantum model needed.',
40:'Focused mixed-model estimation review: all Q40 p8 reread through lecture-hall extension. Measured lumped heat/pollutant balance and exchange/mixing coefficients can implement the requested compromise model for each occupancy schedule. Diffusion and stirred-mixing description supports that ordinary approximation; no prescribed detailed flow field is required. KEEP confirmed, no actual room measurements/optimal schedule fabricated.',
41:'Focused inference-sufficiency review: complete Q41 p8 reread. Trajectory geometry and repeated purposeful-looking patterns can suggest organization, but without an operational intelligence definition or exclusive biological generating law they cannot uniquely certify intelligence. Constructing observationally equivalent nonintelligent processes is a mathematical/logical answer to the asked undisputed-evidence test, rather than importing cognitive theory. KEEP confirmed with this limitation explicit.'}
required={int(r['problem_number']) for r in c.execute("select problem_number from units where source_file_id=3137 and review_status='pass_1_complete'")};assert required<=set(details),(required-set(details))
p=w.ROOT/'reviews/shutdown_ortvay_2003_focused_seeded_formats_28.json';w.writejson(p,[dict(screening_unit_id=u[n]['screening_unit_id'],detail=d) for n,d in details.items()]);w.review(p)
assert not c.execute("select 1 from units where source_file_id=3137 and review_status='pass_1_complete'").fetchone()
print('Saved twenty-eight focused/seeded/format reviews, no calibration change.')
