import workflow as w
c=w.connect();u={int(r['problem_number']):r for r in c.execute('select * from units where source_file_id=3139')}
details={
1:'Focused whole dog/ball/hearing review: actual Q1 p2 reread. The dog reacts to SOUND, so loss of communication once outrunning a trailing sound wave is an ordinary acoustic mechanism, not evidence for a relativistic c bound. Doubling is discrete and timing matters. Air drag can also lift the ball before further bumps, but radius/drag/contact model are absent. BORDERLINE retained for the underdefined whole model, with the initial speculative relativity rationale explicitly corrected and preserved in history; no outside physics presumed from density alone.',
2:'Focused actual piston-wheel diagram and full Q2 reread. Heavy tangential piston displacements change both gas work and gravitational work; water pressure is depth-dependent and contributes work/torque. Counting only expanded-cylinder buoyancy omits those dependencies. Closed-cycle work/first law suffices. KEEP confirmed; no new perpetual-motion claim.',
4:'Focused full satellite estimate reread. Estimate is explicitly requested, so geometric collision rates and offspring/removal branching parameters are legitimate ordinary approximations. No microphysical fracture spectrum must be derived; yield and orbit population must be declared rather than invented. KEEP confirmed.',
8:'Focused rope continuum versus specialized elastic model: complete Q8 p3 reread. Rope is flexible, not a bending beam; differential tension balance follows directly from Newton and centrifugal/gravity force density. Inextensibility and zero free-end tension close ideal shape branches. KEEP confirmed, mathematical difficulty not a prerequisite veto.',
9:'Focused variable-mass pendulum review: complete hourglass statement reread. Specify a sand-transfer history and include falling-grain momentum/impact and changing moment of inertia. A parameterized Newton model is possible; absence of a numerical flow/geometry is not itself out-of-scope physics. KEEP confirmed; no unique measured trajectory claimed.',
10:'Focused small membrane distortion review: actual one-percent instruction reread. Scalar membrane wave eigenvalue/domain perturbation is ordinary waves; specify constant tension versus induced pretension/area changes. No demanded exact three-dimensional tensor response appears in the statement. KEEP confirmed within explicit small scalar-wave idealization.',
11:'Focused full supplied fluid closure: complete Q11 equations and polynomial hint reread on actual p3. Maxwell-Boltzmann Gaussian with local chemical potential gives equilibrium rho/P; all continuity, acceleration and pressure coefficients are supplied for modes. Polynomial substitution is closed mathematical work, unlike deriving an unprovided atmospheric/kinetic wave law. KEEP confirmed; no quantum gas invoked.',
12:'Focused complete towel folding review: theoretical/numerical criteria and differing methods all reread. An ideal flexible-chain kink is Newtonian, whereas a finite-stiffness sheet fold can need a material/contact law. No specified idealization resolves the intended depth and no experimental measurements were performed. Whole BORDERLINE confirmed rather than rejecting experiments or rescuing only observations.',
13:'Focused qualitative fluid experiment review: full sugar/cup contrast reread on actual p4. Rotating pressure gradient persists while bottom friction slows fluid; imbalance drives inward near-bottom motion. Co-rotating cup lacks that mismatch and excess grain density gives outward tendency. Those ordinary force arguments explain the asked qualitative contrast; exact boundary-layer eigenstructure is not requested. KEEP confirmed; no actual experiment claimed.',
14:'Focused complete three-part thermal effusion review: actual d much less than mean free path and maintained T givens reread. Flux n*sqrt(T) equality, molecular momentum and energy exchanges suffice. Net force/source reaction and external temperature maintenance must all be counted; Q alone cannot fix a unique unspecified cycle, but thermodynamic bounds are within scope. Whole KEEP confirmed.',
15:'Focused supplied heat-transfer optimization review: complete printed linear law reread. Choose the usual reversible internal engine and specified/equal conductance interpretation, optimize power through temperature drops and heat ratio. All required physics is ordinary conduction/Carnot; declare idealization and unprovided conductance asymmetry. KEEP confirmed.',
16:'Focused supplied qualitative Doppler cogwheel review: whole argument reread. It asks whether runaway is valid, not an exact all-speed transform. Radiation emission recoil, mirror angular momentum and energy/thermal sources close a conservation critique with the stated blueshift premise. KEEP confirmed; no unprovided Lorentz law imported.',
19:'Focused full zero-resistance energy-transfer review: actual L much longer than capacitor size and line dimensions reread. Electromagnetic propagation/inductance and capacitor energy are ordinary IX/VIII content. Finite lossless oscillations or outgoing radiation require stated termination approximations; missing detailed radiation geometry is a parameter limitation, not permission to discard energy as heat. KEEP confirmed.',
20:'Focused supplied permittivity versus friction model: entire Q20 reread. A real velocity-dependent friction needs fluctuation/dispersion/dissipation or quantum field response absent from constant epsilon alone. Unexcited nondissipative classical ideal sheets can have zero drag, but that special limit does not close the general intended friction law. REJECT confirmed on missing central specialized interaction, not the dielectric context.',
21:'Focused fully supplied wave and fitting model: all Q21 PDE, scale limits and three requests reread. Fourier packet evolution and product-average least squares use provided scalar PDE. Finite undamped torus is recurrent; fitted long-time damping is not genuine energy loss. Specify the initial time derivative and order of limits. KEEP confirmed, no field-theory dynamics must be supplied.',
22:'Focused classical massive-charge pulse review: complete f(x-ct), finite support and approximation request reread. Weak recoil/nonrelativistic Lorentz motion plus Maxwell scattering and field energy/momentum suffice at declared order. Large mass means small impulse relative to mc and limited displacement during pulse, not zero conservation accounting. KEEP confirmed.',
24:'Focused actual aircraft-ring premise review: entire two-paragraph Q24 reread. The source demands pressure-caused colour deflection but supplies neither density profile nor a cloud scattering model. Standard refraction/diffraction can challenge its identification, while a literal quantitative flow-optics answer needs more physical input. Whole BORDERLINE retained; no measured glory or invented aerodynamic solution.',
25:'Focused supplied source model and seeded QC (Random 2026100423 second selection): actual 14/92 counts, multiplets, 3-degree resolution, Poisson equal-intensity emissions, attenuation and latitude reread. Geometry/exposure and statistical inference are sufficient; latitude alone leaves zenith acceptance to a declared model. KEEP confirmed, not a cosmic-ray transport derivation.',
26:'Focused distribution-model ambiguity: all Q26 reread. Independent additive Gaussians remain Gaussian; alternative triggering populations give a mixture. Standard goodness-of-fit/model testing distinguishes the intended hypothesis when specified. This is ordinary data analysis even if the physical example is an earthquake. KEEP confirmed, no data fabricated.',
29:'Seeded QC (Random 2026100423 first selection): actual quartic Hamiltonian and quantise/vacuum/excited/second-order requests reread. Quantum ladder/state representation, perturbation and expectation rules are not supplied. Those methods dominate; REJECT confirmed, not from the Hamiltonian label alone.',
31:'Focused supplied probabilities and actual table: full pp6-7 reread. All spin probabilities are already numerical. A global binary joint table would violate the elementary Bell-type probability inequality; a real measurement record needs setting-conditioned denominators and unperformed-measurement conventions. Identifying/constructing that consistency requires ordinary probability, not deriving Born probabilities. KEEP confirmed despite the source table ambiguity.',
32:'Focused semantic-majority review: full Q32 p7 detector assumptions and concluding state/max-probability request reread. Classical locality contradiction is supplied-model logic, but constructing the two-state-pair wavefunction and optimizing its Born probabilities is the substantial central culmination and lacks operational quantum rules. Whole REJECT confirmed; logical opening does not rescue the quantum task.',
33:'Focused mathematical supply versus physical representation review: actual Q33 p7 boson space/boost formula and four-fermion instructions reread. U2B is supplied, but spin-half rotation/antisymmetric state representation U4F and composite embedding are not. They are the central prerequisite for M/intertwiner/state, beyond merely difficult linear algebra. REJECT confirmed.',
34:'Focused explicit classical-function option: actual p8 Hamiltonian and drive reread. It is exactly kinetic p^2/(2m) plus onsite and nearest-neighbour scalar spring energies. Newton/Hooke gives a complete classical mode model; quantization is not requested. Finite no-damping mean power differs from outgoing infinite-chain power and resonance grows. KEEP confirmed with those limits recorded, distinct from an arbitrary unsupplied canonical H model.',
35:'Focused whole plasma release depth: all Q35 p8 read again. Given Debye length, one-dimensional magnetization and thermal/charge densities allow an ordinary electron-escape/charge-separation/ion-acceleration qualitative picture. Full collisionless expansion/trapping and late distribution can need an unprovided kinetic/sheath closure; no quantitative operational PDE is supplied unlike Q11. Requested qualitative-first wording leaves intended later depth genuinely uncertain. BORDERLINE confirmed, not a blanket advanced-plasma rejection.'}
required={int(r['problem_number']) for r in c.execute("select problem_number from units where source_file_id=3139 and review_status='pass_1_complete'")};assert required<=set(details),(required-set(details))
w.writejson(w.ROOT/'reviews/shutdown_ortvay_2000_q1_rationale_history.json',{'before':dict(u[1]),'correction':'Hearing is an explicit ordinary sound-propagation mechanism. Remove speculative relativity interpretation; BORDERLINE remains because drag/contact and precise acoustic doubling timing are underdefined.','changed_at':w.now()})
c.execute('update units set required_physics=?,decision_reason=?,external_physics_if_any=?,primary_spho_domains=?,source_quality_notes=? where screening_unit_id=?',('Ball-ground contact and acoustic feedback for a doubling-speed dog','Ordinary drag, tail tension/gravity and propagation of sound from a trailing impact govern whether further doubling triggers arrive. Radius/drag/contact dynamics and feedback timing are not given, leaving the whole numerical limiting-speed model uncertain. The sound-speed feedback possibility is within ordinary waves, not an inferred relativistic restriction.','Unspecified aerodynamic/contact model and acoustic feedback convention','I_force_motion;II_oscillations_waves','Sound-trigger feedback explicitly printed; density may determine whether drag raises the ball before acoustic signals fail to catch the dog. Doubling is discrete. Ball radius/drag/contact conditions absent. Do not insert a relativistic c bound or fabricate numeric terminal speed.',u[1]['screening_unit_id']));c.commit()
p=w.ROOT/'reviews/shutdown_ortvay_2000_focused_seeded_formats_25.json';w.writejson(p,[dict(screening_unit_id=u[n]['screening_unit_id'],detail=d) for n,d in details.items()]);w.review(p)
assert not c.execute("select 1 from units where source_file_id=3139 and review_status='pass_1_complete'").fetchone();print('Saved twenty-five focused/seeded/format reviews and explicit Q1 rationale correction history.')
