import workflow as w
c=w.connect();u={int(r['problem_number']):r for r in c.execute('select * from units where source_file_id=3136')}
details={
1:'Focused actual-image/provenance review: complete Q1 p2 and downloaded original JPEG actually inspected. Clouds, ground shadows, streets, bridges and river permit registration/scale and solar direction/height estimates. The file decodes as a 3032x2000 JPEG with no EXIF, so no metadata timestamp is claimed. Ordinary ray/shadow geometry and Sun position determine candidate times/cloud heights subject to viewing geometry/season/date priors. Minute precision may not be uniquely supported; that can be evaluated with allowed physics. Whole KEEP confirmed; source image is preserved with exact hash outside raw and linked to Q1.',
2:'Seeded QC (Random 2026100419 first selection): entire Q2 p2 reread, including the alternative pursuer strategy extra question. Square boundary and direction-following algorithm are actual givens. Relative speeds and optimal path geometry determine the guarantee; dramatic fiction adds no outside physics. KEEP confirmed, extra question retained inside Q2.',
3:'Focused water-column/cart review: full Q3 p2 reread. Water mass dominates, tube finite length and cross-section ratio are supplied. In a declared plug-flow approximation, pressure forces on the tube water and tank recoil plus continuity are Newtonian balances; acceleration feedback modifies the stationary Torricelli relation. No viscosity profile or full Navier-Stokes closure is required. KEEP confirmed; no blanket assumption that the outlet inertial term vanishes.',
7:'Focused restitution-model review: full Q7 p2 reread. It explicitly asks a constructed 2D disk/wall model and tests energy conservation. Rotation/tangential-to-normal transfer or a compliant wall oscillator produces normal restitution >1 with conserved total energy; an ordinary lumped contact spring model is sufficient. A full material elasticity tensor is not demanded. KEEP confirmed.',
10:'Focused complete toy-law review: Q10 p3 formulas and all three parts reread. F=M*a supplies the dynamics directly; rotationally invariant 2D matrices have an antisymmetric J part as well as scalar identity. Force laws, drag and identical bodies are printed. Conservation tests, bounded trajectories and stationary rotating arrangements require direct ODE/linear algebra, not unsupplied canonical evolution. KEEP confirmed under the existing supplied-model rule.',
13:'Focused finite-radius buoyancy review: complete Q13 p4 reread. Rotating fluid hydrostatic balance gives a parabolic free surface/effective gravity. Integrating displaced pressure over the finite sphere and minimizing combined effective gravitational/buoyant potential address both size regimes. Unknown wood density/contact/wetting are estimate parameters, not required outside fluid dynamics. KEEP confirmed.',
14:'Focused exotic-context versus actual idealization review: entire Q14 p4 reread. Incompressible self-gravitating fluid replaces actual neutron-star structure. An ellipsoidal Newton potential plus rotating hydrostatic surface condition derives the spheroid relation by mathematical integration; no nuclear EOS, GR or viscous flow law is needed. Branch choice/equilibrium versus stability limits should be distinguished and not supplied as an unexplained remembered formula. Main meaningful equilibrium work stays within ordinary Newton/hydrostatics. KEEP confirmed.',
15:'Focused specified-wind acoustics review: full Q15 p4 reread. Wind is already defined as v=alpha*z with speed much less than sound; it need not be solved from a flow PDE. Advected sound speed and ordinary wave/ray geometry account for paths, pulse delays and caustic/shadow behaviour. Finite-wave interpretation handles ray singularities without turbulence modelling. KEEP confirmed.',
17:'Focused moving-mirror diagnostic review: complete Q17 p4 reread. The gas cloud intentionally removes shape as a clue. Ordinary polarization/spectral/reflection tests may distinguish some configurations, but a universal test of arbitrary fast-moving image versus emitter can depend on unsupplied relativistic Doppler/aberration and can fail for observationally identical sources. No small-speed/model prescription or official worked key resolves the intended requirement. Whole BORDERLINE retained; no invented diagnostic observation.',
18:'Focused accelerating-source prerequisite review: all Q18 p4 reread. No small-speed limit, source-clock convention or explicit Doppler relation is supplied. The requested acceleration/direction-dependent emitted light requires frequency tied to source proper time and relativistic aberration/retarded-time mapping at general speeds. REJECT confirmed on those central missing laws, not on the laser apparatus.',
19:'Focused supplied-target versus operational-dynamics review: complete Q19 p4 and intact correction formula reopened. gamma(v) and target relativistic cross section are indeed printed. They do not give p(v), energy or central-force trajectory evolution needed to derive it. The entire task asks for that derivation. REJECT confirmed, acknowledging all supplied equations rather than falsely calling the correction absent.',
20:'Seeded QC (Random 2026100419 second selection): full Q20 p5 reread, both static and maximal-spin cases plus comfort/mass constraints. No metric/geodesic/proper-acceleration/tidal relation is given. Those missing GR tools centrally determine the whole travel bound. REJECT confirmed; a selected comfort threshold alone would not make the model operational.',
22:'Focused complete modified-law review: Q22 p5 force/density equations and solar-system extra question reread. The pairwise G(separation) law explicitly replaces Newton G, while a defined thin disk supplies density. Superposition/inverse integral and centripetal-force constraints are mathematics on the provided classical model. The printed alpha length-unit typo and kernel nonuniqueness need disclosure, but no unrelated MOND/GR model is needed. Whole KEEP confirmed.',
24:'Focused matrix versus oscillator prerequisite review: complete 3x3 Hamiltonian Q24 p5 reopened. Algebra can reduce the matrix for a symbolic H0 eigenvalue, but the requested actual spectrum/eigenstates require quantum harmonic-oscillator levels and state representation. These are only called well known, not supplied. REJECT confirmed consistently with earlier partial quantum Hamiltonian cases.',
25:'Focused formal ordering versus quantum representation review: entire Q25 p6 reread. Three kinetic operators and usual-commutator wording are acknowledged. Hermiticity, gauge compensation and discontinuous-interface wavefunction conditions require a momentum differential representation, Hilbert/current convention and quantum matching law not supplied operationally. REJECT confirmed; real semiconductor context itself is not grounds for rejection.',
26:'Focused partial supplied quantum model review: entire Q26 p6 Hamiltonian, minimal coupling and Zeeman term reread. They supply some physics but Pauli matrices are only named, and oscillator/commutator quantization needed to compute Landau-spin levels is absent. The central spectrum depends on those unsupplied quantum tools. REJECT confirmed without ignoring the supplied substitutions.',
27:'Focused whole-parent/ODE review: complete Q27 p6 read through closing general-statement request. Part a supplies rotational ODE but its endpoint omega(1/a) conflicts with the declared [0,1] domain. Parts b/c centrally compare time-dependent and stationary quantum perturbation at first and second order, whose rules/evolution are not provided. Whole REJECT confirmed; no split or rescue of the mathematical opening.',
30:'Focused stochastic sufficiency review: complete Q30 p7 reread. Under many independent rare possible collisions a Poisson limit gives lambda=-log(1-p) and P(N>=2)=1-(1+lambda)*exp(-lambda). With arbitrary correlations the one number p is insufficient, demonstrable by two count distributions sharing P(N>=1). Both intended limit and valid insufficiency analysis need probability mathematics, not strong-force microphysics. KEEP confirmed with the additional assumption explicit.',
31:'Focused data-analysis/format review: complete Q31 p7 reread. It directs contestants to choose maps/databases and construct/test scale relations. Model dimensional geometry/topology and measured log-distribution fitting are allowed mathematical/data work; no fixed missing original dataset exists and no geological evolution law is mandated. KEEP confirmed; no dataset or empirical scaling results fabricated.',
32:'Focused experimental-model review: full Q32 p7 reread. It describes a held unwinding strip along a wall and asks centre height plus break location/time. Measured geometry/linear density and ordinary Newton torque/tension model suffice; strength is a measurable material parameter rather than a request for an unsupplied fracture theory. KEEP confirmed under a declared slip/contact/tensile-strength idealization, with no performed experiment claimed.'}
p=w.ROOT/'reviews/shutdown_ortvay_2004_focused_seeded_formats_20.json';w.writejson(p,[dict(screening_unit_id=u[n]['screening_unit_id'],detail=d) for n,d in details.items()]);w.review(p)
assert not c.execute("select 1 from units where source_file_id=3136 and review_status='pass_1_complete'").fetchone()
print('Saved twenty focused, seeded and format checks.')
