import workflow as w
c=w.connect();u={int(r['problem_number']):r for r in c.execute('select * from units where source_file_id=3128')}
details={
7:'Focused slowly changed stiffness review: complete rendered p2 unilateral-spring problem reread. Energy-rate dE/dt comes from the supplied spring force and its parameter dependence. Averaging this work over piecewise oscillations derives the adiabatic action law if desired; no outside physical principle must be assumed. Slack/free-flight transition and limiting integrals remain Newtonian. KEEP confirmed.',
9:'Focused supplied direction-only action review: intact p2 definitions reread. dL/dv=(I-nn)/v times dL/dn and its time derivative yield a mass-like velocity Hessian plus ordinary derivative terms. Degenerate cases require constraint mathematics; no relativity or external modified-dynamics law is imported. KEEP confirmed.',
10:'Focused nonlocal functional review: full integral and kernel in p2 render reopened. Varying q at both occurrences produces past and future contributions with the chosen action endpoint. Exponential kernels permit a linear ODE/boundary reduction. The problem explicitly defines the model and requests action variation; endpoint freedom and unusual 1/m kinetic coefficient are source notes, not permission to substitute an unsupplied dissipative law. KEEP confirmed.',
12:'Focused mode ambiguity review: rendered p3 short task reread. Dimensions really are 20 cm by 1 cm by 0.4 cm. A longitudinal strike excites conventional compression waves; transverse deflection excites modes requiring the unsupplied beam-bending law. No impact direction or intended mode is stated. BORDERLINE confirmed instead of assuming all struck rods require outside beam theory.',
20:'Focused target-model review: complete Q20 p4 reread. It rejects relativistic theory as the proposed mechanism but demands reproducing its exact lensing target and weak-field limit. Those target relations are not printed. Classical Fermat ray integration alone cannot define the comparison without importing GR; whole problem REJECT confirmed.',
24:'Focused structure versus pure geometry review: full single-sentence Q24 p5 reread. No GaAs basis or coordination is supplied, so semiconductor-specific packing and unrestricted binary sphere packing are distinct tasks. A source solution could resolve intended assumptions, but none is acquired/linked in the organizer archive. BORDERLINE retained without adding external lattice knowledge.',
25:'Focused trace-model review: intact p5 formula reread. A two-by-two eigenphase can follow from trace only if determinant and representation are known; conventional conservative wave matrices are unimodular, but neither that condition nor the Bloch mapping is stated. Band gaps are substantial mathematical work once such assumptions are supplied; conduction also depends on unprovided filling. BORDERLINE confirmed for partial model adequacy.',
27:'Focused ordinary-field derivation review: entire p5 collimation task reread. In the stated slow-gradient/nonrelativistic limit, gyro-averaged Lorentz force and divergence-free magnetic flux yield transverse-energy over B invariance. Total kinetic energy is conserved by magnetic force, then an ordinary Jacobian maps initial isotropic momentum/angle distributions. No quantum or specialized plasma model is necessary. KEEP confirmed.',
28:'Focused complete-ensemble review: all p6 star graph equations and ordered limits reread. Conditional on central sign, the supplied Boltzmann weight factors into independent two-valued peripheral terms; elementary concentration gives mean tanh(beta*(J*s0+h)), and the given order of limits selects the positive-field branch before field removal. Conventional ±1 domain is a documented notation convention; energy and probability laws are actually supplied. KEEP confirmed, unlike prior unsupplied Ising-model tasks.',
29:'Focused data/model review: all p6 fall assumptions and both downloaded original chart renders reread. The source explicitly supplies constant-coefficient quadratic drag even above sound speed, and linked temperature/sound-speed data. Hydrostatic pressure integration, gas density and Newtonian trajectory yield crossing times and differing Mach/speed maxima. Historical graph temperature-axis correction is preserved explicitly with attribution, not silently substituted. KEEP confirmed.',
6:'Seeded QC (Random 2026100411, first selection): all p2 nested-cylinder geometry/parts reread. The tangent outer axle and radius-half coaxial inner body fix inertia and initial conditions. Torque, normal force and Coulomb static-friction inequality determine both thresholds. KEEP confirmed.',
3:'Seeded QC (Random 2026100411, second selection, experimental format): complete p1 leg-motion observation reread. It expressly requests a simple model and ratio; effective body/limb inertia and elastic oscillation coupling are foundational mechanics. No specialized anatomical law is structurally demanded. KEEP confirmed with model-dependent numeric caveat.'}
p=w.ROOT/'reviews/shutdown_ortvay_2012_focused_seeded_qc_12.json';w.writejson(p,[dict(screening_unit_id=u[n]['screening_unit_id'],detail=d) for n,d in details.items()]);w.review(p)
print('Saved twelve focused/seeded reviews; decisions unchanged.')
