import workflow as w
c=w.connect();u={int(r['problem_number']):r for r in c.execute('select * from units where source_file_id=3126')}
details={
7:'Focused entire dust-tail model review: full four parts p2 reopened. Radiative pressure and Kepler motion are ordinary physics, but brightness/extinction depends centrally on unprovided grain optical response, injection and viewing/distribution assumptions. No year-directory worked solution resolves whether a conventional toy model is intended. BORDERLINE confirmed; neither advanced context alone nor invented parameters decide it.',
14:'Focused required-law review: full two parts and p3 drawing/formulas reopened. Static dielectric-sphere polarization follows electrostatic boundary conditions. Dipole radiation supplies scattered momentum and intensity-gradient force; both conventional Maxwell radiation and harmonic response lie in the explicit EM scope. Balancing forces and transverse Newtonian oscillations then use given intensity/geometry. KEEP confirmed; optical tweezer terminology is not the criterion.',
20:'Focused beam-versus-ordinary-Hooke review: whole p4 statement reopened. Distributed lateral deflection of a clamped thin rod is the main requested function; axial Hooke force alone does not determine it. No moment-curvature or beam equation is supplied, and constants-table permission only supplies coefficients. Consistent with already established flexural beam decisions, REJECT confirmed without revising the rubric.',
21:'Focused steel-pipe model review: complete two-sentence problem reopened. Ordinary gravity/eddy currents permit a linear-response model, but strong ferromagnetic response and stability may depend on nonlinear or hysteretic constitutive data not supplied. No actual solution is available to distinguish the intended model. BORDERLINE remains; steel keyword alone does not force REJECT.',
23:'Focused insulated/frictional piston review: full initial data and friction assumption reopened. A declared adiabatic-gas approximation gives pressure versus volume and a piecewise Newton equation until static threshold; friction heat can remain in the insulating mechanical parts. Other heat allocations change the quantitative answer, and very small mass tests quasistatic assumptions. These are ordinary thermodynamic model limitations, not external specialized prerequisites. KEEP confirmed with explicit quality note.',
29:'Focused supplied operator algebra review: intact p5 formulas reopened. [a,a†]=I gives [N,a]=-a and ladder norms from N=a†a; positive quadratic forms establish the zero state, with b annihilation generating a normalized coefficient recurrence. Applying b† produces the next two states. Hyperbolic functions are supplied linear algebra, not relativistic spacetime laws. Optional coherent-state definition is peripheral. Whole compulsory task KEEP confirmed.',
30:'Focused binary-basis/counting review: complete p5 formula and request reopened. A one-particle creation/deletion term changes one occupied index to one empty index; binary occupancy is explicitly stated. For generic coefficients each n-sector has C(N,n) rows with n(N-n) off-diagonal destinations and a generic diagonal, apart from the vacuum. Fermionic sign conventions do not change which generic entries are nonzero, so specialized anticommutator/quantum dynamics is not required for the requested logarithmic count. Fixed n versus extensive n must be distinguished. KEEP confirmed.',
32:'Focused topology-versus-quantum dependency review: full p6 statement reopened. Quotient fixed points, half-plane and permutation eigenvalues are mathematical; the Robin and Hamiltonian expressions are actually provided. But deriving physical boundary restrictions, time evolution and particle-statistics interpretation requires unprovided quantum rules. Meaningful work is mixed near the scope boundary. BORDERLINE retained; no supplied full Schrodinger PDE imported from neighbouring questions.',
35:'Focused data-analysis/source review: full p7 exercise and both SQL examples reopened. Classical line-of-sight Doppler fitting/averaging and galactic coordinate geometry suffice; no unsupplied galaxy dynamics or GR equation is required. Original official DR7 SQL endpoint returned 100 validated records with requested l,b,z columns, preserved with hash/query. The unordered example is explicitly not the full exercise dataset. KEEP confirmed with source access and selection limitations.',
2:'Experimental format QC: complete bicycle measurement task reopened. Mechanical work per time and gravity/coast-down/drive comparison allow calibration with household instruments, including losses through measurement rather than assumed aero laws. KEEP confirmed; actual measurement request remains one experimental problem.',
10:'Focused supplied-map QC: all airfoil conditions reopened. The map and finite-velocity condition do not themselves define a complex flow field or circulation; the contestant must import unsupplied potential-flow hydrodynamics to construct it. Whole problem REJECT confirmed.',
18:'Seeded QC (Random 2026100409, first selection): complete p3 problem and coloured torus geometry reopened. Fusion reactor is an inactive story; the sole actual task is the grounded-cavity potential of a static charge. Electrostatic boundary mathematics supplies the required physics. KEEP confirmed.',
19:'Seeded QC (Random 2026100409, second selection): all p4 tensor-resistance conditions reopened. Anisotropic conductivity is expressly supplied and ideal end contacts define the boundary problem. Ordinary local Ohm law and continuity plus PDE mathematics determine limiting/exact resistances. KEEP confirmed.'}
p=w.ROOT/'reviews/shutdown_ortvay_2014_focused_seeded_qc_13.json';w.writejson(p,[dict(screening_unit_id=u[n]['screening_unit_id'],detail=d) for n,d in details.items()]);w.review(p)
print('Saved thirteen focused/seeded/format reviews; decisions unchanged.')
