import workflow as w
c=w.connect();u={int(r['problem_number']):r for r in c.execute('select * from units where source_file_id=3123')}
details={
1:'Focused review: complete Q1 p1 and flag bands reopened. The source asks a qualitative visual-width explanation, but irradiation/perception versus chromatic lens effects is unspecified. No organizer solution supplies a visual-response model. BORDERLINE confirmed rather than importing a neuroscience relation.',
7:'Focused whole-problem weighting: complete Q7 p3 and dome diagram reread. Classical nonuniqueness has explicit ODE and geometric force, but the mandatory final surface eigenstate is a substantial independent calculation requiring an unsupplied quantum surface Hamiltonian. Neither simply counting clauses nor rescuing the classical section settles dominance. BORDERLINE retained.',
11:'Focused elastic-prerequisite/format check: complete Q11 and apparatus p3 reopened. Contact is along uniform rod axes. Applying ordinary Hooke stress E*strain and Newton to a small axial slice derives wave speed sqrt(E/rho); contact duration then measures the round trip. No specialized flexural stiffness or contact-fracture law is needed. Experimental KEEP confirmed.',
13:'Focused supplied-model check: intact Q13 kinetic/spring/coupling expression p4 reread. It defines ordinary bilinear coupled oscillators. Newton gives m0*Xddot+m0*w0^2*X+integral C*x=0 and rho*(xddot+w^2*x)+C*X=0. Eliminating x by forced-oscillator integration yields memory and apparent damping, while total energy is conserved. KEEP confirmed without quantum bath assumptions.',
15:'Focused fluid prerequisite check: complete Q15 p4 reopened. One-dimensional wetting column at negligible viscosity has prescribed capillary pressure and gravitational weight; momentum balance must account for incoming liquid. Overshoot follows that ordinary variable-mass model, with no roll-wave or turbulent closure. KEEP confirmed.',
18:'Focused biological/model check: Q18 p5 reread. Defined hydraulic resistance and a compliant chamber give volume balance C*dp/dt=Iin-p/R in the explicit linear-compliance approximation. Unknown C is a material/model parameter, not a requirement to know cardiovascular physiology. KEEP confirmed; unspecified compliance remains disclosed.',
21:'Focused negative-index model check: Q21 p5 reread. Negative n is expressly supplied, so Snell ray directions and slab imaging are sufficient. Chromatic displacement can be expressed via measured n(lambda), bandwidth and geometric depth; no derivation of a metamaterial response is requested. KEEP confirmed with dispersion-data limitation retained.',
28:'Focused supplied-model review: Q28 p7 reread. Given differential operators allow their brackets to be calculated, and the unitary target is explicit. However which brackets constitute canonical commutation and which domains count as a physical representation remain unstated; topological boundary conditions also affect the counterexample. BORDERLINE confirmed, consistent with partially supplied canonical-model cases.',
36:'Focused source-linked model review: whole Q36 p10 plus reference Sections II-III and Appendix pp2-3,8 read and rendered formulas inspected. The appendix supplies scalar equations24-33, defines every moment and supplies the closure approximation. At weak coupling, solve the three driven atomic variables at zeroth order, integrate the supplied linear moment equations at first order, then integrate d<Nn>/dt at second order. Analytical integration/expansion is mathematics; no unsupplied quantum law is required. KEEP confirmed; essential PDF registered and preserved.',
37:'Focused ambiguity review: all three Q37 parts p10 reread. Newtonian central mass loss changes outer Kepler elements and tidal stability, but direct passing-wave disruption of the inner binary is a distinct effect needing strain/force coupling. The statement supplies neither and does not disambiguate its last wording. Substantial classical work plus possible central outside dependency supports whole-problem BORDERLINE.',
38:'Focused supplied-radiation review: Q38 p11 and all explicit rate formulas reopened. Radiation loss is supplied; for instance Newtonian interactions can transfer orbital energy and widen a radiating binary while the external reservoir supplies energy. Integrating ordinary multi-body equations plus the specified secular loss yields decreasing frequency without an extra GR emission relation. KEEP confirmed; dimensional G-power typo stays flagged.',
6:'Seeded KEEP QC (2026100406): whole Q6 p2 reread. Required endpoint and exit-direction constraints select radial potentials through ordinary energy/angular-momentum orbit equations. Inverse construction is mathematical mechanics, without a specialized force law prerequisite. KEEP confirmed.',
25:'Seeded REJECT QC (2026100406): whole Q25 p7 reread. A tensor kinetic term does not give the particle-field action or covariant variation/force rules; requested Maxwell modification and tensor dynamics centrally need unsupplied relativistic field formalism. REJECT confirmed.'}
p=w.ROOT/'reviews/shutdown_ortvay_2017_focused_seeded_qc_13.json';w.writejson(p,[dict(screening_unit_id=u[n]['screening_unit_id'],detail=d) for n,d in details.items()]);w.review(p)
print('Saved thirteen source-grounded focused/seeded QC reviews; decisions unchanged.')
